// This file is auto-generated by @hey-api/openapi-ts

export { getMeta, type Options } from './sdk.gen';
export type { ClientOptions, GetMetaData, GetMetaError, GetMetaErrors, GetMetaResponse, GetMetaResponses, Meta, Problem } from './types.gen';
