// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

export type Meta = {
    /**
     * The build version of the binary.
     */
    version: string;
    /**
     * The mode the server runs in.
     */
    mode: 'local';
};

/**
 * RFC 9457 problem details with a stable code.
 */
export type Problem = {
    type: string;
    title: string;
    status: number;
    detail?: string;
    instance?: string;
    /**
     * A stable machine-readable error code.
     */
    code: string;
};

export type Bundle = {
    id: string;
    /**
     * In local mode, the bundle folder relative to the served folder.
     */
    slug: string;
    title: string;
    /**
     * The frontmatter type of the main doc.
     */
    profile_key: string;
    source_kind: 'local' | 'db' | 'github';
    /**
     * The path of the main doc in the bundle.
     */
    main_doc: string;
    current_version: Version;
    updated_at: string;
    verdict?: BundleVerdict;
    /**
     * Why the latest run on the current version failed, when it failed.
     */
    run_error?: string;
};

/**
 * The verdict of the bundle's latest completed run. It is stale when that run is not on the current version.
 */
export type BundleVerdict = {
    run_id: string;
    version_number: number;
    /**
     * lint means only the lint stage ran.
     */
    kind: 'lint' | 'full';
    result: VerdictResult;
    score: number;
    radar: {
        [key: string]: number;
    };
    waiver_count: number;
    /**
     * Checks in adoption mode (REQ-133).
     */
    relaxed_count: number;
    /**
     * Open MUST findings.
     */
    must: number;
    should: number;
    info: number;
};

export type VerdictResult = 'build_ready' | 'not_build_ready' | 'stale';

export type CreateBundleRequest = {
    /**
     * The profile key.
     */
    profile: string;
    /**
     * The bundle folder name.
     */
    name: string;
    title?: string;
};

export type Run = {
    id: string;
    bundle_id: string;
    version_id: string;
    version_number: number;
    profile_key: string;
    profile_version: number;
    kind: 'lint' | 'full';
    status: 'queued' | 'running' | 'complete' | 'failed';
    stage: string;
    error: string;
    started_at: string;
    finished_at?: string;
    verdict?: BundleVerdict;
};

export type RunList = {
    items: Array<Run>;
};

/**
 * A range of text with context (SDD §8.8).
 */
export type Anchor = {
    file: string;
    heading_path: Array<string>;
    quote: string;
    prefix: string;
    suffix: string;
    /**
     * Byte offset of the quote in the file.
     */
    start: number;
    end: number;
};

export type Finding = {
    id: string;
    check_slug: string;
    level: 'MUST' | 'SHOULD' | 'INFO';
    stage: string;
    /**
     * The check is in adoption mode, so it reports at INFO (REQ-133).
     */
    relaxed: boolean;
    message: string;
    fix?: string;
    anchor: Anchor;
};

export type FindingList = {
    items: Array<Finding>;
};

export type Profile = {
    key: string;
    name: string;
    version: number;
    /**
     * built-in, or the path of the profile file.
     */
    origin: string;
};

export type ProfileList = {
    items: Array<Profile>;
    /**
     * Profile files that did not load, with the reason.
     */
    problems: Array<string>;
};

export type BundleList = {
    items: Array<Bundle>;
    next_cursor?: string;
    /**
     * Folders that are not valid bundles, for example with two main docs (REQ-001).
     */
    problems: Array<BundleProblem>;
};

export type BundleProblem = {
    path: string;
    message: string;
};

export type BundleFile = {
    path: string;
    size: number;
    sha256: string;
    is_main_doc: boolean;
};

export type FileList = {
    version: Version;
    items: Array<BundleFile>;
};

export type Version = {
    id: string;
    number: number;
    created_by: string;
    message: string;
    created_at: string;
};

export type VersionList = {
    items: Array<Version>;
    next_cursor?: string;
};

export type WriteResult = {
    version: Version;
    /**
     * False when the write left the bundle unchanged, so no version was created.
     */
    changed: boolean;
};

export type RenameRequest = {
    from: string;
    to: string;
    base_version: string;
};

export type ImportRequest = {
    /**
     * The bundle folder name. The default comes from the file name or the doc title.
     */
    name?: string;
    /**
     * A .md file or a .zip file.
     */
    file?: Blob | File;
    /**
     * Pasted markdown.
     */
    text?: string;
};

export type Diff = {
    from: Version;
    to: Version;
    files: Array<FileDiff>;
    /**
     * The sections of the main doc, matched by heading path.
     */
    sections: Array<SectionDiff>;
};

export type ChangeStatus = 'added' | 'removed' | 'modified' | 'unchanged';

export type FileDiff = {
    path: string;
    status: ChangeStatus;
    binary: boolean;
    /**
     * Line operations for a modified text file. Empty otherwise.
     */
    lines: Array<LineOp>;
};

export type SectionDiff = {
    heading_path: Array<string>;
    status: ChangeStatus;
    lines: Array<LineOp>;
};

export type LineOp = {
    op: 'equal' | 'insert' | 'delete';
    /**
     * One or more whole lines, each ending with a newline except possibly the last line of the file.
     */
    text: string;
};

export type RenderRequest = {
    markdown: string;
    /**
     * When set, relative image links resolve to files in this bundle.
     */
    bundle_id?: string;
    /**
     * The path of the file in the bundle, so relative links resolve from its folder.
     */
    path?: string;
};

export type RenderResult = {
    /**
     * HTML. Each block element has data-src-start and data-src-end (byte offsets into the markdown) and data-line (the 1-based first line). Mermaid blocks are <pre class="mermaid">.
     *
     */
    html: string;
};

export type RunId = string;

export type BundleId = string;

/**
 * A file path relative to the bundle folder, with / separators.
 */
export type PathQuery = string;

export type VersionQuery = string;

/**
 * The version the change is based on. When the bundle has a newer version, the request fails with code version_conflict, so a change never overwrites one it did not see.
 *
 */
export type BaseVersion = string;

export type Cursor = string;

export type Limit = number;

export type GetMetaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/meta';
};

export type GetMetaErrors = {
    /**
     * An error.
     */
    default: Problem;
};

export type GetMetaError = GetMetaErrors[keyof GetMetaErrors];

export type GetMetaResponses = {
    /**
     * The server version and mode.
     */
    200: Meta;
};

export type GetMetaResponse = GetMetaResponses[keyof GetMetaResponses];

export type ListBundlesData = {
    body?: never;
    path?: never;
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/bundles';
};

export type ListBundlesErrors = {
    /**
     * An error.
     */
    default: Problem;
};

export type ListBundlesError = ListBundlesErrors[keyof ListBundlesErrors];

export type ListBundlesResponses = {
    /**
     * One page of bundles.
     */
    200: BundleList;
};

export type ListBundlesResponse = ListBundlesResponses[keyof ListBundlesResponses];

export type CreateBundleData = {
    body: CreateBundleRequest;
    path?: never;
    query?: never;
    url: '/bundles';
};

export type CreateBundleErrors = {
    /**
     * An error.
     */
    default: Problem;
};

export type CreateBundleError = CreateBundleErrors[keyof CreateBundleErrors];

export type CreateBundleResponses = {
    /**
     * The new bundle.
     */
    201: Bundle;
};

export type CreateBundleResponse = CreateBundleResponses[keyof CreateBundleResponses];

export type ImportBundleData = {
    body: ImportRequest;
    path?: never;
    query?: never;
    url: '/bundles/import';
};

export type ImportBundleErrors = {
    /**
     * An error.
     */
    default: Problem;
};

export type ImportBundleError = ImportBundleErrors[keyof ImportBundleErrors];

export type ImportBundleResponses = {
    /**
     * The new bundle.
     */
    201: Bundle;
};

export type ImportBundleResponse = ImportBundleResponses[keyof ImportBundleResponses];

export type GetBundleData = {
    body?: never;
    path: {
        bundleId: string;
    };
    query?: never;
    url: '/bundles/{bundleId}';
};

export type GetBundleErrors = {
    /**
     * An error.
     */
    default: Problem;
};

export type GetBundleError = GetBundleErrors[keyof GetBundleErrors];

export type GetBundleResponses = {
    /**
     * The bundle.
     */
    200: Bundle;
};

export type GetBundleResponse = GetBundleResponses[keyof GetBundleResponses];

export type DeleteFileData = {
    body?: never;
    path: {
        bundleId: string;
    };
    query: {
        /**
         * A file path relative to the bundle folder, with / separators.
         */
        path: string;
        /**
         * The version the change is based on. When the bundle has a newer version, the request fails with code version_conflict, so a change never overwrites one it did not see.
         *
         */
        base_version: string;
    };
    url: '/bundles/{bundleId}/files';
};

export type DeleteFileErrors = {
    /**
     * An error.
     */
    default: Problem;
};

export type DeleteFileError = DeleteFileErrors[keyof DeleteFileErrors];

export type DeleteFileResponses = {
    /**
     * The version that the change created.
     */
    200: WriteResult;
};

export type DeleteFileResponse = DeleteFileResponses[keyof DeleteFileResponses];

export type ListFilesData = {
    body?: never;
    path: {
        bundleId: string;
    };
    query?: {
        version?: string;
    };
    url: '/bundles/{bundleId}/files';
};

export type ListFilesErrors = {
    /**
     * An error.
     */
    default: Problem;
};

export type ListFilesError = ListFilesErrors[keyof ListFilesErrors];

export type ListFilesResponses = {
    /**
     * The files, sorted by path.
     */
    200: FileList;
};

export type ListFilesResponse = ListFilesResponses[keyof ListFilesResponses];

export type GetFileContentData = {
    body?: never;
    path: {
        bundleId: string;
    };
    query: {
        /**
         * A file path relative to the bundle folder, with / separators.
         */
        path: string;
        version?: string;
    };
    url: '/bundles/{bundleId}/files/content';
};

export type GetFileContentErrors = {
    /**
     * An error.
     */
    default: Problem;
};

export type GetFileContentError = GetFileContentErrors[keyof GetFileContentErrors];

export type GetFileContentResponses = {
    /**
     * The file content.
     */
    200: Blob | File;
};

export type GetFileContentResponse = GetFileContentResponses[keyof GetFileContentResponses];

export type PutFileContentData = {
    body: Blob | File;
    path: {
        bundleId: string;
    };
    query: {
        /**
         * A file path relative to the bundle folder, with / separators.
         */
        path: string;
        /**
         * The version the change is based on. When the bundle has a newer version, the request fails with code version_conflict, so a change never overwrites one it did not see.
         *
         */
        base_version: string;
    };
    url: '/bundles/{bundleId}/files/content';
};

export type PutFileContentErrors = {
    /**
     * An error.
     */
    default: Problem;
};

export type PutFileContentError = PutFileContentErrors[keyof PutFileContentErrors];

export type PutFileContentResponses = {
    /**
     * The version after the write.
     */
    200: WriteResult;
};

export type PutFileContentResponse = PutFileContentResponses[keyof PutFileContentResponses];

export type RenameFileData = {
    body: RenameRequest;
    path: {
        bundleId: string;
    };
    query?: never;
    url: '/bundles/{bundleId}/files/rename';
};

export type RenameFileErrors = {
    /**
     * An error.
     */
    default: Problem;
};

export type RenameFileError = RenameFileErrors[keyof RenameFileErrors];

export type RenameFileResponses = {
    /**
     * The version that the change created.
     */
    200: WriteResult;
};

export type RenameFileResponse = RenameFileResponses[keyof RenameFileResponses];

export type ListVersionsData = {
    body?: never;
    path: {
        bundleId: string;
    };
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/bundles/{bundleId}/versions';
};

export type ListVersionsErrors = {
    /**
     * An error.
     */
    default: Problem;
};

export type ListVersionsError = ListVersionsErrors[keyof ListVersionsErrors];

export type ListVersionsResponses = {
    /**
     * One page of versions.
     */
    200: VersionList;
};

export type ListVersionsResponse = ListVersionsResponses[keyof ListVersionsResponses];

export type DiffVersionsData = {
    body?: never;
    path: {
        bundleId: string;
    };
    query: {
        from: string;
        to: string;
    };
    url: '/bundles/{bundleId}/diff';
};

export type DiffVersionsErrors = {
    /**
     * An error.
     */
    default: Problem;
};

export type DiffVersionsError = DiffVersionsErrors[keyof DiffVersionsErrors];

export type DiffVersionsResponses = {
    /**
     * The differences.
     */
    200: Diff;
};

export type DiffVersionsResponse = DiffVersionsResponses[keyof DiffVersionsResponses];

export type ExportBundleData = {
    body?: never;
    path: {
        bundleId: string;
    };
    query?: {
        version?: string;
    };
    url: '/bundles/{bundleId}/export';
};

export type ExportBundleErrors = {
    /**
     * An error.
     */
    default: Problem;
};

export type ExportBundleError = ExportBundleErrors[keyof ExportBundleErrors];

export type ExportBundleResponses = {
    /**
     * The .zip file.
     */
    200: Blob | File;
};

export type ExportBundleResponse = ExportBundleResponses[keyof ExportBundleResponses];

export type ListRunsData = {
    body?: never;
    path: {
        bundleId: string;
    };
    query?: {
        limit?: number;
    };
    url: '/bundles/{bundleId}/runs';
};

export type ListRunsErrors = {
    /**
     * An error.
     */
    default: Problem;
};

export type ListRunsError = ListRunsErrors[keyof ListRunsErrors];

export type ListRunsResponses = {
    /**
     * The runs.
     */
    200: RunList;
};

export type ListRunsResponse = ListRunsResponses[keyof ListRunsResponses];

export type GetRunData = {
    body?: never;
    path: {
        runId: string;
    };
    query?: never;
    url: '/runs/{runId}';
};

export type GetRunErrors = {
    /**
     * An error.
     */
    default: Problem;
};

export type GetRunError = GetRunErrors[keyof GetRunErrors];

export type GetRunResponses = {
    /**
     * The run.
     */
    200: Run;
};

export type GetRunResponse = GetRunResponses[keyof GetRunResponses];

export type ListFindingsData = {
    body?: never;
    path: {
        runId: string;
    };
    query?: never;
    url: '/runs/{runId}/findings';
};

export type ListFindingsErrors = {
    /**
     * An error.
     */
    default: Problem;
};

export type ListFindingsError = ListFindingsErrors[keyof ListFindingsErrors];

export type ListFindingsResponses = {
    /**
     * The findings.
     */
    200: FindingList;
};

export type ListFindingsResponse = ListFindingsResponses[keyof ListFindingsResponses];

export type ListProfilesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/profiles';
};

export type ListProfilesErrors = {
    /**
     * An error.
     */
    default: Problem;
};

export type ListProfilesError = ListProfilesErrors[keyof ListProfilesErrors];

export type ListProfilesResponses = {
    /**
     * The profiles.
     */
    200: ProfileList;
};

export type ListProfilesResponse = ListProfilesResponses[keyof ListProfilesResponses];

export type RenderMarkdownData = {
    body: RenderRequest;
    path?: never;
    query?: never;
    url: '/render';
};

export type RenderMarkdownErrors = {
    /**
     * An error.
     */
    default: Problem;
};

export type RenderMarkdownError = RenderMarkdownErrors[keyof RenderMarkdownErrors];

export type RenderMarkdownResponses = {
    /**
     * The HTML.
     */
    200: RenderResult;
};

export type RenderMarkdownResponse = RenderMarkdownResponses[keyof RenderMarkdownResponses];
