// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

export type Meta = {
    /**
     * The build version of the binary.
     */
    version: string;
    /**
     * The mode the server runs in.
     */
    mode: 'local';
};

/**
 * RFC 9457 problem details with a stable code.
 */
export type Problem = {
    type: string;
    title: string;
    status: number;
    detail?: string;
    instance?: string;
    /**
     * A stable machine-readable error code.
     */
    code: string;
};

export type GetMetaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/meta';
};

export type GetMetaErrors = {
    /**
     * An error.
     */
    default: Problem;
};

export type GetMetaError = GetMetaErrors[keyof GetMetaErrors];

export type GetMetaResponses = {
    /**
     * The server version and mode.
     */
    200: Meta;
};

export type GetMetaResponse = GetMetaResponses[keyof GetMetaResponses];
