package main

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"sort"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	"gopkg.in/yaml.v3"

	"github.com/alternayte/speccy/internal/engine/lint"
	"github.com/alternayte/speccy/internal/features/profile"
	"github.com/alternayte/speccy/internal/features/review"
	"github.com/alternayte/speccy/internal/mcpserver"
	"github.com/alternayte/speccy/internal/source"
)

// The docs site's generated pages, and the files that the site and the app read from them.
const (
	docsDir       = "site/src/content/docs"
	checksPage    = docsDir + "/reference/checks.md"
	schemaPage    = docsDir + "/reference/profile-schema.md"
	actionPage    = docsDir + "/reference/github-action.md"
	mcpPage       = docsDir + "/reference/mcp-tools.md"
	cliPage       = docsDir + "/reference/cli.md"
	configPage    = docsDir + "/reference/configuration.mdx"
	domainWords   = "site/styles/Speccy/DomainWords.yml"
	catalogTS     = "web/src/lib/check-catalog.gen.ts"
	catalogSource = "internal/features/profile/catalog.yaml"
	generated     = "<!-- Generated by `go run ./tools/buildtool docs-ref` from %s. Do not edit this file. -->"
)

// cmdDocsRef writes the generated Reference pages. With check, it writes nothing: it fails when
// a generated file differs from the committed one, when a YAML sample does not parse with
// Speccy's own loader, when a sample runs a command the CLI does not have, or when the
// Configuration page misses a SPECCY_ variable.
func cmdDocsRef(check bool) error {
	usage, err := cliUsage()
	if err != nil {
		return err
	}
	pages := map[string]func() (string, error){
		checksPage:  checkCatalog,
		schemaPage:  profileSchemaPage,
		actionPage:  actionRefPage,
		mcpPage:     mcpToolsPage,
		cliPage:     func() (string, error) { return cliRefPage(usage), nil },
		domainWords: domainWordsRule,
		catalogTS:   catalogSlugsTS,
	}
	var problems []string
	for _, path := range slices.Sorted(func(yield func(string) bool) {
		for p := range pages {
			if !yield(p) {
				return
			}
		}
	}) {
		want, err := pages[path]()
		if err != nil {
			return fmt.Errorf("%s: %w", path, err)
		}
		if !check {
			if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
				return err
			}
			if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
				return err
			}
			continue
		}
		have, err := os.ReadFile(path)
		if err != nil || string(have) != want {
			problems = append(problems, fmt.Sprintf("%s is stale. Run `go run ./tools/buildtool docs-ref`.", path))
		}
	}
	if !check {
		return nil
	}
	sampleProblems, err := checkSamples(commandsOf(usage))
	if err != nil {
		return err
	}
	problems = append(problems, sampleProblems...)
	configProblems, err := checkConfigVars()
	if err != nil {
		return err
	}
	problems = append(problems, configProblems...)
	if len(problems) > 0 {
		return errors.New("the docs are not current:\n  " + strings.Join(problems, "\n  "))
	}
	return nil
}

// catalogEntry is the Check catalog text of one check the engine runs itself.
type catalogEntry struct {
	Slug    string `yaml:"slug"`
	Stage   string `yaml:"stage"`
	Level   string `yaml:"level"`
	What    string `yaml:"what"`
	Fix     string `yaml:"fix"`
	Removed string `yaml:"removed"`
}

// engineSlugs are the checks the engine runs for every profile. Each one needs an entry in
// catalog.yaml. The lint rules come from lint.Rules; the rest are the review stages' own.
func engineSlugs() []string {
	var out []string
	for _, r := range lint.Rules {
		out = append(out, r.Slug)
	}
	return append(out, review.FrontmatterReadableSlug, review.HasChildrenSlug, review.ContradictionSlug,
		review.RestatementSlug, review.DivergenceAmbiguous, review.DivergenceGap,
		review.GroundingContradicted, review.GroundingUnverified)
}

// stageOrder is the order the review pipeline runs its stages in, and the catalog's order.
var stageOrder = []string{"lint", "rubric", "grounding", "divergence", "coherence"}

var stageTitle = map[string]string{
	"lint":       "Lint",
	"rubric":     "Rubric",
	"grounding":  "Grounding",
	"divergence": "Divergence",
	"coherence":  "Coherence",
}

var stageIntro = map[string]string{
	"lint":       "Lint checks run without a model, on every save. They check the writing and the structure.",
	"rubric":     "Rubric checks ask a model one question about the doc. The profile writes the question and the condition that passes it.",
	"grounding":  "Grounding checks compare the doc's factual claims with the sources that the profile's source policy accepts.",
	"divergence": "Divergence checks give the doc to independent readers, who answer the build questions from the doc only.",
	"coherence":  "Coherence checks read the doc together with the docs it links to.",
}

// catalogCheck is one entry of the Check catalog.
type catalogCheck struct {
	slug, stage, level, what, passWhen, fix, removed string
	profiles                                         []string
	sizes                                            []string
}

func loadCatalog() ([]catalogCheck, error) {
	src, err := os.ReadFile(catalogSource)
	if err != nil {
		return nil, err
	}
	var file struct {
		Checks []catalogEntry `yaml:"checks"`
	}
	dec := yaml.NewDecoder(bytes.NewReader(src))
	dec.KnownFields(true)
	if err := dec.Decode(&file); err != nil {
		return nil, fmt.Errorf("%s: %w", catalogSource, err)
	}
	levels := map[string]string{}
	for _, r := range lint.Rules {
		levels[r.Slug] = string(r.Level)
	}
	byslug := map[string]*catalogCheck{}
	var out []*catalogCheck
	engine := map[string]bool{}
	for _, s := range engineSlugs() {
		engine[s] = true
	}
	for _, e := range file.Checks {
		if byslug[e.Slug] != nil {
			return nil, fmt.Errorf("%s: %s has two entries", catalogSource, e.Slug)
		}
		if e.Removed == "" && !engine[e.Slug] {
			return nil, fmt.Errorf("%s: %s is not a check the engine runs. A profile check takes its text from the profile; a removed check needs removed: vX.Y", catalogSource, e.Slug)
		}
		level := e.Level
		if l, ok := levels[e.Slug]; ok {
			level = l
		}
		c := &catalogCheck{slug: e.Slug, stage: e.Stage, level: level, what: e.What, fix: e.Fix, removed: e.Removed}
		byslug[e.Slug] = c
		out = append(out, c)
	}
	for s := range engine {
		if byslug[s] == nil {
			return nil, fmt.Errorf("%s: the engine runs %s, and the catalog has no entry for it", catalogSource, s)
		}
	}
	builtins, err := profile.Builtins()
	if err != nil {
		return nil, err
	}
	sort.Slice(builtins, func(i, j int) bool { return builtins[i].Profile.Key < builtins[j].Profile.Key })
	for _, b := range builtins {
		name := strings.ToUpper(b.Profile.Key)
		for _, ch := range b.Profile.Checks {
			if engine[ch.Slug] {
				return nil, fmt.Errorf("the %s profile names %s, which the engine also runs; the catalog cannot say which text is right", b.Profile.Key, ch.Slug)
			}
			c := byslug[ch.Slug]
			if c == nil {
				c = &catalogCheck{slug: ch.Slug, stage: ch.Stage, level: ch.Level, what: ch.Question, passWhen: ch.PassWhen, sizes: ch.Sizes}
				byslug[ch.Slug] = c
				out = append(out, c)
			} else if c.removed != "" {
				return nil, fmt.Errorf("%s: %s is marked removed, and the %s profile still has it", catalogSource, ch.Slug, b.Profile.Key)
			}
			c.profiles = append(c.profiles, name)
		}
	}
	for _, c := range out {
		if len(c.profiles) == 0 && c.removed == "" {
			c.profiles = []string{"every profile"}
		}
	}
	sort.SliceStable(out, func(i, j int) bool {
		si, sj := slices.Index(stageOrder, out[i].stage), slices.Index(stageOrder, out[j].stage)
		if si != sj {
			return si < sj
		}
		return out[i].slug < out[j].slug
	})
	res := make([]catalogCheck, len(out))
	for i, c := range out {
		if slices.Index(stageOrder, c.stage) < 0 {
			return nil, fmt.Errorf("%s has the stage %q, which the pipeline does not have", c.slug, c.stage)
		}
		res[i] = *c
	}
	return res, nil
}

func checkCatalog() (string, error) {
	checks, err := loadCatalog()
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("---\ntitle: Check catalog\ndescription: Each check that the built-in PRD and SDD profiles run, what it checks, and what passes it.\n---\n\n")
	fmt.Fprintf(&b, generated+"\n\n", "internal/features/profile/catalog.yaml and the built-in profiles")
	b.WriteString("This page lists each check that Speccy runs with the built-in PRD and SDD profiles. A finding in Speccy links to the entry of its check.\n\n")
	b.WriteString("A check has a slug, a level and a stage. A MUST finding makes the verdict Not Build Ready. A SHOULD finding counts in the score. An INFO finding is a hint. A profile can change the level of a check. [The review pipeline](/concepts/review-pipeline/) explains the stages.\n\n")
	stage := ""
	for _, c := range checks {
		if c.stage != stage {
			stage = c.stage
			fmt.Fprintf(&b, "## %s\n\n%s\n\n", stageTitle[stage], stageIntro[stage])
		}
		// The slug is the anchor, because the app links to /reference/checks/#<slug>.
		fmt.Fprintf(&b, "<h3 id=\"%s\"><code>%s</code></h3>\n\n", c.slug, c.slug)
		if c.removed != "" {
			fmt.Fprintf(&b, "Removed in %s. Speccy no longer runs this check.\n\n", c.removed)
			if c.what != "" {
				fmt.Fprintf(&b, "%s\n\n", c.what)
			}
			continue
		}
		level := c.level
		if level == "question" {
			level = "the level of its build question"
		}
		fmt.Fprintf(&b, "- Level: %s\n- Profiles: %s\n", level, strings.Join(c.profiles, ", "))
		if len(c.sizes) > 0 {
			fmt.Fprintf(&b, "- Sizes: %s\n", strings.Join(c.sizes, ", "))
		}
		b.WriteString("\n")
		if c.passWhen != "" {
			fmt.Fprintf(&b, "The check asks: %s\n\nIt passes when: %s\n\n", c.what, c.passWhen)
		} else {
			fmt.Fprintf(&b, "%s\n\n", c.what)
		}
		if c.fix != "" {
			fmt.Fprintf(&b, "To fix a finding: %s\n\n", c.fix)
		}
	}
	return strings.TrimRight(b.String(), "\n") + "\n", nil
}

// catalogSlugsTS is the list of slugs the app links to the Check catalog for.
func catalogSlugsTS() (string, error) {
	checks, err := loadCatalog()
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("// Generated by `go run ./tools/buildtool docs-ref` from the Check catalog. Do not edit this file.\n")
	b.WriteString("// A finding of one of these checks links to its entry on the docs site.\n")
	b.WriteString("export const catalogSlugs: ReadonlySet<string> = new Set([\n")
	for _, c := range checks {
		fmt.Fprintf(&b, "  %q,\n", c.slug)
	}
	b.WriteString("]);\n")
	return b.String(), nil
}

// profileSchemaPage writes the profile schema as tables, one for each object, in the order
// the schema lists the keys.
func profileSchemaPage() (string, error) {
	src, err := os.ReadFile("schemas/profile.schema.json")
	if err != nil {
		return "", err
	}
	var doc yaml.Node
	if err := yaml.Unmarshal(src, &doc); err != nil {
		return "", err
	}
	root := doc.Content[0]
	defs := get(root, "$defs")
	var b strings.Builder
	b.WriteString("---\ntitle: Profile schema\ndescription: Each key of a profile file, its type, and what it means.\n---\n\n")
	fmt.Fprintf(&b, generated+"\n\n", "schemas/profile.schema.json")
	b.WriteString("This page lists each key that a profile file can hold. Speccy checks a profile against this schema when it loads the file, and `speccy profile validate <file>` checks one file. An unknown key is an error.\n\n")
	b.WriteString("[Change a profile or a check](/how-to/change-a-profile/) shows the common changes.\n\n")
	writeObject(&b, "The profile", "", root, defs)
	return strings.TrimRight(b.String(), "\n") + "\n", nil
}

// get returns the value of key in the mapping node n, or nil.
func get(n *yaml.Node, key string) *yaml.Node {
	if n == nil || n.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i+1 < len(n.Content); i += 2 {
		if n.Content[i].Value == key {
			return n.Content[i+1]
		}
	}
	return nil
}

func str(n *yaml.Node, key string) string {
	if v := get(n, key); v != nil && v.Kind == yaml.ScalarNode {
		return v.Value
	}
	return ""
}

func writeObject(b *strings.Builder, title, path string, obj, defs *yaml.Node) {
	props := get(obj, "properties")
	if props == nil || len(props.Content) == 0 {
		return
	}
	required := map[string]bool{}
	if r := get(obj, "required"); r != nil {
		for _, k := range r.Content {
			required[k.Value] = true
		}
	}
	fmt.Fprintf(b, "## %s\n\n", title)
	if d := str(obj, "description"); d != "" && path != "" {
		fmt.Fprintf(b, "%s\n\n", d)
	}
	b.WriteString("| Key | Type | Required | Meaning |\n|---|---|---|---|\n")
	type child struct {
		key  string
		node *yaml.Node
		list bool
	}
	var nested []child
	for i := 0; i+1 < len(props.Content); i += 2 {
		k := props.Content[i].Value
		p := resolve(props.Content[i+1], defs)
		req := ""
		if required[k] {
			req = "yes"
		}
		fmt.Fprintf(b, "| `%s` | %s | %s | %s |\n", k, typeOf(p, defs), req, strings.ReplaceAll(str(p, "description"), "|", "\\|"))
		if get(p, "properties") != nil {
			nested = append(nested, child{k, p, false})
		} else if items := resolve(get(p, "items"), defs); get(items, "properties") != nil {
			nested = append(nested, child{k, items, true})
		}
	}
	b.WriteString("\n")
	for _, c := range nested {
		name := joinPath(path, c.key)
		if c.list {
			writeObject(b, "Each item of `"+name+"`", name+"[]", c.node, defs)
			continue
		}
		writeObject(b, "`"+name+"`", name, c.node, defs)
	}
}

func joinPath(path, k string) string {
	if path == "" {
		return k
	}
	return path + "." + k
}

// resolve follows a $ref into $defs. The node's own keys, such as a description, stay.
func resolve(p, defs *yaml.Node) *yaml.Node {
	ref := str(p, "$ref")
	if ref == "" {
		return p
	}
	d := get(defs, strings.TrimPrefix(ref, "#/$defs/"))
	if d == nil {
		return p
	}
	// The node's own keys come first, so get finds its description before the definition's.
	merged := &yaml.Node{Kind: yaml.MappingNode}
	for i := 0; i+1 < len(p.Content); i += 2 {
		if p.Content[i].Value == "$ref" {
			continue
		}
		merged.Content = append(merged.Content, p.Content[i], p.Content[i+1])
	}
	merged.Content = append(merged.Content, d.Content...)
	return merged
}

func typeOf(p, defs *yaml.Node) string {
	p = resolve(p, defs)
	if e := get(p, "enum"); e != nil {
		var vs []string
		for _, v := range e.Content {
			vs = append(vs, "`"+v.Value+"`")
		}
		return "one of " + strings.Join(vs, ", ")
	}
	if c := get(p, "const"); c != nil {
		return "`" + c.Value + "`"
	}
	t := get(p, "type")
	switch {
	case t != nil && t.Kind == yaml.ScalarNode:
		switch t.Value {
		case "array":
			if items := get(p, "items"); items != nil {
				return "list of " + typeOf(items, defs)
			}
		case "object":
			if ap := get(p, "additionalProperties"); ap != nil && ap.Kind == yaml.MappingNode {
				return "map of " + typeOf(ap, defs)
			}
		case "string":
			if pat := str(p, "pattern"); pat != "" {
				return "string matching `" + strings.ReplaceAll(pat, "|", "\\|") + "`"
			}
		}
		return t.Value
	case t != nil && t.Kind == yaml.SequenceNode:
		var vs []string
		for _, v := range t.Content {
			vs = append(vs, v.Value)
		}
		return strings.Join(vs, " or ")
	}
	for _, alt := range []string{"oneOf", "anyOf"} {
		if one := get(p, alt); one != nil {
			var vs []string
			for _, v := range one.Content {
				vs = append(vs, typeOf(v, defs))
			}
			return strings.Join(vs, " or ")
		}
	}
	return "any"
}

// actionRefPage writes the inputs of action.yml.
func actionRefPage() (string, error) {
	src, err := os.ReadFile("action.yml")
	if err != nil {
		return "", err
	}
	var doc yaml.Node
	if err := yaml.Unmarshal(src, &doc); err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("---\ntitle: GitHub Action\ndescription: Each input of the Speccy GitHub Action.\n---\n\n")
	fmt.Fprintf(&b, generated+"\n\n", "action.yml")
	b.WriteString("This page lists each input of the Speccy GitHub Action, `alternayte/speccy`. [Keep the verdict in CI](/how-to/keep-the-verdict-in-ci/) shows a whole workflow, and [Reply commands](/reference/reply-commands/) lists the replies that record a decision.\n\n")
	b.WriteString("| Input | Default | What it does |\n|---|---|---|\n")
	root := doc.Content[0]
	for i := 0; i+1 < len(root.Content); i += 2 {
		if root.Content[i].Value != "inputs" {
			continue
		}
		inputs := root.Content[i+1]
		for j := 0; j+1 < len(inputs.Content); j += 2 {
			name := inputs.Content[j].Value
			var in struct {
				Description string `yaml:"description"`
				Default     string `yaml:"default"`
			}
			if err := inputs.Content[j+1].Decode(&in); err != nil {
				return "", err
			}
			def := "empty"
			if in.Default != "" {
				def = "`" + in.Default + "`"
			}
			desc := strings.Join(strings.Fields(in.Description), " ")
			desc = strings.ReplaceAll(desc, "<model>", "&lt;model&gt;")
			fmt.Fprintf(&b, "| `%s` | %s | %s |\n", name, def, strings.ReplaceAll(desc, "|", "\\|"))
		}
	}
	return b.String(), nil
}

// mcpToolsPage lists the tools of the MCP server, with the input of each, from the server.
func mcpToolsPage() (string, error) {
	ctx := context.Background()
	server := mcpserver.New(nil)
	ct, st := mcp.NewInMemoryTransports()
	if _, err := server.Connect(ctx, st, nil); err != nil {
		return "", err
	}
	cs, err := mcp.NewClient(&mcp.Implementation{Name: "docs-ref"}, nil).Connect(ctx, ct, nil)
	if err != nil {
		return "", err
	}
	defer func() { _ = cs.Close() }()
	res, err := cs.ListTools(ctx, nil)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("---\ntitle: MCP tools\ndescription: Each tool of the Speccy MCP server, and its input.\n---\n\n")
	fmt.Fprintf(&b, generated+"\n\n", "internal/mcpserver")
	b.WriteString("This page lists each tool of Speccy's MCP server. `speccy mcp` runs the server over stdio as the local user. In hosted mode the same tools are at `/mcp`, with a personal API token. [Hand a spec to a coding agent](/how-to/hand-a-spec-to-a-coding-agent/) shows the setup.\n\n")
	for _, t := range res.Tools {
		fmt.Fprintf(&b, "## `%s`\n\n%s\n\n", t.Name, t.Description)
		js, _ := json.Marshal(t.InputSchema)
		var doc yaml.Node
		if err := yaml.Unmarshal(js, &doc); err != nil {
			return "", err
		}
		schema := doc.Content[0]
		props := get(schema, "properties")
		if props == nil || len(props.Content) == 0 {
			b.WriteString("It takes no input.\n\n")
			continue
		}
		required := map[string]bool{}
		if r := get(schema, "required"); r != nil {
			for _, k := range r.Content {
				required[k.Value] = true
			}
		}
		b.WriteString("| Input | Type | Required | Meaning |\n|---|---|---|---|\n")
		for i := 0; i+1 < len(props.Content); i += 2 {
			k, p := props.Content[i].Value, props.Content[i+1]
			req := ""
			if required[k] {
				req = "yes"
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", k, typeOf(p, nil), req, strings.ReplaceAll(str(p, "description"), "|", "\\|"))
		}
		b.WriteString("\n")
	}
	return strings.TrimRight(b.String(), "\n") + "\n", nil
}

// cliUsage is the text of `speccy help`.
func cliUsage() (string, error) {
	out, err := exec.Command("go", "run", "./cmd/speccy", "help").Output()
	if err != nil {
		return "", fmt.Errorf("speccy help: %w", err)
	}
	return string(out), nil
}

// usageCmdRe finds a command line of the usage text: "  speccy <word>".
var usageCmdRe = regexp.MustCompile(`^  speccy( ([a-z][a-z-]*))?`)

// commandsOf returns the first word of each command in the usage text.
func commandsOf(usage string) map[string]bool {
	out := map[string]bool{}
	for _, line := range strings.Split(usage, "\n") {
		if m := usageCmdRe.FindStringSubmatch(line); m != nil && m[2] != "" {
			out[m[2]] = true
		}
	}
	return out
}

func cliRefPage(usage string) string {
	var b strings.Builder
	b.WriteString("---\ntitle: CLI\ndescription: Each command of the speccy binary, its flags, and its exit codes.\n---\n\n")
	fmt.Fprintf(&b, generated+"\n\n", "the output of `speccy help`")
	b.WriteString("This page lists each command of the `speccy` binary, as `speccy help` prints it. [The TUI](/reference/tui/) lists the keys of the terminal UI.\n\n")
	b.WriteString("```text\n" + strings.TrimRight(usage, "\n") + "\n```\n")
	return b.String()
}

// sharedWords lists the single avoid words that also name another thing in Speccy, so
// the DomainWords rule does not flag them. For example, a profile has a template, a finding
// has an anchor, and a verdict becomes stale. Phrases of two or more words are always flagged.
var sharedWords = map[string]bool{
	"activity": true, "anchor": true, "accuracy": true, "blocker": true, "broken": true, "candidate": true,
	"category": true, "clone": true, "copy": true, "divergence": true, "diverged": true, "duplicate": true,
	"evidence": true, "excluded": true, "expired": true, "feedback": true, "group": true, "guess": true,
	"gutter": true, "handle": true, "header": true, "integration": true, "job": true, "mapping": true,
	"marker": true, "override": true, "partial": true, "precision": true, "queue": true, "reference": true,
	"scale": true, "skip": true, "skipped": true, "snippet": true, "stale": true, "suggestion": true,
	"symbol": true, "tag": true, "template": true, "timeline": true, "todo": true, "unknown": true,
	"unreachable": true, "locator": true,
}

var domainLineRe = regexp.MustCompile(`^- ([^:]+): .*Avoid(?: anywhere)?: (.+)\.$`)

// domainWordsRule writes a Vale substitution rule from the Domain words of AGENTS.md.
func domainWordsRule() (string, error) {
	f, err := os.Open("AGENTS.md")
	if err != nil {
		return "", err
	}
	defer func() { _ = f.Close() }()
	swap := map[string][]string{}
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		m := domainLineRe.FindStringSubmatch(sc.Text())
		if m == nil {
			continue
		}
		for _, w := range strings.Split(m[2], ",") {
			w = strings.TrimSpace(w)
			if w == "" || !strings.Contains(w, " ") && sharedWords[strings.ToLower(w)] {
				continue
			}
			if !slices.Contains(swap[w], m[1]) {
				swap[w] = append(swap[w], m[1])
			}
		}
	}
	if err := sc.Err(); err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("# Generated by `go run ./tools/buildtool docs-ref` from the Domain words of AGENTS.md. Do not edit this file.\n")
	b.WriteString("extends: substitution\nmessage: \"Use the domain word '%s', not '%s'.\"\nlevel: error\nignorecase: true\nswap:\n")
	for _, w := range slices.Sorted(func(yield func(string) bool) {
		for k := range swap {
			if !yield(k) {
				return
			}
		}
	}) {
		fmt.Fprintf(&b, "  %s: %s\n", quote(regexp.QuoteMeta(w)), quote(strings.Join(swap[w], " or ")))
	}
	return b.String(), nil
}

// quote writes s as a YAML double-quoted string.
func quote(s string) string {
	out, _ := json.Marshal(s)
	return string(out)
}

// fenceRe finds a fenced code block: its info string and its body.
var fenceRe = regexp.MustCompile("(?ms)^```([^\\n]*)\\n(.*?)^```\\s*$")

// sampleLoaders parse a YAML sample of each kind with the loader the server uses. A kind
// with a nil loader only needs to be YAML.
var sampleLoaders = map[string]func([]byte) error{
	"frontmatter": func(src []byte) error {
		var fm source.Frontmatter
		dec := yaml.NewDecoder(bytes.NewReader(src))
		dec.KnownFields(true)
		if err := dec.Decode(&fm); err != nil {
			return err
		}
		if problem, _ := source.FrontmatterProblem([]byte("---\n" + string(src) + "---\n")); problem != "" {
			return errors.New(problem)
		}
		return nil
	},
	"speccy-config": func(src []byte) error { _, err := source.ParseRepoConfig(src); return err },
	"sidecar":       func(src []byte) error { _, err := source.ParseDecisions(src); return err },
	"profile": func(src []byte) error {
		_, err := profile.Parse("sample", src, func(string) ([]byte, error) { return []byte("# Template\n"), nil })
		return err
	},
	"workflow": nil,
	"k8s":      nil,
	"compose":  nil,
}

var shellLangs = map[string]bool{"sh": true, "bash": true, "shell": true, "console": true}

var speccyCmdRe = regexp.MustCompile(`(?m)^\s*(?:\$\s*)?speccy(?:\s+(--?[a-z-]+|[a-z][a-z-]*))?`)

// checkSamples parses each YAML sample of the site with its loader, and checks each speccy
// command of a shell sample against the CLI.
func checkSamples(commands map[string]bool) ([]string, error) {
	var problems []string
	err := filepath.WalkDir(docsDir, func(p string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() || !strings.HasSuffix(p, ".md") && !strings.HasSuffix(p, ".mdx") {
			return err
		}
		src, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		for _, m := range fenceRe.FindAllSubmatchIndex(src, -1) {
			info := strings.Fields(string(src[m[2]:m[3]]))
			body := src[m[4]:m[5]]
			line := bytes.Count(src[:m[0]], []byte("\n")) + 1
			if len(info) == 0 {
				continue
			}
			lang := info[0]
			switch {
			case lang == "yaml" || lang == "yml":
				if len(info) < 2 {
					problems = append(problems, fmt.Sprintf("%s:%d: a YAML sample needs its kind, such as ```yaml frontmatter. Kinds: %s", p, line, kinds()))
					continue
				}
				load, ok := sampleLoaders[info[1]]
				if !ok {
					problems = append(problems, fmt.Sprintf("%s:%d: %q is not a sample kind. Kinds: %s", p, line, info[1], kinds()))
					continue
				}
				var parsed yaml.Node
				if err := yaml.Unmarshal(body, &parsed); err != nil {
					problems = append(problems, fmt.Sprintf("%s:%d: the YAML does not parse: %v", p, line, err))
					continue
				}
				if load != nil {
					if err := load(body); err != nil {
						problems = append(problems, fmt.Sprintf("%s:%d: the %s sample does not load: %v", p, line, info[1], err))
					}
				}
			case shellLangs[lang]:
				for _, c := range speccyCmdRe.FindAllSubmatch(body, -1) {
					word := string(c[1])
					if word == "" || strings.HasPrefix(word, "-") {
						continue
					}
					if !commands[word] {
						problems = append(problems, fmt.Sprintf("%s:%d: `speccy %s` is not a command. `speccy help` lists the commands.", p, line, word))
					}
				}
			}
		}
		return nil
	})
	return problems, err
}

func kinds() string {
	var ks []string
	for k := range sampleLoaders {
		ks = append(ks, k)
	}
	sort.Strings(ks)
	return strings.Join(ks, ", ")
}

var envRe = regexp.MustCompile(`SPECCY_[A-Z][A-Z0-9_]*[A-Z0-9]`)

// checkConfigVars fails when a SPECCY_ variable that the code reads is missing from the
// Configuration page.
func checkConfigVars() ([]string, error) {
	page, err := os.ReadFile(configPage)
	if err != nil {
		return nil, fmt.Errorf("the Configuration page: %w", err)
	}
	seen := map[string]bool{}
	for _, root := range []string{"cmd", "internal"} {
		err := filepath.WalkDir(root, func(p string, d fs.DirEntry, err error) error {
			if err != nil || d.IsDir() || !strings.HasSuffix(p, ".go") || strings.HasSuffix(p, "_test.go") {
				return err
			}
			src, err := os.ReadFile(p)
			if err != nil {
				return err
			}
			for _, v := range envRe.FindAll(src, -1) {
				seen[string(v)] = true
			}
			return nil
		})
		if err != nil {
			return nil, err
		}
	}
	var problems []string
	for _, v := range slices.Sorted(func(yield func(string) bool) {
		for k := range seen {
			if !yield(k) {
				return
			}
		}
	}) {
		if !bytes.Contains(page, []byte(v)) {
			problems = append(problems, fmt.Sprintf("%s does not name %s, which the code reads.", configPage, v))
		}
	}
	return problems, nil
}
