package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"strings"
)

const (
	pgQuerierPath  = "db/postgres/querier.go"
	sqliteAdapter  = "db/sqlite/adapter.gen.go"
	pgImportPath   = "github.com/alternayte/speccy/db/postgres"
	sqliteTypePkg  = "sqlitedb" // the package the adapter is written into
	postgresPkg    = "pgdb"
	adapterComment = "// Code generated by tools/buildtool sqladapter. DO NOT EDIT.\n\n"
)

// cmdSQLAdapter writes db/sqlite/adapter.gen.go: a pgdb.Querier on the SQLite queries.
// sqlc generates the same type shapes for both engines (see sqlc.yaml), so each method is a
// struct conversion. When the shapes drift, the adapter does not compile.
func cmdSQLAdapter() error {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, pgQuerierPath, nil, 0)
	if err != nil {
		return fmt.Errorf("sqladapter: %w", err)
	}
	var iface *ast.InterfaceType
	ast.Inspect(f, func(n ast.Node) bool {
		if ts, ok := n.(*ast.TypeSpec); ok && ts.Name.Name == "Querier" {
			iface, _ = ts.Type.(*ast.InterfaceType)
		}
		return iface == nil
	})
	if iface == nil {
		return fmt.Errorf("sqladapter: %s has no Querier interface", pgQuerierPath)
	}

	var b bytes.Buffer
	b.WriteString(adapterComment)
	b.WriteString("package " + sqliteTypePkg + "\n\nimport (\n")
	for _, imp := range f.Imports {
		b.WriteString("\t" + imp.Path.Value + "\n")
	}
	fmt.Fprintf(&b, "\n\t%s %q\n)\n\n", postgresPkg, pgImportPath)
	b.WriteString("// Adapter runs the SQLite queries behind the pgdb.Querier interface.\n")
	b.WriteString("type Adapter struct{ q *Queries }\n\n")
	b.WriteString("// NewAdapter returns an Adapter on db.\n")
	b.WriteString("func NewAdapter(db DBTX) Adapter { return Adapter{q: New(db)} }\n\n")
	fmt.Fprintf(&b, "var _ %s.Querier = Adapter{}\n", postgresPkg)

	for _, m := range iface.Methods.List {
		fn, ok := m.Type.(*ast.FuncType)
		if !ok || len(m.Names) != 1 {
			return fmt.Errorf("sqladapter: unexpected member in Querier")
		}
		name := m.Names[0].Name
		var params, args []string
		for _, p := range fn.Params.List {
			for _, n := range p.Names {
				typ := typeString(p.Type)
				params = append(params, n.Name+" "+qualify(typ))
				if isLocal(typ) {
					args = append(args, typ+"("+n.Name+")")
				} else {
					args = append(args, n.Name)
				}
			}
		}
		var results []string
		for _, r := range fn.Results.List {
			results = append(results, typeString(r.Type))
		}
		call := "a.q." + name + "(" + strings.Join(args, ", ") + ")"
		qualified := make([]string, len(results))
		for i, r := range results {
			qualified[i] = qualify(r)
		}
		fmt.Fprintf(&b, "\nfunc (a Adapter) %s(%s) (%s) {\n", name, strings.Join(params, ", "), strings.Join(qualified, ", "))
		switch {
		case len(results) == 1:
			fmt.Fprintf(&b, "\treturn %s\n", call)
		case len(results) == 2 && strings.HasPrefix(results[0], "[]") && isLocal(strings.TrimPrefix(results[0], "[]")):
			elem := strings.TrimPrefix(results[0], "[]")
			fmt.Fprintf(&b, "\trows, err := %s\n\tif err != nil {\n\t\treturn nil, err\n\t}\n", call)
			fmt.Fprintf(&b, "\tout := make([]%s.%s, len(rows))\n\tfor i, r := range rows {\n\t\tout[i] = %s.%s(r)\n\t}\n\treturn out, nil\n", postgresPkg, elem, postgresPkg, elem)
		case len(results) == 2 && isLocal(results[0]):
			fmt.Fprintf(&b, "\tr, err := %s\n\treturn %s.%s(r), err\n", call, postgresPkg, results[0])
		case len(results) == 2:
			fmt.Fprintf(&b, "\treturn %s\n", call)
		default:
			return fmt.Errorf("sqladapter: %s has %d results", name, len(results))
		}
		b.WriteString("}\n")
	}

	src, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("sqladapter: format: %w\n%s", err, b.String())
	}
	return os.WriteFile(sqliteAdapter, src, 0o644)
}

func typeString(e ast.Expr) string {
	switch t := e.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return typeString(t.X) + "." + t.Sel.Name
	case *ast.ArrayType:
		return "[]" + typeString(t.Elt)
	case *ast.StarExpr:
		return "*" + typeString(t.X)
	}
	panic(fmt.Sprintf("sqladapter: unsupported type %T", e))
}

// isLocal reports whether typ is a type that sqlc declares in the generated package.
func isLocal(typ string) bool {
	return !strings.Contains(typ, ".") && !strings.HasPrefix(typ, "[]") && typ != "" &&
		typ[0] >= 'A' && typ[0] <= 'Z'
}

// qualify adds the pgdb package name to local types, so the signature matches pgdb.Querier.
func qualify(typ string) string {
	if strings.HasPrefix(typ, "[]") {
		return "[]" + qualify(strings.TrimPrefix(typ, "[]"))
	}
	if isLocal(typ) {
		return postgresPkg + "." + typ
	}
	return typ
}
