root = "."
tmp_dir = "build/air"

[build]
  cmd = "go build -o build/air/speccy ./cmd/speccy"
  full_bin = "build/air/speccy serve"
  include_ext = ["go", "yaml"]
  exclude_dir = ["web", "build", "bin", "docs", "node_modules", "testdata"]
  delay = 300

[log]
  time = false
