// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collab.sql

package sqlitedb

import (
	"context"
	"database/sql"
	"time"

	"github.com/alternayte/speccy/db/dbtype"
	"github.com/google/uuid"
)

const countAuthorMessagesSince = `-- name: CountAuthorMessagesSince :one
SELECT COUNT(*) FROM thread_message_view WHERE author_id = ?1 AND created_at > ?2
`

type CountAuthorMessagesSinceParams struct {
	AuthorID string
	Since    time.Time
}

// REQ-086: a guest's posts in the last hour.
func (q *Queries) CountAuthorMessagesSince(ctx context.Context, arg CountAuthorMessagesSinceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuthorMessagesSince, arg.AuthorID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFindingsByCheck = `-- name: CountFindingsByCheck :many
SELECT f.check_slug, COUNT(*) AS n
FROM finding f
WHERE f.run_id IN (
    SELECT (SELECT r2.id FROM review_run r2 WHERE r2.bundle_id = b.id AND r2.status = 'complete'
            ORDER BY r2.started_at DESC LIMIT 1)
    FROM bundle b WHERE b.workspace_id = ?1 AND b.archived_at IS NULL AND b.profile_key = ?2
)
GROUP BY f.check_slug ORDER BY n DESC LIMIT 10
`

type CountFindingsByCheckParams struct {
	WorkspaceID uuid.UUID
	ProfileKey  string
}

type CountFindingsByCheckRow struct {
	CheckSlug string
	N         int64
}

// For insights: failing checks in the latest completed run of each bundle.
func (q *Queries) CountFindingsByCheck(ctx context.Context, arg CountFindingsByCheckParams) ([]CountFindingsByCheckRow, error) {
	rows, err := q.db.QueryContext(ctx, countFindingsByCheck, arg.WorkspaceID, arg.ProfileKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountFindingsByCheckRow
	for rows.Next() {
		var i CountFindingsByCheckRow
		if err := rows.Scan(&i.CheckSlug, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOpenBlockingThreads = `-- name: CountOpenBlockingThreads :one
SELECT COUNT(*) FROM thread_view WHERE bundle_id = ?1 AND blocking AND status = 'open'
`

func (q *Queries) CountOpenBlockingThreads(ctx context.Context, bundleID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenBlockingThreads, bundleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteProfileMaintainers = `-- name: DeleteProfileMaintainers :exec
DELETE FROM profile_maintainer WHERE profile_id = ?1
`

func (q *Queries) DeleteProfileMaintainers(ctx context.Context, profileID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProfileMaintainers, profileID)
	return err
}

const getBundleStatusView = `-- name: GetBundleStatusView :one
SELECT bundle_id, status, approvals, approved_version, review_requested_at, approved_at, updated_at FROM bundle_status_view WHERE bundle_id = ?1
`

func (q *Queries) GetBundleStatusView(ctx context.Context, bundleID uuid.UUID) (BundleStatusView, error) {
	row := q.db.QueryRowContext(ctx, getBundleStatusView, bundleID)
	var i BundleStatusView
	err := row.Scan(
		&i.BundleID,
		&i.Status,
		&i.Approvals,
		&i.ApprovedVersion,
		&i.ReviewRequestedAt,
		&i.ApprovedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFinding = `-- name: GetFinding :one
SELECT id, run_id, check_slug, level, stage, relaxed, anchor, message, evidence, suggestion, waived FROM finding WHERE id = ?1
`

func (q *Queries) GetFinding(ctx context.Context, id uuid.UUID) (Finding, error) {
	row := q.db.QueryRowContext(ctx, getFinding, id)
	var i Finding
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.CheckSlug,
		&i.Level,
		&i.Stage,
		&i.Relaxed,
		&i.Anchor,
		&i.Message,
		&i.Evidence,
		&i.Suggestion,
		&i.Waived,
	)
	return i, err
}

const getThreadView = `-- name: GetThreadView :one
SELECT id, workspace_id, bundle_id, profile_key, anchor_kind, anchor, addressed_to, title, blocking, status, created_by, created_at, last_message_at, message_count, handoff_id, handoff_version FROM thread_view WHERE workspace_id = ?1 AND id = ?2
`

type GetThreadViewParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetThreadView(ctx context.Context, arg GetThreadViewParams) (ThreadView, error) {
	row := q.db.QueryRowContext(ctx, getThreadView, arg.WorkspaceID, arg.ID)
	var i ThreadView
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.BundleID,
		&i.ProfileKey,
		&i.AnchorKind,
		&i.Anchor,
		&i.AddressedTo,
		&i.Title,
		&i.Blocking,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastMessageAt,
		&i.MessageCount,
		&i.HandoffID,
		&i.HandoffVersion,
	)
	return i, err
}

const getUserState = `-- name: GetUserState :one
SELECT user_id, inbox_seen_at FROM user_state WHERE user_id = ?1
`

func (q *Queries) GetUserState(ctx context.Context, userID string) (UserState, error) {
	row := q.db.QueryRowContext(ctx, getUserState, userID)
	var i UserState
	err := row.Scan(&i.UserID, &i.InboxSeenAt)
	return i, err
}

const getWaiverView = `-- name: GetWaiverView :one
SELECT id, workspace_id, bundle_id, check_slug, level, section_path, section_hash, reason, status, requested_by, approvals, decided_by, created_at, updated_at, scope, trace_id, repo FROM waiver_view WHERE workspace_id = ?1 AND id = ?2
`

type GetWaiverViewParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetWaiverView(ctx context.Context, arg GetWaiverViewParams) (WaiverView, error) {
	row := q.db.QueryRowContext(ctx, getWaiverView, arg.WorkspaceID, arg.ID)
	var i WaiverView
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.BundleID,
		&i.CheckSlug,
		&i.Level,
		&i.SectionPath,
		&i.SectionHash,
		&i.Reason,
		&i.Status,
		&i.RequestedBy,
		&i.Approvals,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Scope,
		&i.TraceID,
		&i.Repo,
	)
	return i, err
}

const insertBundleReviewer = `-- name: InsertBundleReviewer :exec
INSERT INTO bundle_reviewer (bundle_id, user_id) VALUES (?1, ?2) ON CONFLICT DO NOTHING
`

type InsertBundleReviewerParams struct {
	BundleID uuid.UUID
	UserID   string
}

func (q *Queries) InsertBundleReviewer(ctx context.Context, arg InsertBundleReviewerParams) error {
	_, err := q.db.ExecContext(ctx, insertBundleReviewer, arg.BundleID, arg.UserID)
	return err
}

const insertProfileMaintainer = `-- name: InsertProfileMaintainer :exec
INSERT INTO profile_maintainer (profile_id, user_id) VALUES (?1, ?2) ON CONFLICT DO NOTHING
`

type InsertProfileMaintainerParams struct {
	ProfileID uuid.UUID
	UserID    string
}

func (q *Queries) InsertProfileMaintainer(ctx context.Context, arg InsertProfileMaintainerParams) error {
	_, err := q.db.ExecContext(ctx, insertProfileMaintainer, arg.ProfileID, arg.UserID)
	return err
}

const insertThreadMessage = `-- name: InsertThreadMessage :exec
INSERT INTO thread_message_view (id, thread_id, seq, author_kind, author_id, author_name, body, sources, decision, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6,
        ?7, ?8, ?9, ?10)
`

type InsertThreadMessageParams struct {
	ID         uuid.UUID
	ThreadID   uuid.UUID
	Seq        int64
	AuthorKind string
	AuthorID   string
	AuthorName string
	Body       string
	Sources    dbtype.JSON
	Decision   string
	CreatedAt  time.Time
}

func (q *Queries) InsertThreadMessage(ctx context.Context, arg InsertThreadMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertThreadMessage,
		arg.ID,
		arg.ThreadID,
		arg.Seq,
		arg.AuthorKind,
		arg.AuthorID,
		arg.AuthorName,
		arg.Body,
		arg.Sources,
		arg.Decision,
		arg.CreatedAt,
	)
	return err
}

const isAnyMaintainer = `-- name: IsAnyMaintainer :one
SELECT EXISTS (SELECT 1 FROM profile_maintainer pm JOIN profile p ON p.id = pm.profile_id
               WHERE p.workspace_id = ?1 AND pm.user_id = ?2) AS maintainer
`

type IsAnyMaintainerParams struct {
	WorkspaceID uuid.UUID
	UserID      string
}

func (q *Queries) IsAnyMaintainer(ctx context.Context, arg IsAnyMaintainerParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isAnyMaintainer, arg.WorkspaceID, arg.UserID)
	var maintainer bool
	err := row.Scan(&maintainer)
	return maintainer, err
}

const isProfileMaintainer = `-- name: IsProfileMaintainer :one
SELECT EXISTS (SELECT 1 FROM profile_maintainer pm JOIN profile p ON p.id = pm.profile_id
               WHERE p.workspace_id = ?1 AND p.key = ?2 AND pm.user_id = ?3) AS maintainer
`

type IsProfileMaintainerParams struct {
	WorkspaceID uuid.UUID
	Key         string
	UserID      string
}

func (q *Queries) IsProfileMaintainer(ctx context.Context, arg IsProfileMaintainerParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isProfileMaintainer, arg.WorkspaceID, arg.Key, arg.UserID)
	var maintainer bool
	err := row.Scan(&maintainer)
	return maintainer, err
}

const listAllRuns = `-- name: ListAllRuns :many
SELECT r.id, r.workspace_id, r.bundle_id, r.version_id, r.profile_key, r.profile_version, r.kind, r.status, r.stage, r.roles, r.prompt_versions, r.tokens_in, r.tokens_out, r.cost_estimate, r.cache_hits, r.error, r.started_at, r.finished_at, r.notes, r.stages, r.decisions_hash, v.result AS verdict_result
FROM review_run r LEFT JOIN verdict v ON v.run_id = r.id
WHERE r.workspace_id = ?1 AND r.status = 'complete'
ORDER BY r.started_at
`

type ListAllRunsRow struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	BundleID       uuid.UUID
	VersionID      uuid.UUID
	ProfileKey     string
	ProfileVersion int64
	Kind           string
	Status         string
	Stage          string
	Roles          dbtype.JSON
	PromptVersions dbtype.JSON
	TokensIn       int64
	TokensOut      int64
	CostEstimate   float64
	CacheHits      int64
	Error          string
	StartedAt      time.Time
	FinishedAt     sql.NullTime
	Notes          dbtype.JSON
	Stages         dbtype.JSON
	DecisionsHash  string
	VerdictResult  sql.NullString
}

// For insights: every finished run of the workspace, oldest first.
func (q *Queries) ListAllRuns(ctx context.Context, workspaceID uuid.UUID) ([]ListAllRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllRuns, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllRunsRow
	for rows.Next() {
		var i ListAllRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.BundleID,
			&i.VersionID,
			&i.ProfileKey,
			&i.ProfileVersion,
			&i.Kind,
			&i.Status,
			&i.Stage,
			&i.Roles,
			&i.PromptVersions,
			&i.TokensIn,
			&i.TokensOut,
			&i.CostEstimate,
			&i.CacheHits,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Notes,
			&i.Stages,
			&i.DecisionsHash,
			&i.VerdictResult,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorBundles = `-- name: ListAuthorBundles :many
SELECT bundle_id FROM bundle_author WHERE user_id = ?1
`

func (q *Queries) ListAuthorBundles(ctx context.Context, userID string) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listAuthorBundles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var bundle_id uuid.UUID
		if err := rows.Scan(&bundle_id); err != nil {
			return nil, err
		}
		items = append(items, bundle_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuildThreads = `-- name: ListBuildThreads :many
SELECT id, workspace_id, bundle_id, profile_key, anchor_kind, anchor, addressed_to, title, blocking, status, created_by, created_at, last_message_at, message_count, handoff_id, handoff_version FROM thread_view WHERE workspace_id = ?1 AND handoff_id IS NOT NULL
`

func (q *Queries) ListBuildThreads(ctx context.Context, workspaceID uuid.UUID) ([]ThreadView, error) {
	rows, err := q.db.QueryContext(ctx, listBuildThreads, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ThreadView
	for rows.Next() {
		var i ThreadView
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.BundleID,
			&i.ProfileKey,
			&i.AnchorKind,
			&i.Anchor,
			&i.AddressedTo,
			&i.Title,
			&i.Blocking,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastMessageAt,
			&i.MessageCount,
			&i.HandoffID,
			&i.HandoffVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBundleStatusViews = `-- name: ListBundleStatusViews :many
SELECT s.bundle_id, s.status, s.approvals, s.approved_version, s.review_requested_at, s.approved_at, s.updated_at FROM bundle_status_view s JOIN bundle b ON b.id = s.bundle_id WHERE b.workspace_id = ?1
`

func (q *Queries) ListBundleStatusViews(ctx context.Context, workspaceID uuid.UUID) ([]BundleStatusView, error) {
	rows, err := q.db.QueryContext(ctx, listBundleStatusViews, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BundleStatusView
	for rows.Next() {
		var i BundleStatusView
		if err := rows.Scan(
			&i.BundleID,
			&i.Status,
			&i.Approvals,
			&i.ApprovedVersion,
			&i.ReviewRequestedAt,
			&i.ApprovedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBundleThreads = `-- name: ListBundleThreads :many
SELECT id, workspace_id, bundle_id, profile_key, anchor_kind, anchor, addressed_to, title, blocking, status, created_by, created_at, last_message_at, message_count, handoff_id, handoff_version FROM thread_view WHERE bundle_id = ?1 ORDER BY status DESC, last_message_at DESC
`

func (q *Queries) ListBundleThreads(ctx context.Context, bundleID uuid.NullUUID) ([]ThreadView, error) {
	rows, err := q.db.QueryContext(ctx, listBundleThreads, bundleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ThreadView
	for rows.Next() {
		var i ThreadView
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.BundleID,
			&i.ProfileKey,
			&i.AnchorKind,
			&i.Anchor,
			&i.AddressedTo,
			&i.Title,
			&i.Blocking,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastMessageAt,
			&i.MessageCount,
			&i.HandoffID,
			&i.HandoffVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBundleWaivers = `-- name: ListBundleWaivers :many
SELECT id, workspace_id, bundle_id, check_slug, level, section_path, section_hash, reason, status, requested_by, approvals, decided_by, created_at, updated_at, scope, trace_id, repo FROM waiver_view WHERE bundle_id = ?1 ORDER BY created_at DESC
`

func (q *Queries) ListBundleWaivers(ctx context.Context, bundleID uuid.UUID) ([]WaiverView, error) {
	rows, err := q.db.QueryContext(ctx, listBundleWaivers, bundleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaiverView
	for rows.Next() {
		var i WaiverView
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.BundleID,
			&i.CheckSlug,
			&i.Level,
			&i.SectionPath,
			&i.SectionHash,
			&i.Reason,
			&i.Status,
			&i.RequestedBy,
			&i.Approvals,
			&i.DecidedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Scope,
			&i.TraceID,
			&i.Repo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFullRunsSince = `-- name: ListFullRunsSince :many
SELECT id, workspace_id, bundle_id, version_id, profile_key, profile_version, kind, status, stage, roles, prompt_versions, tokens_in, tokens_out, cost_estimate, cache_hits, error, started_at, finished_at, notes, stages, decisions_hash FROM review_run WHERE workspace_id = ?1 AND kind = 'full' AND status IN ('complete', 'failed')
  AND finished_at > ?2
ORDER BY finished_at DESC LIMIT 200
`

type ListFullRunsSinceParams struct {
	WorkspaceID uuid.UUID
	Since       sql.NullTime
}

func (q *Queries) ListFullRunsSince(ctx context.Context, arg ListFullRunsSinceParams) ([]ReviewRun, error) {
	rows, err := q.db.QueryContext(ctx, listFullRunsSince, arg.WorkspaceID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewRun
	for rows.Next() {
		var i ReviewRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.BundleID,
			&i.VersionID,
			&i.ProfileKey,
			&i.ProfileVersion,
			&i.Kind,
			&i.Status,
			&i.Stage,
			&i.Roles,
			&i.PromptVersions,
			&i.TokensIn,
			&i.TokensOut,
			&i.CostEstimate,
			&i.CacheHits,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Notes,
			&i.Stages,
			&i.DecisionsHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboxRead = `-- name: ListInboxRead :many
SELECT item_key FROM inbox_read WHERE user_id = ?1 AND read_at > ?2
`

type ListInboxReadParams struct {
	UserID string
	Since  time.Time
}

func (q *Queries) ListInboxRead(ctx context.Context, arg ListInboxReadParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listInboxRead, arg.UserID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var item_key string
		if err := rows.Scan(&item_key); err != nil {
			return nil, err
		}
		items = append(items, item_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesSince = `-- name: ListMessagesSince :many
SELECT m.id, m.thread_id, m.seq, m.author_kind, m.author_id, m.author_name, m.body, m.sources, m.decision, m.created_at, t.bundle_id, t.profile_key, t.title
FROM thread_message_view m JOIN thread_view t ON t.id = m.thread_id
WHERE t.workspace_id = ?1 AND m.created_at > ?2
ORDER BY m.created_at DESC LIMIT 500
`

type ListMessagesSinceParams struct {
	WorkspaceID uuid.UUID
	Since       time.Time
}

type ListMessagesSinceRow struct {
	ID         uuid.UUID
	ThreadID   uuid.UUID
	Seq        int64
	AuthorKind string
	AuthorID   string
	AuthorName string
	Body       string
	Sources    dbtype.JSON
	Decision   string
	CreatedAt  time.Time
	BundleID   uuid.NullUUID
	ProfileKey string
	Title      string
}

// Messages in threads of the workspace after a time, newest first, for the inbox.
func (q *Queries) ListMessagesSince(ctx context.Context, arg ListMessagesSinceParams) ([]ListMessagesSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesSince, arg.WorkspaceID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesSinceRow
	for rows.Next() {
		var i ListMessagesSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.Seq,
			&i.AuthorKind,
			&i.AuthorID,
			&i.AuthorName,
			&i.Body,
			&i.Sources,
			&i.Decision,
			&i.CreatedAt,
			&i.BundleID,
			&i.ProfileKey,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfileMaintainers = `-- name: ListProfileMaintainers :many
SELECT user_id FROM profile_maintainer WHERE profile_id = ?1 ORDER BY user_id
`

func (q *Queries) ListProfileMaintainers(ctx context.Context, profileID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listProfileMaintainers, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfileThreads = `-- name: ListProfileThreads :many
SELECT id, workspace_id, bundle_id, profile_key, anchor_kind, anchor, addressed_to, title, blocking, status, created_by, created_at, last_message_at, message_count, handoff_id, handoff_version FROM thread_view WHERE workspace_id = ?1 AND profile_key = ?2
ORDER BY status DESC, last_message_at DESC
`

type ListProfileThreadsParams struct {
	WorkspaceID uuid.UUID
	ProfileKey  string
}

func (q *Queries) ListProfileThreads(ctx context.Context, arg ListProfileThreadsParams) ([]ThreadView, error) {
	rows, err := q.db.QueryContext(ctx, listProfileThreads, arg.WorkspaceID, arg.ProfileKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ThreadView
	for rows.Next() {
		var i ThreadView
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.BundleID,
			&i.ProfileKey,
			&i.AnchorKind,
			&i.Anchor,
			&i.AddressedTo,
			&i.Title,
			&i.Blocking,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastMessageAt,
			&i.MessageCount,
			&i.HandoffID,
			&i.HandoffVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfileVersions = `-- name: ListProfileVersions :many
SELECT version, created_by, created_at, origin FROM profile_version WHERE profile_id = ?1 ORDER BY version DESC LIMIT 50
`

type ListProfileVersionsRow struct {
	Version   int64
	CreatedBy string
	CreatedAt time.Time
	Origin    string
}

func (q *Queries) ListProfileVersions(ctx context.Context, profileID uuid.UUID) ([]ListProfileVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProfileVersions, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProfileVersionsRow
	for rows.Next() {
		var i ListProfileVersionsRow
		if err := rows.Scan(
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewerBundles = `-- name: ListReviewerBundles :many
SELECT bundle_id FROM bundle_reviewer WHERE user_id = ?1
`

func (q *Queries) ListReviewerBundles(ctx context.Context, userID string) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listReviewerBundles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var bundle_id uuid.UUID
		if err := rows.Scan(&bundle_id); err != nil {
			return nil, err
		}
		items = append(items, bundle_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupersedesLinks = `-- name: ListSupersedesLinks :many
SELECT id, workspace_id, from_bundle_id, kind, target_kind, target_bundle_id, target_ref, origin, target_url FROM link WHERE workspace_id = ?1 AND kind = 'supersedes' AND target_bundle_id IS NOT NULL
`

func (q *Queries) ListSupersedesLinks(ctx context.Context, workspaceID uuid.UUID) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, listSupersedesLinks, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.FromBundleID,
			&i.Kind,
			&i.TargetKind,
			&i.TargetBundleID,
			&i.TargetRef,
			&i.Origin,
			&i.TargetUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadMessages = `-- name: ListThreadMessages :many
SELECT id, thread_id, seq, author_kind, author_id, author_name, body, sources, decision, created_at FROM thread_message_view WHERE thread_id = ?1 ORDER BY seq
`

func (q *Queries) ListThreadMessages(ctx context.Context, threadID uuid.UUID) ([]ThreadMessageView, error) {
	rows, err := q.db.QueryContext(ctx, listThreadMessages, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ThreadMessageView
	for rows.Next() {
		var i ThreadMessageView
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.Seq,
			&i.AuthorKind,
			&i.AuthorID,
			&i.AuthorName,
			&i.Body,
			&i.Sources,
			&i.Decision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerificationWaivers = `-- name: ListVerificationWaivers :many
SELECT id, workspace_id, bundle_id, check_slug, level, section_path, section_hash, reason, status, requested_by, approvals, decided_by, created_at, updated_at, scope, trace_id, repo FROM waiver_view
WHERE bundle_id = ?1 AND scope = 'verify' AND repo = ?2 AND status = 'approved'
`

type ListVerificationWaiversParams struct {
	BundleID uuid.UUID
	Repo     string
}

func (q *Queries) ListVerificationWaivers(ctx context.Context, arg ListVerificationWaiversParams) ([]WaiverView, error) {
	rows, err := q.db.QueryContext(ctx, listVerificationWaivers, arg.BundleID, arg.Repo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaiverView
	for rows.Next() {
		var i WaiverView
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.BundleID,
			&i.CheckSlug,
			&i.Level,
			&i.SectionPath,
			&i.SectionHash,
			&i.Reason,
			&i.Status,
			&i.RequestedBy,
			&i.Approvals,
			&i.DecidedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Scope,
			&i.TraceID,
			&i.Repo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceWaivers = `-- name: ListWorkspaceWaivers :many
SELECT id, workspace_id, bundle_id, check_slug, level, section_path, section_hash, reason, status, requested_by, approvals, decided_by, created_at, updated_at, scope, trace_id, repo FROM waiver_view WHERE workspace_id = ?1 ORDER BY created_at DESC
`

func (q *Queries) ListWorkspaceWaivers(ctx context.Context, workspaceID uuid.UUID) ([]WaiverView, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceWaivers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaiverView
	for rows.Next() {
		var i WaiverView
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.BundleID,
			&i.CheckSlug,
			&i.Level,
			&i.SectionPath,
			&i.SectionHash,
			&i.Reason,
			&i.Status,
			&i.RequestedBy,
			&i.Approvals,
			&i.DecidedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Scope,
			&i.TraceID,
			&i.Repo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInboxItemRead = `-- name: MarkInboxItemRead :exec
INSERT INTO inbox_read (user_id, item_key, read_at) VALUES (?1, ?2, ?3)
ON CONFLICT (user_id, item_key) DO NOTHING
`

type MarkInboxItemReadParams struct {
	UserID  string
	ItemKey string
	ReadAt  time.Time
}

func (q *Queries) MarkInboxItemRead(ctx context.Context, arg MarkInboxItemReadParams) error {
	_, err := q.db.ExecContext(ctx, markInboxItemRead, arg.UserID, arg.ItemKey, arg.ReadAt)
	return err
}

const setInboxSeen = `-- name: SetInboxSeen :exec
INSERT INTO user_state (user_id, inbox_seen_at) VALUES (?1, ?2)
ON CONFLICT (user_id) DO UPDATE SET inbox_seen_at = excluded.inbox_seen_at
`

type SetInboxSeenParams struct {
	UserID      string
	InboxSeenAt time.Time
}

func (q *Queries) SetInboxSeen(ctx context.Context, arg SetInboxSeenParams) error {
	_, err := q.db.ExecContext(ctx, setInboxSeen, arg.UserID, arg.InboxSeenAt)
	return err
}

const setMessageDecision = `-- name: SetMessageDecision :exec
UPDATE thread_message_view SET decision = ?1 WHERE id = ?2
`

type SetMessageDecisionParams struct {
	Decision string
	ID       uuid.UUID
}

func (q *Queries) SetMessageDecision(ctx context.Context, arg SetMessageDecisionParams) error {
	_, err := q.db.ExecContext(ctx, setMessageDecision, arg.Decision, arg.ID)
	return err
}

const upsertBundleStatusView = `-- name: UpsertBundleStatusView :exec
INSERT INTO bundle_status_view (bundle_id, status, approvals, approved_version, review_requested_at, approved_at, updated_at)
VALUES (?1, ?2, ?3, ?4,
        ?5, ?6, ?7)
ON CONFLICT (bundle_id) DO UPDATE SET status = excluded.status, approvals = excluded.approvals,
    approved_version = excluded.approved_version, review_requested_at = excluded.review_requested_at,
    approved_at = excluded.approved_at, updated_at = excluded.updated_at
`

type UpsertBundleStatusViewParams struct {
	BundleID          uuid.UUID
	Status            string
	Approvals         dbtype.JSON
	ApprovedVersion   uuid.NullUUID
	ReviewRequestedAt sql.NullTime
	ApprovedAt        sql.NullTime
	UpdatedAt         time.Time
}

func (q *Queries) UpsertBundleStatusView(ctx context.Context, arg UpsertBundleStatusViewParams) error {
	_, err := q.db.ExecContext(ctx, upsertBundleStatusView,
		arg.BundleID,
		arg.Status,
		arg.Approvals,
		arg.ApprovedVersion,
		arg.ReviewRequestedAt,
		arg.ApprovedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertThreadView = `-- name: UpsertThreadView :exec
INSERT INTO thread_view (id, workspace_id, bundle_id, profile_key, anchor_kind, anchor, addressed_to, title, blocking,
                         status, created_by, created_at, last_message_at, message_count, handoff_id, handoff_version)
VALUES (?1, ?2, ?3, ?4, ?5,
        ?6, ?7, ?8, ?9, ?10,
        ?11, ?12, ?13, ?14,
        ?15, ?16)
ON CONFLICT (id) DO UPDATE SET blocking = excluded.blocking, status = excluded.status,
    last_message_at = excluded.last_message_at, message_count = excluded.message_count
`

type UpsertThreadViewParams struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	BundleID       uuid.NullUUID
	ProfileKey     string
	AnchorKind     string
	Anchor         dbtype.JSON
	AddressedTo    string
	Title          string
	Blocking       bool
	Status         string
	CreatedBy      string
	CreatedAt      time.Time
	LastMessageAt  time.Time
	MessageCount   int64
	HandoffID      uuid.NullUUID
	HandoffVersion int64
}

func (q *Queries) UpsertThreadView(ctx context.Context, arg UpsertThreadViewParams) error {
	_, err := q.db.ExecContext(ctx, upsertThreadView,
		arg.ID,
		arg.WorkspaceID,
		arg.BundleID,
		arg.ProfileKey,
		arg.AnchorKind,
		arg.Anchor,
		arg.AddressedTo,
		arg.Title,
		arg.Blocking,
		arg.Status,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.LastMessageAt,
		arg.MessageCount,
		arg.HandoffID,
		arg.HandoffVersion,
	)
	return err
}

const upsertWaiverView = `-- name: UpsertWaiverView :exec
INSERT INTO waiver_view (id, workspace_id, bundle_id, check_slug, level, section_path, section_hash, reason, status,
                         requested_by, approvals, decided_by, created_at, updated_at, scope, trace_id, repo)
VALUES (?1, ?2, ?3, ?4, ?5,
        ?6, ?7, ?8, ?9, ?10,
        ?11, ?12, ?13, ?14,
        ?15, ?16, ?17)
ON CONFLICT (id) DO UPDATE SET status = excluded.status, approvals = excluded.approvals,
    decided_by = excluded.decided_by, updated_at = excluded.updated_at
`

type UpsertWaiverViewParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	BundleID    uuid.UUID
	CheckSlug   string
	Level       string
	SectionPath dbtype.JSON
	SectionHash string
	Reason      string
	Status      string
	RequestedBy string
	Approvals   dbtype.JSON
	DecidedBy   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Scope       string
	TraceID     string
	Repo        string
}

func (q *Queries) UpsertWaiverView(ctx context.Context, arg UpsertWaiverViewParams) error {
	_, err := q.db.ExecContext(ctx, upsertWaiverView,
		arg.ID,
		arg.WorkspaceID,
		arg.BundleID,
		arg.CheckSlug,
		arg.Level,
		arg.SectionPath,
		arg.SectionHash,
		arg.Reason,
		arg.Status,
		arg.RequestedBy,
		arg.Approvals,
		arg.DecidedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Scope,
		arg.TraceID,
		arg.Repo,
	)
	return err
}
