// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete.sql

package sqlitedb

import (
	"context"

	"github.com/google/uuid"
)

const clearBundleHead = `-- name: ClearBundleHead :exec
UPDATE bundle SET current_version_id = NULL WHERE id = ?1
`

// The bundle points at a version, and the version points at the bundle. The head goes first,
// so neither foreign key holds the other up.
func (q *Queries) ClearBundleHead(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearBundleHead, id)
	return err
}

const countBundlesUsingProfile = `-- name: CountBundlesUsingProfile :one
SELECT COUNT(*) FROM bundle WHERE workspace_id = ?1 AND profile_key = ?2 AND archived_at IS NULL
`

type CountBundlesUsingProfileParams struct {
	WorkspaceID uuid.UUID
	ProfileKey  string
}

func (q *Queries) CountBundlesUsingProfile(ctx context.Context, arg CountBundlesUsingProfileParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBundlesUsingProfile, arg.WorkspaceID, arg.ProfileKey)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAnswersOfBundle = `-- name: DeleteAnswersOfBundle :exec
DELETE FROM answer WHERE run_id IN (SELECT id FROM review_run WHERE bundle_id = ?1)
`

func (q *Queries) DeleteAnswersOfBundle(ctx context.Context, bundleID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAnswersOfBundle, bundleID)
	return err
}

const deleteBundleAuthors = `-- name: DeleteBundleAuthors :exec
DELETE FROM bundle_author WHERE bundle_id = ?1
`

func (q *Queries) DeleteBundleAuthors(ctx context.Context, bundleID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBundleAuthors, bundleID)
	return err
}

const deleteBundleReviewers = `-- name: DeleteBundleReviewers :exec
DELETE FROM bundle_reviewer WHERE bundle_id = ?1
`

func (q *Queries) DeleteBundleReviewers(ctx context.Context, bundleID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBundleReviewers, bundleID)
	return err
}

const deleteBundleRow = `-- name: DeleteBundleRow :exec
DELETE FROM bundle WHERE workspace_id = ?1 AND id = ?2
`

type DeleteBundleRowParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) DeleteBundleRow(ctx context.Context, arg DeleteBundleRowParams) error {
	_, err := q.db.ExecContext(ctx, deleteBundleRow, arg.WorkspaceID, arg.ID)
	return err
}

const deleteBundleStatusView = `-- name: DeleteBundleStatusView :exec
DELETE FROM bundle_status_view WHERE bundle_id = ?1
`

func (q *Queries) DeleteBundleStatusView(ctx context.Context, bundleID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBundleStatusView, bundleID)
	return err
}

const deleteClaimsOfBundle = `-- name: DeleteClaimsOfBundle :exec
DELETE FROM claim WHERE run_id IN (SELECT id FROM review_run WHERE bundle_id = ?1)
`

func (q *Queries) DeleteClaimsOfBundle(ctx context.Context, bundleID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteClaimsOfBundle, bundleID)
	return err
}

const deleteEventsOfStream = `-- name: DeleteEventsOfStream :exec
DELETE FROM es_events WHERE stream_id = ?1
`

func (q *Queries) DeleteEventsOfStream(ctx context.Context, streamID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEventsOfStream, streamID)
	return err
}

const deleteFindingsOfBundle = `-- name: DeleteFindingsOfBundle :exec
DELETE FROM finding WHERE run_id IN (SELECT id FROM review_run WHERE bundle_id = ?1)
`

func (q *Queries) DeleteFindingsOfBundle(ctx context.Context, bundleID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFindingsOfBundle, bundleID)
	return err
}

const deleteHandoffsOfBundle = `-- name: DeleteHandoffsOfBundle :exec
DELETE FROM handoff WHERE bundle_id = ?1
`

func (q *Queries) DeleteHandoffsOfBundle(ctx context.Context, bundleID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteHandoffsOfBundle, bundleID)
	return err
}

const deleteLinkStatesOfBundle = `-- name: DeleteLinkStatesOfBundle :exec
DELETE FROM link_state WHERE bundle_id = ?1
`

func (q *Queries) DeleteLinkStatesOfBundle(ctx context.Context, bundleID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLinkStatesOfBundle, bundleID)
	return err
}

const deleteLinksOfBundle = `-- name: DeleteLinksOfBundle :exec
DELETE FROM link WHERE from_bundle_id = ?1 OR target_bundle_id = ?1
`

func (q *Queries) DeleteLinksOfBundle(ctx context.Context, bundleID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLinksOfBundle, bundleID)
	return err
}

const deleteOrphanBlobs = `-- name: DeleteOrphanBlobs :exec
DELETE FROM blob WHERE sha256 NOT IN (SELECT sha256 FROM version_file)
`

func (q *Queries) DeleteOrphanBlobs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOrphanBlobs)
	return err
}

const deleteProfileMaintainersOf = `-- name: DeleteProfileMaintainersOf :exec
DELETE FROM profile_maintainer WHERE profile_id = ?1
`

func (q *Queries) DeleteProfileMaintainersOf(ctx context.Context, profileID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProfileMaintainersOf, profileID)
	return err
}

const deleteProfileRow = `-- name: DeleteProfileRow :exec
DELETE FROM profile WHERE workspace_id = ?1 AND id = ?2
`

type DeleteProfileRowParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) DeleteProfileRow(ctx context.Context, arg DeleteProfileRowParams) error {
	_, err := q.db.ExecContext(ctx, deleteProfileRow, arg.WorkspaceID, arg.ID)
	return err
}

const deleteProfileVersionsOf = `-- name: DeleteProfileVersionsOf :exec
DELETE FROM profile_version WHERE profile_id = ?1
`

func (q *Queries) DeleteProfileVersionsOf(ctx context.Context, profileID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProfileVersionsOf, profileID)
	return err
}

const deleteQuestionResultsOfBundle = `-- name: DeleteQuestionResultsOfBundle :exec
DELETE FROM question_result WHERE run_id IN (SELECT id FROM review_run WHERE bundle_id = ?1)
`

func (q *Queries) DeleteQuestionResultsOfBundle(ctx context.Context, bundleID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteQuestionResultsOfBundle, bundleID)
	return err
}

const deleteQuestionsOfBundle = `-- name: DeleteQuestionsOfBundle :exec
DELETE FROM question WHERE bundle_id = ?1
`

func (q *Queries) DeleteQuestionsOfBundle(ctx context.Context, bundleID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteQuestionsOfBundle, bundleID)
	return err
}

const deleteReviewRunsOfBundle = `-- name: DeleteReviewRunsOfBundle :exec
DELETE FROM review_run WHERE bundle_id = ?1
`

func (q *Queries) DeleteReviewRunsOfBundle(ctx context.Context, bundleID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteReviewRunsOfBundle, bundleID)
	return err
}

const deleteRunLinksOfBundle = `-- name: DeleteRunLinksOfBundle :exec
DELETE FROM run_link WHERE bundle_id = ?1
`

func (q *Queries) DeleteRunLinksOfBundle(ctx context.Context, bundleID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRunLinksOfBundle, bundleID)
	return err
}

const deleteStream = `-- name: DeleteStream :exec
DELETE FROM es_streams WHERE stream_id = ?1
`

func (q *Queries) DeleteStream(ctx context.Context, streamID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteStream, streamID)
	return err
}

const deleteThreadMessagesOfBundle = `-- name: DeleteThreadMessagesOfBundle :exec
DELETE FROM thread_message_view WHERE thread_id IN (SELECT id FROM thread_view WHERE bundle_id = ?1)
`

func (q *Queries) DeleteThreadMessagesOfBundle(ctx context.Context, bundleID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, deleteThreadMessagesOfBundle, bundleID)
	return err
}

const deleteThreadsOfBundle = `-- name: DeleteThreadsOfBundle :exec
DELETE FROM thread_view WHERE bundle_id = ?1
`

func (q *Queries) DeleteThreadsOfBundle(ctx context.Context, bundleID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, deleteThreadsOfBundle, bundleID)
	return err
}

const deleteVerdictsOfBundle = `-- name: DeleteVerdictsOfBundle :exec
DELETE FROM verdict WHERE run_id IN (SELECT id FROM review_run WHERE bundle_id = ?1)
`

func (q *Queries) DeleteVerdictsOfBundle(ctx context.Context, bundleID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVerdictsOfBundle, bundleID)
	return err
}

const deleteVerificationOutcomesOfBundle = `-- name: DeleteVerificationOutcomesOfBundle :exec

DELETE FROM verification_outcome WHERE run_id IN (SELECT id FROM verification_run WHERE bundle_id = ?1)
`

// Deleting a bundle removes everything that hangs off it. The order is children first,
// because the foreign keys do not cascade.
func (q *Queries) DeleteVerificationOutcomesOfBundle(ctx context.Context, bundleID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVerificationOutcomesOfBundle, bundleID)
	return err
}

const deleteVerificationRunsOfBundle = `-- name: DeleteVerificationRunsOfBundle :exec
DELETE FROM verification_run WHERE bundle_id = ?1
`

func (q *Queries) DeleteVerificationRunsOfBundle(ctx context.Context, bundleID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVerificationRunsOfBundle, bundleID)
	return err
}

const deleteVersionFilesOfBundle = `-- name: DeleteVersionFilesOfBundle :exec
DELETE FROM version_file WHERE version_id IN (SELECT id FROM version WHERE bundle_id = ?1)
`

func (q *Queries) DeleteVersionFilesOfBundle(ctx context.Context, bundleID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVersionFilesOfBundle, bundleID)
	return err
}

const deleteVersionsOfBundle = `-- name: DeleteVersionsOfBundle :exec
DELETE FROM version WHERE bundle_id = ?1
`

func (q *Queries) DeleteVersionsOfBundle(ctx context.Context, bundleID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVersionsOfBundle, bundleID)
	return err
}

const deleteWaiversOfBundle = `-- name: DeleteWaiversOfBundle :exec
DELETE FROM waiver_view WHERE bundle_id = ?1
`

func (q *Queries) DeleteWaiversOfBundle(ctx context.Context, bundleID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteWaiversOfBundle, bundleID)
	return err
}

const listBundlesUsingProfile = `-- name: ListBundlesUsingProfile :many
SELECT id, slug, title FROM bundle
WHERE workspace_id = ?1 AND profile_key = ?2 AND archived_at IS NULL
ORDER BY slug LIMIT 5
`

type ListBundlesUsingProfileParams struct {
	WorkspaceID uuid.UUID
	ProfileKey  string
}

type ListBundlesUsingProfileRow struct {
	ID    uuid.UUID
	Slug  string
	Title string
}

func (q *Queries) ListBundlesUsingProfile(ctx context.Context, arg ListBundlesUsingProfileParams) ([]ListBundlesUsingProfileRow, error) {
	rows, err := q.db.QueryContext(ctx, listBundlesUsingProfile, arg.WorkspaceID, arg.ProfileKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBundlesUsingProfileRow
	for rows.Next() {
		var i ListBundlesUsingProfileRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const threadIDsOfBundle = `-- name: ThreadIDsOfBundle :many
SELECT id FROM thread_view WHERE bundle_id = ?1
`

func (q *Queries) ThreadIDsOfBundle(ctx context.Context, bundleID uuid.NullUUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, threadIDsOfBundle, bundleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const waiverIDsOfBundle = `-- name: WaiverIDsOfBundle :many
SELECT id FROM waiver_view WHERE bundle_id = ?1
`

func (q *Queries) WaiverIDsOfBundle(ctx context.Context, bundleID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, waiverIDsOfBundle, bundleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
