// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: github.sql

package sqlitedb

import (
	"context"
	"database/sql"
	"time"

	"github.com/alternayte/speccy/db/dbtype"
	"github.com/google/uuid"
)

const deleteGithubConnection = `-- name: DeleteGithubConnection :exec
DELETE FROM github_connection WHERE workspace_id = ?1
`

func (q *Queries) DeleteGithubConnection(ctx context.Context, workspaceID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGithubConnection, workspaceID)
	return err
}

const deleteGithubSource = `-- name: DeleteGithubSource :exec
DELETE FROM github_source WHERE workspace_id = ?1 AND id = ?2
`

type DeleteGithubSourceParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) DeleteGithubSource(ctx context.Context, arg DeleteGithubSourceParams) error {
	_, err := q.db.ExecContext(ctx, deleteGithubSource, arg.WorkspaceID, arg.ID)
	return err
}

const getGithubConnection = `-- name: GetGithubConnection :one
SELECT workspace_id, token_encrypted, token_last4, api_url, updated_by, updated_at FROM github_connection WHERE workspace_id = ?1
`

func (q *Queries) GetGithubConnection(ctx context.Context, workspaceID uuid.UUID) (GithubConnection, error) {
	row := q.db.QueryRowContext(ctx, getGithubConnection, workspaceID)
	var i GithubConnection
	err := row.Scan(
		&i.WorkspaceID,
		&i.TokenEncrypted,
		&i.TokenLast4,
		&i.ApiUrl,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getGithubSource = `-- name: GetGithubSource :one
SELECT id, workspace_id, repo, branch, path, head_commit, synced_at, error, created_by, created_at FROM github_source WHERE workspace_id = ?1 AND id = ?2
`

type GetGithubSourceParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetGithubSource(ctx context.Context, arg GetGithubSourceParams) (GithubSource, error) {
	row := q.db.QueryRowContext(ctx, getGithubSource, arg.WorkspaceID, arg.ID)
	var i GithubSource
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Repo,
		&i.Branch,
		&i.Path,
		&i.HeadCommit,
		&i.SyncedAt,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertGithubSource = `-- name: InsertGithubSource :exec
INSERT INTO github_source (id, workspace_id, repo, branch, path, created_by, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
`

type InsertGithubSourceParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Repo        string
	Branch      string
	Path        string
	CreatedBy   string
	CreatedAt   time.Time
}

func (q *Queries) InsertGithubSource(ctx context.Context, arg InsertGithubSourceParams) error {
	_, err := q.db.ExecContext(ctx, insertGithubSource,
		arg.ID,
		arg.WorkspaceID,
		arg.Repo,
		arg.Branch,
		arg.Path,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const listGithubSources = `-- name: ListGithubSources :many
SELECT id, workspace_id, repo, branch, path, head_commit, synced_at, error, created_by, created_at FROM github_source WHERE workspace_id = ?1 ORDER BY repo, branch, path
`

func (q *Queries) ListGithubSources(ctx context.Context, workspaceID uuid.UUID) ([]GithubSource, error) {
	rows, err := q.db.QueryContext(ctx, listGithubSources, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GithubSource
	for rows.Next() {
		var i GithubSource
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Repo,
			&i.Branch,
			&i.Path,
			&i.HeadCommit,
			&i.SyncedAt,
			&i.Error,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBundleSourceRef = `-- name: SetBundleSourceRef :exec
UPDATE bundle SET source_ref = ?1, updated_at = ?2 WHERE id = ?3
`

type SetBundleSourceRefParams struct {
	SourceRef dbtype.JSON
	UpdatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) SetBundleSourceRef(ctx context.Context, arg SetBundleSourceRefParams) error {
	_, err := q.db.ExecContext(ctx, setBundleSourceRef, arg.SourceRef, arg.UpdatedAt, arg.ID)
	return err
}

const setGithubSourceSynced = `-- name: SetGithubSourceSynced :exec
UPDATE github_source SET head_commit = ?1, synced_at = ?2, error = ?3
WHERE id = ?4
`

type SetGithubSourceSyncedParams struct {
	HeadCommit string
	SyncedAt   sql.NullTime
	Error      string
	ID         uuid.UUID
}

func (q *Queries) SetGithubSourceSynced(ctx context.Context, arg SetGithubSourceSyncedParams) error {
	_, err := q.db.ExecContext(ctx, setGithubSourceSynced,
		arg.HeadCommit,
		arg.SyncedAt,
		arg.Error,
		arg.ID,
	)
	return err
}

const upsertGithubConnection = `-- name: UpsertGithubConnection :exec
INSERT INTO github_connection (workspace_id, token_encrypted, token_last4, api_url, updated_by, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
ON CONFLICT (workspace_id) DO UPDATE SET token_encrypted = excluded.token_encrypted, token_last4 = excluded.token_last4,
    api_url = excluded.api_url, updated_by = excluded.updated_by, updated_at = excluded.updated_at
`

type UpsertGithubConnectionParams struct {
	WorkspaceID    uuid.UUID
	TokenEncrypted []byte
	TokenLast4     string
	ApiUrl         string
	UpdatedBy      string
	UpdatedAt      time.Time
}

func (q *Queries) UpsertGithubConnection(ctx context.Context, arg UpsertGithubConnectionParams) error {
	_, err := q.db.ExecContext(ctx, upsertGithubConnection,
		arg.WorkspaceID,
		arg.TokenEncrypted,
		arg.TokenLast4,
		arg.ApiUrl,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}
