// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model.sql

package sqlitedb

import (
	"context"
	"database/sql"
	"time"

	"github.com/alternayte/speccy/db/dbtype"
	"github.com/google/uuid"
)

const addBudgetTokens = `-- name: AddBudgetTokens :exec
UPDATE budget SET tokens_used = tokens_used + ?1
WHERE workspace_id = ?2 AND month = ?3
`

type AddBudgetTokensParams struct {
	Tokens      int64
	WorkspaceID uuid.UUID
	Month       string
}

func (q *Queries) AddBudgetTokens(ctx context.Context, arg AddBudgetTokensParams) error {
	_, err := q.db.ExecContext(ctx, addBudgetTokens, arg.Tokens, arg.WorkspaceID, arg.Month)
	return err
}

const countAssignmentsForBackend = `-- name: CountAssignmentsForBackend :one
SELECT COUNT(*) FROM role_assignment WHERE workspace_id = ?1 AND backend_id = ?2
`

type CountAssignmentsForBackendParams struct {
	WorkspaceID uuid.UUID
	BackendID   uuid.UUID
}

func (q *Queries) CountAssignmentsForBackend(ctx context.Context, arg CountAssignmentsForBackendParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAssignmentsForBackend, arg.WorkspaceID, arg.BackendID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAssignment = `-- name: DeleteAssignment :exec
DELETE FROM role_assignment WHERE workspace_id = ?1 AND role = ?2
`

type DeleteAssignmentParams struct {
	WorkspaceID uuid.UUID
	Role        string
}

func (q *Queries) DeleteAssignment(ctx context.Context, arg DeleteAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, deleteAssignment, arg.WorkspaceID, arg.Role)
	return err
}

const deleteBackend = `-- name: DeleteBackend :execrows
DELETE FROM model_backend WHERE workspace_id = ?1 AND id = ?2
`

type DeleteBackendParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) DeleteBackend(ctx context.Context, arg DeleteBackendParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBackend, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAssignment = `-- name: GetAssignment :one
SELECT workspace_id, role, backend_id, model, price_in_per_mtok, price_out_per_mtok FROM role_assignment WHERE workspace_id = ?1 AND role = ?2
`

type GetAssignmentParams struct {
	WorkspaceID uuid.UUID
	Role        string
}

func (q *Queries) GetAssignment(ctx context.Context, arg GetAssignmentParams) (RoleAssignment, error) {
	row := q.db.QueryRowContext(ctx, getAssignment, arg.WorkspaceID, arg.Role)
	var i RoleAssignment
	err := row.Scan(
		&i.WorkspaceID,
		&i.Role,
		&i.BackendID,
		&i.Model,
		&i.PriceInPerMtok,
		&i.PriceOutPerMtok,
	)
	return i, err
}

const getBackend = `-- name: GetBackend :one
SELECT id, workspace_id, kind, name, config, secret_encrypted, secret_last4, created_at FROM model_backend WHERE workspace_id = ?1 AND id = ?2
`

type GetBackendParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetBackend(ctx context.Context, arg GetBackendParams) (ModelBackend, error) {
	row := q.db.QueryRowContext(ctx, getBackend, arg.WorkspaceID, arg.ID)
	var i ModelBackend
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Name,
		&i.Config,
		&i.SecretEncrypted,
		&i.SecretLast4,
		&i.CreatedAt,
	)
	return i, err
}

const getBudget = `-- name: GetBudget :one
SELECT workspace_id, month, token_limit, tokens_used FROM budget WHERE workspace_id = ?1 AND month = ?2
`

type GetBudgetParams struct {
	WorkspaceID uuid.UUID
	Month       string
}

func (q *Queries) GetBudget(ctx context.Context, arg GetBudgetParams) (Budget, error) {
	row := q.db.QueryRowContext(ctx, getBudget, arg.WorkspaceID, arg.Month)
	var i Budget
	err := row.Scan(
		&i.WorkspaceID,
		&i.Month,
		&i.TokenLimit,
		&i.TokensUsed,
	)
	return i, err
}

const insertBackend = `-- name: InsertBackend :exec
INSERT INTO model_backend (id, workspace_id, kind, name, config, secret_encrypted, secret_last4, created_at)
VALUES (?1, ?2, ?3, ?4, ?5,
        ?6, ?7, ?8)
`

type InsertBackendParams struct {
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
	Kind            string
	Name            string
	Config          dbtype.JSON
	SecretEncrypted []byte
	SecretLast4     string
	CreatedAt       time.Time
}

func (q *Queries) InsertBackend(ctx context.Context, arg InsertBackendParams) error {
	_, err := q.db.ExecContext(ctx, insertBackend,
		arg.ID,
		arg.WorkspaceID,
		arg.Kind,
		arg.Name,
		arg.Config,
		arg.SecretEncrypted,
		arg.SecretLast4,
		arg.CreatedAt,
	)
	return err
}

const insertBudget = `-- name: InsertBudget :exec
INSERT INTO budget (workspace_id, month, token_limit, tokens_used)
VALUES (?1, ?2, ?3, 0)
ON CONFLICT (workspace_id, month) DO NOTHING
`

type InsertBudgetParams struct {
	WorkspaceID uuid.UUID
	Month       string
	TokenLimit  sql.NullInt64
}

func (q *Queries) InsertBudget(ctx context.Context, arg InsertBudgetParams) error {
	_, err := q.db.ExecContext(ctx, insertBudget, arg.WorkspaceID, arg.Month, arg.TokenLimit)
	return err
}

const latestBudget = `-- name: LatestBudget :one
SELECT workspace_id, month, token_limit, tokens_used FROM budget WHERE workspace_id = ?1 ORDER BY month DESC LIMIT 1
`

func (q *Queries) LatestBudget(ctx context.Context, workspaceID uuid.UUID) (Budget, error) {
	row := q.db.QueryRowContext(ctx, latestBudget, workspaceID)
	var i Budget
	err := row.Scan(
		&i.WorkspaceID,
		&i.Month,
		&i.TokenLimit,
		&i.TokensUsed,
	)
	return i, err
}

const listAssignments = `-- name: ListAssignments :many
SELECT workspace_id, role, backend_id, model, price_in_per_mtok, price_out_per_mtok FROM role_assignment WHERE workspace_id = ?1 ORDER BY role
`

func (q *Queries) ListAssignments(ctx context.Context, workspaceID uuid.UUID) ([]RoleAssignment, error) {
	rows, err := q.db.QueryContext(ctx, listAssignments, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoleAssignment
	for rows.Next() {
		var i RoleAssignment
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Role,
			&i.BackendID,
			&i.Model,
			&i.PriceInPerMtok,
			&i.PriceOutPerMtok,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackends = `-- name: ListBackends :many
SELECT id, workspace_id, kind, name, config, secret_encrypted, secret_last4, created_at FROM model_backend WHERE workspace_id = ?1 ORDER BY name
`

func (q *Queries) ListBackends(ctx context.Context, workspaceID uuid.UUID) ([]ModelBackend, error) {
	rows, err := q.db.QueryContext(ctx, listBackends, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelBackend
	for rows.Next() {
		var i ModelBackend
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Kind,
			&i.Name,
			&i.Config,
			&i.SecretEncrypted,
			&i.SecretLast4,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBudgetLimit = `-- name: SetBudgetLimit :exec
UPDATE budget SET token_limit = ?1 WHERE workspace_id = ?2 AND month = ?3
`

type SetBudgetLimitParams struct {
	TokenLimit  sql.NullInt64
	WorkspaceID uuid.UUID
	Month       string
}

func (q *Queries) SetBudgetLimit(ctx context.Context, arg SetBudgetLimitParams) error {
	_, err := q.db.ExecContext(ctx, setBudgetLimit, arg.TokenLimit, arg.WorkspaceID, arg.Month)
	return err
}

const updateBackend = `-- name: UpdateBackend :exec
UPDATE model_backend
SET name = ?1, config = ?2, secret_encrypted = ?3,
    secret_last4 = ?4
WHERE workspace_id = ?5 AND id = ?6
`

type UpdateBackendParams struct {
	Name            string
	Config          dbtype.JSON
	SecretEncrypted []byte
	SecretLast4     string
	WorkspaceID     uuid.UUID
	ID              uuid.UUID
}

func (q *Queries) UpdateBackend(ctx context.Context, arg UpdateBackendParams) error {
	_, err := q.db.ExecContext(ctx, updateBackend,
		arg.Name,
		arg.Config,
		arg.SecretEncrypted,
		arg.SecretLast4,
		arg.WorkspaceID,
		arg.ID,
	)
	return err
}

const upsertAssignment = `-- name: UpsertAssignment :exec
INSERT INTO role_assignment (workspace_id, role, backend_id, model, price_in_per_mtok, price_out_per_mtok)
VALUES (?1, ?2, ?3, ?4, ?5,
        ?6)
ON CONFLICT (workspace_id, role) DO UPDATE
SET backend_id = excluded.backend_id, model = excluded.model, price_in_per_mtok = excluded.price_in_per_mtok,
    price_out_per_mtok = excluded.price_out_per_mtok
`

type UpsertAssignmentParams struct {
	WorkspaceID     uuid.UUID
	Role            string
	BackendID       uuid.UUID
	Model           string
	PriceInPerMtok  float64
	PriceOutPerMtok float64
}

func (q *Queries) UpsertAssignment(ctx context.Context, arg UpsertAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, upsertAssignment,
		arg.WorkspaceID,
		arg.Role,
		arg.BackendID,
		arg.Model,
		arg.PriceInPerMtok,
		arg.PriceOutPerMtok,
	)
	return err
}
