// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitedb

import (
	"time"

	"github.com/google/uuid"
)

type EsEvent struct {
	StreamID   uuid.UUID
	Version    int64
	EventType  string
	Payload    string
	Metadata   string
	OccurredAt time.Time
}

type EsStream struct {
	StreamID   uuid.UUID
	StreamType string
	Version    int64
	State      string
	UpdatedAt  time.Time
}
