// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitedb

import (
	"database/sql"
	"time"

	"github.com/alternayte/speccy/db/dbtype"
	"github.com/google/uuid"
)

type Blob struct {
	Sha256  string
	Content []byte
	Size    int64
}

type Budget struct {
	WorkspaceID uuid.UUID
	Month       string
	TokenLimit  sql.NullInt64
	TokensUsed  int64
}

type Bundle struct {
	ID               uuid.UUID
	WorkspaceID      uuid.UUID
	Slug             string
	Title            string
	ProfileKey       string
	MainDoc          string
	SourceKind       string
	SourceRef        dbtype.JSON
	CurrentVersionID uuid.NullUUID
	ArchivedAt       sql.NullTime
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type EsEvent struct {
	StreamID   uuid.UUID
	Version    int64
	EventType  string
	Payload    dbtype.JSON
	Metadata   dbtype.JSON
	OccurredAt time.Time
}

type EsStream struct {
	StreamID   uuid.UUID
	StreamType string
	Version    int64
	State      dbtype.JSON
	UpdatedAt  time.Time
}

type Finding struct {
	ID         uuid.UUID
	RunID      uuid.UUID
	CheckSlug  string
	Level      string
	Stage      string
	Relaxed    bool
	Anchor     dbtype.JSON
	Message    string
	Evidence   dbtype.JSON
	Suggestion dbtype.JSON
}

type ModelBackend struct {
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
	Kind            string
	Name            string
	Config          dbtype.JSON
	SecretEncrypted []byte
	SecretLast4     string
	CreatedAt       time.Time
}

type Profile struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	Key            string
	Name           string
	CurrentVersion int64
}

type ProfileVersion struct {
	ProfileID uuid.UUID
	Version   int64
	Yaml      string
	Template  string
	Origin    string
	CreatedBy string
	CreatedAt time.Time
}

type ReviewRun struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	BundleID       uuid.UUID
	VersionID      uuid.UUID
	ProfileKey     string
	ProfileVersion int64
	Kind           string
	Status         string
	Stage          string
	Roles          dbtype.JSON
	PromptVersions dbtype.JSON
	TokensIn       int64
	TokensOut      int64
	CostEstimate   float64
	CacheHits      int64
	Error          string
	StartedAt      time.Time
	FinishedAt     sql.NullTime
}

type RoleAssignment struct {
	WorkspaceID     uuid.UUID
	Role            string
	BackendID       uuid.UUID
	Model           string
	PriceInPerMtok  float64
	PriceOutPerMtok float64
}

type Verdict struct {
	RunID              uuid.UUID
	Result             string
	Score              int64
	Radar              dbtype.JSON
	WaiverCount        int64
	RelaxedCount       int64
	BlockingFindingIds dbtype.JSON
}

type Version struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	BundleID    uuid.UUID
	Number      int64
	CreatedBy   string
	Message     string
	CreatedAt   time.Time
}

type VersionFile struct {
	VersionID uuid.UUID
	Path      string
	Sha256    string
}

type Workspace struct {
	ID        uuid.UUID
	Name      string
	Settings  dbtype.JSON
	CreatedAt time.Time
}
