// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prbatch.sql

package sqlitedb

import (
	"context"
	"database/sql"
	"time"

	"github.com/alternayte/speccy/db/dbtype"
	"github.com/google/uuid"
)

const deletePrReviewComment = `-- name: DeletePrReviewComment :exec
DELETE FROM pr_review_comment
WHERE workspace_id = ?1 AND repo = ?2 AND pull = ?3 AND comment_id = ?4
`

type DeletePrReviewCommentParams struct {
	WorkspaceID uuid.UUID
	Repo        string
	Pull        int64
	CommentID   string
}

func (q *Queries) DeletePrReviewComment(ctx context.Context, arg DeletePrReviewCommentParams) error {
	_, err := q.db.ExecContext(ctx, deletePrReviewComment,
		arg.WorkspaceID,
		arg.Repo,
		arg.Pull,
		arg.CommentID,
	)
	return err
}

const deletePrReviewComments = `-- name: DeletePrReviewComments :exec
DELETE FROM pr_review_comment WHERE workspace_id = ?1 AND repo = ?2 AND pull = ?3
`

type DeletePrReviewCommentsParams struct {
	WorkspaceID uuid.UUID
	Repo        string
	Pull        int64
}

func (q *Queries) DeletePrReviewComments(ctx context.Context, arg DeletePrReviewCommentsParams) error {
	_, err := q.db.ExecContext(ctx, deletePrReviewComments, arg.WorkspaceID, arg.Repo, arg.Pull)
	return err
}

const getPrBatch = `-- name: GetPrBatch :one
SELECT id, workspace_id, status, parallel, stages, again, source, estimate, created_at, finished_at FROM pr_batch WHERE workspace_id = ?1 AND id = ?2
`

type GetPrBatchParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetPrBatch(ctx context.Context, arg GetPrBatchParams) (PrBatch, error) {
	row := q.db.QueryRowContext(ctx, getPrBatch, arg.WorkspaceID, arg.ID)
	var i PrBatch
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Status,
		&i.Parallel,
		&i.Stages,
		&i.Again,
		&i.Source,
		&i.Estimate,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const hasPrReview = `-- name: HasPrReview :one
SELECT count(*) FROM pr_review
WHERE workspace_id = ?1 AND repo = ?2 AND pull = ?3 AND head_sha = ?4
`

type HasPrReviewParams struct {
	WorkspaceID uuid.UUID
	Repo        string
	Pull        int64
	HeadSha     string
}

func (q *Queries) HasPrReview(ctx context.Context, arg HasPrReviewParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasPrReview,
		arg.WorkspaceID,
		arg.Repo,
		arg.Pull,
		arg.HeadSha,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertPrBatch = `-- name: InsertPrBatch :exec
INSERT INTO pr_batch (id, workspace_id, status, parallel, stages, again, source, estimate, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6,
        ?7, ?8, ?9)
`

type InsertPrBatchParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Status      string
	Parallel    int64
	Stages      dbtype.JSON
	Again       bool
	Source      string
	Estimate    dbtype.JSON
	CreatedAt   time.Time
}

func (q *Queries) InsertPrBatch(ctx context.Context, arg InsertPrBatchParams) error {
	_, err := q.db.ExecContext(ctx, insertPrBatch,
		arg.ID,
		arg.WorkspaceID,
		arg.Status,
		arg.Parallel,
		arg.Stages,
		arg.Again,
		arg.Source,
		arg.Estimate,
		arg.CreatedAt,
	)
	return err
}

const insertPrBatchItem = `-- name: InsertPrBatchItem :exec
INSERT INTO pr_batch_item (batch_id, position, repo, pull, url, state, reason, head_sha, result, comments, review_url, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7,
        ?8, ?9, ?10, ?11, ?12)
`

type InsertPrBatchItemParams struct {
	BatchID   uuid.UUID
	Position  int64
	Repo      string
	Pull      int64
	Url       string
	State     string
	Reason    string
	HeadSha   string
	Result    dbtype.JSON
	Comments  int64
	ReviewUrl string
	UpdatedAt time.Time
}

func (q *Queries) InsertPrBatchItem(ctx context.Context, arg InsertPrBatchItemParams) error {
	_, err := q.db.ExecContext(ctx, insertPrBatchItem,
		arg.BatchID,
		arg.Position,
		arg.Repo,
		arg.Pull,
		arg.Url,
		arg.State,
		arg.Reason,
		arg.HeadSha,
		arg.Result,
		arg.Comments,
		arg.ReviewUrl,
		arg.UpdatedAt,
	)
	return err
}

const insertPrReviewComment = `-- name: InsertPrReviewComment :exec
INSERT INTO pr_review_comment (workspace_id, repo, pull, comment_id, kind, ref, body, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7,
        ?8)
ON CONFLICT (workspace_id, repo, pull, comment_id, kind, ref) DO UPDATE SET body = excluded.body
`

type InsertPrReviewCommentParams struct {
	WorkspaceID uuid.UUID
	Repo        string
	Pull        int64
	CommentID   string
	Kind        string
	Ref         string
	Body        string
	CreatedAt   time.Time
}

func (q *Queries) InsertPrReviewComment(ctx context.Context, arg InsertPrReviewCommentParams) error {
	_, err := q.db.ExecContext(ctx, insertPrReviewComment,
		arg.WorkspaceID,
		arg.Repo,
		arg.Pull,
		arg.CommentID,
		arg.Kind,
		arg.Ref,
		arg.Body,
		arg.CreatedAt,
	)
	return err
}

const listActivePrBatches = `-- name: ListActivePrBatches :many
SELECT id, workspace_id, status, parallel, stages, again, source, estimate, created_at, finished_at FROM pr_batch WHERE workspace_id = ?1 AND status IN ('planned', 'running') ORDER BY created_at
`

func (q *Queries) ListActivePrBatches(ctx context.Context, workspaceID uuid.UUID) ([]PrBatch, error) {
	rows, err := q.db.QueryContext(ctx, listActivePrBatches, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrBatch
	for rows.Next() {
		var i PrBatch
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Status,
			&i.Parallel,
			&i.Stages,
			&i.Again,
			&i.Source,
			&i.Estimate,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrBatchItems = `-- name: ListPrBatchItems :many
SELECT batch_id, position, repo, pull, url, state, reason, head_sha, result, comments, review_url, updated_at, removed, config FROM pr_batch_item WHERE batch_id = ?1 ORDER BY position
`

func (q *Queries) ListPrBatchItems(ctx context.Context, batchID uuid.UUID) ([]PrBatchItem, error) {
	rows, err := q.db.QueryContext(ctx, listPrBatchItems, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrBatchItem
	for rows.Next() {
		var i PrBatchItem
		if err := rows.Scan(
			&i.BatchID,
			&i.Position,
			&i.Repo,
			&i.Pull,
			&i.Url,
			&i.State,
			&i.Reason,
			&i.HeadSha,
			&i.Result,
			&i.Comments,
			&i.ReviewUrl,
			&i.UpdatedAt,
			&i.Removed,
			&i.Config,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrReviewComments = `-- name: ListPrReviewComments :many
SELECT workspace_id, repo, pull, comment_id, kind, ref, body, created_at FROM pr_review_comment
WHERE workspace_id = ?1 AND repo = ?2 AND pull = ?3
ORDER BY created_at, comment_id, kind, ref
`

type ListPrReviewCommentsParams struct {
	WorkspaceID uuid.UUID
	Repo        string
	Pull        int64
}

func (q *Queries) ListPrReviewComments(ctx context.Context, arg ListPrReviewCommentsParams) ([]PrReviewComment, error) {
	rows, err := q.db.QueryContext(ctx, listPrReviewComments, arg.WorkspaceID, arg.Repo, arg.Pull)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrReviewComment
	for rows.Next() {
		var i PrReviewComment
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Repo,
			&i.Pull,
			&i.CommentID,
			&i.Kind,
			&i.Ref,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordPrReview = `-- name: RecordPrReview :exec
INSERT INTO pr_review (workspace_id, repo, pull, head_sha, batch_id, reviewed_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
ON CONFLICT (workspace_id, repo, pull, head_sha) DO UPDATE SET batch_id = excluded.batch_id, reviewed_at = excluded.reviewed_at
`

type RecordPrReviewParams struct {
	WorkspaceID uuid.UUID
	Repo        string
	Pull        int64
	HeadSha     string
	BatchID     uuid.NullUUID
	ReviewedAt  time.Time
}

func (q *Queries) RecordPrReview(ctx context.Context, arg RecordPrReviewParams) error {
	_, err := q.db.ExecContext(ctx, recordPrReview,
		arg.WorkspaceID,
		arg.Repo,
		arg.Pull,
		arg.HeadSha,
		arg.BatchID,
		arg.ReviewedAt,
	)
	return err
}

const setPrBatchStatus = `-- name: SetPrBatchStatus :exec
UPDATE pr_batch SET status = ?1, finished_at = ?2
WHERE workspace_id = ?3 AND id = ?4
`

type SetPrBatchStatusParams struct {
	Status      string
	FinishedAt  sql.NullTime
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) SetPrBatchStatus(ctx context.Context, arg SetPrBatchStatusParams) error {
	_, err := q.db.ExecContext(ctx, setPrBatchStatus,
		arg.Status,
		arg.FinishedAt,
		arg.WorkspaceID,
		arg.ID,
	)
	return err
}

const stopPrBatchItems = `-- name: StopPrBatchItems :exec
UPDATE pr_batch_item SET state = ?1, reason = ?2, updated_at = ?3
WHERE batch_id = ?4 AND state IN ('waiting', 'reviewing')
`

type StopPrBatchItemsParams struct {
	State     string
	Reason    string
	UpdatedAt time.Time
	BatchID   uuid.UUID
}

func (q *Queries) StopPrBatchItems(ctx context.Context, arg StopPrBatchItemsParams) error {
	_, err := q.db.ExecContext(ctx, stopPrBatchItems,
		arg.State,
		arg.Reason,
		arg.UpdatedAt,
		arg.BatchID,
	)
	return err
}

const updatePrBatchItem = `-- name: UpdatePrBatchItem :exec
UPDATE pr_batch_item SET state = ?1, reason = ?2, head_sha = ?3, result = ?4,
    comments = ?5, removed = ?6, review_url = ?7, config = ?8,
    updated_at = ?9
WHERE batch_id = ?10 AND position = ?11
`

type UpdatePrBatchItemParams struct {
	State     string
	Reason    string
	HeadSha   string
	Result    dbtype.JSON
	Comments  int64
	Removed   int64
	ReviewUrl string
	Config    dbtype.JSON
	UpdatedAt time.Time
	BatchID   uuid.UUID
	Position  int64
}

func (q *Queries) UpdatePrBatchItem(ctx context.Context, arg UpdatePrBatchItemParams) error {
	_, err := q.db.ExecContext(ctx, updatePrBatchItem,
		arg.State,
		arg.Reason,
		arg.HeadSha,
		arg.Result,
		arg.Comments,
		arg.Removed,
		arg.ReviewUrl,
		arg.Config,
		arg.UpdatedAt,
		arg.BatchID,
		arg.Position,
	)
	return err
}
