// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification.sql

package sqlitedb

import (
	"context"
	"time"

	"github.com/alternayte/speccy/db/dbtype"
	"github.com/google/uuid"
)

const getVerificationRun = `-- name: GetVerificationRun :one
SELECT id, workspace_id, bundle_id, version_id, handoff_id, repo, sha, base_sha, digest, verdict, counts, notes, stale, started_by, created_at FROM verification_run WHERE workspace_id = ?1 AND id = ?2
`

type GetVerificationRunParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetVerificationRun(ctx context.Context, arg GetVerificationRunParams) (VerificationRun, error) {
	row := q.db.QueryRowContext(ctx, getVerificationRun, arg.WorkspaceID, arg.ID)
	var i VerificationRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.BundleID,
		&i.VersionID,
		&i.HandoffID,
		&i.Repo,
		&i.Sha,
		&i.BaseSha,
		&i.Digest,
		&i.Verdict,
		&i.Counts,
		&i.Notes,
		&i.Stale,
		&i.StartedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertVerificationOutcome = `-- name: InsertVerificationOutcome :exec
INSERT INTO verification_outcome (id, run_id, trace_id, outcome, level, blocks, waived, provenance, note, targets, judgement)
VALUES (?1, ?2, ?3, ?4, ?5, ?6,
        ?7, ?8, ?9, ?10, ?11)
`

type InsertVerificationOutcomeParams struct {
	ID         uuid.UUID
	RunID      uuid.UUID
	TraceID    string
	Outcome    string
	Level      string
	Blocks     bool
	Waived     bool
	Provenance string
	Note       string
	Targets    dbtype.JSON
	Judgement  dbtype.JSON
}

func (q *Queries) InsertVerificationOutcome(ctx context.Context, arg InsertVerificationOutcomeParams) error {
	_, err := q.db.ExecContext(ctx, insertVerificationOutcome,
		arg.ID,
		arg.RunID,
		arg.TraceID,
		arg.Outcome,
		arg.Level,
		arg.Blocks,
		arg.Waived,
		arg.Provenance,
		arg.Note,
		arg.Targets,
		arg.Judgement,
	)
	return err
}

const insertVerificationRun = `-- name: InsertVerificationRun :exec
INSERT INTO verification_run (id, workspace_id, bundle_id, version_id, handoff_id, repo, sha, base_sha, digest,
                              verdict, counts, notes, started_by, created_at)
VALUES (?1, ?2, ?3, ?4, ?5,
        ?6, ?7, ?8, ?9, ?10, ?11,
        ?12, ?13, ?14)
`

type InsertVerificationRunParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	BundleID    uuid.UUID
	VersionID   uuid.UUID
	HandoffID   uuid.NullUUID
	Repo        string
	Sha         string
	BaseSha     string
	Digest      string
	Verdict     string
	Counts      dbtype.JSON
	Notes       dbtype.JSON
	StartedBy   string
	CreatedAt   time.Time
}

func (q *Queries) InsertVerificationRun(ctx context.Context, arg InsertVerificationRunParams) error {
	_, err := q.db.ExecContext(ctx, insertVerificationRun,
		arg.ID,
		arg.WorkspaceID,
		arg.BundleID,
		arg.VersionID,
		arg.HandoffID,
		arg.Repo,
		arg.Sha,
		arg.BaseSha,
		arg.Digest,
		arg.Verdict,
		arg.Counts,
		arg.Notes,
		arg.StartedBy,
		arg.CreatedAt,
	)
	return err
}

const latestVerificationSHA = `-- name: LatestVerificationSHA :one
SELECT sha FROM verification_run
WHERE bundle_id = ?1 AND repo = ?2 AND sha <> ''
ORDER BY created_at DESC, id LIMIT 1
`

type LatestVerificationSHAParams struct {
	BundleID uuid.UUID
	Repo     string
}

func (q *Queries) LatestVerificationSHA(ctx context.Context, arg LatestVerificationSHAParams) (string, error) {
	row := q.db.QueryRowContext(ctx, latestVerificationSHA, arg.BundleID, arg.Repo)
	var sha string
	err := row.Scan(&sha)
	return sha, err
}

const listVerificationOutcomes = `-- name: ListVerificationOutcomes :many
SELECT id, run_id, trace_id, outcome, level, blocks, waived, provenance, note, targets, judgement FROM verification_outcome WHERE run_id = ?1 ORDER BY trace_id
`

func (q *Queries) ListVerificationOutcomes(ctx context.Context, runID uuid.UUID) ([]VerificationOutcome, error) {
	rows, err := q.db.QueryContext(ctx, listVerificationOutcomes, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VerificationOutcome
	for rows.Next() {
		var i VerificationOutcome
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.TraceID,
			&i.Outcome,
			&i.Level,
			&i.Blocks,
			&i.Waived,
			&i.Provenance,
			&i.Note,
			&i.Targets,
			&i.Judgement,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerificationRuns = `-- name: ListVerificationRuns :many
SELECT id, workspace_id, bundle_id, version_id, handoff_id, repo, sha, base_sha, digest, verdict, counts, notes, stale, started_by, created_at FROM verification_run WHERE bundle_id = ?1 ORDER BY created_at DESC, id
`

func (q *Queries) ListVerificationRuns(ctx context.Context, bundleID uuid.UUID) ([]VerificationRun, error) {
	rows, err := q.db.QueryContext(ctx, listVerificationRuns, bundleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VerificationRun
	for rows.Next() {
		var i VerificationRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.BundleID,
			&i.VersionID,
			&i.HandoffID,
			&i.Repo,
			&i.Sha,
			&i.BaseSha,
			&i.Digest,
			&i.Verdict,
			&i.Counts,
			&i.Notes,
			&i.Stale,
			&i.StartedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceVerificationRuns = `-- name: ListWorkspaceVerificationRuns :many
SELECT id, workspace_id, bundle_id, version_id, handoff_id, repo, sha, base_sha, digest, verdict, counts, notes, stale, started_by, created_at FROM verification_run WHERE workspace_id = ?1 ORDER BY created_at DESC
`

func (q *Queries) ListWorkspaceVerificationRuns(ctx context.Context, workspaceID uuid.UUID) ([]VerificationRun, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceVerificationRuns, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VerificationRun
	for rows.Next() {
		var i VerificationRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.BundleID,
			&i.VersionID,
			&i.HandoffID,
			&i.Repo,
			&i.Sha,
			&i.BaseSha,
			&i.Digest,
			&i.Verdict,
			&i.Counts,
			&i.Notes,
			&i.Stale,
			&i.StartedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const staleVerificationRuns = `-- name: StaleVerificationRuns :exec
UPDATE verification_run SET stale = true WHERE bundle_id = ?1 AND version_id <> ?2
`

type StaleVerificationRunsParams struct {
	BundleID  uuid.UUID
	VersionID uuid.UUID
}

func (q *Queries) StaleVerificationRuns(ctx context.Context, arg StaleVerificationRunsParams) error {
	_, err := q.db.ExecContext(ctx, staleVerificationRuns, arg.BundleID, arg.VersionID)
	return err
}
