// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access.sql

package pgdb

import (
	"context"
	"database/sql"
	"time"

	"github.com/alternayte/speccy/db/dbtype"
	"github.com/google/uuid"
)

const bundleByShareToken = `-- name: BundleByShareToken :one
SELECT id, workspace_id, slug, title, source_kind, source_ref, visibility, share_token_hash, share_expires_at, archived_at, created_at, updated_at FROM bundle
WHERE share_token_hash = $1 AND visibility = 'link' AND archived_at IS NULL
  AND (share_expires_at IS NULL OR share_expires_at > $2)
`

type BundleByShareTokenParams struct {
	ShareTokenHash sql.NullString
	Now            sql.NullTime
}

func (q *Queries) BundleByShareToken(ctx context.Context, arg BundleByShareTokenParams) (Bundle, error) {
	row := q.db.QueryRowContext(ctx, bundleByShareToken, arg.ShareTokenHash, arg.Now)
	var i Bundle
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Slug,
		&i.Title,
		&i.SourceKind,
		&i.SourceRef,
		&i.Visibility,
		&i.ShareTokenHash,
		&i.ShareExpiresAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShareGuest = `-- name: GetShareGuest :one
SELECT id, bundle_id, display_name, created_at FROM share_guest WHERE id = $1
`

func (q *Queries) GetShareGuest(ctx context.Context, id uuid.UUID) (ShareGuest, error) {
	row := q.db.QueryRowContext(ctx, getShareGuest, id)
	var i ShareGuest
	err := row.Scan(
		&i.ID,
		&i.BundleID,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, settings, created_at FROM workspace WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const insertBundleAuthor = `-- name: InsertBundleAuthor :exec
INSERT INTO bundle_author (bundle_id, user_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type InsertBundleAuthorParams struct {
	BundleID uuid.UUID
	UserID   string
}

func (q *Queries) InsertBundleAuthor(ctx context.Context, arg InsertBundleAuthorParams) error {
	_, err := q.db.ExecContext(ctx, insertBundleAuthor, arg.BundleID, arg.UserID)
	return err
}

const insertInvite = `-- name: InsertInvite :exec
INSERT INTO invite (id, workspace_id, token_hash, role, expires_at, created_by, created_at)
VALUES ($1, $2, $3, $4, $5,
        $6, $7)
`

type InsertInviteParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	TokenHash   string
	Role        string
	ExpiresAt   time.Time
	CreatedBy   string
	CreatedAt   time.Time
}

func (q *Queries) InsertInvite(ctx context.Context, arg InsertInviteParams) error {
	_, err := q.db.ExecContext(ctx, insertInvite,
		arg.ID,
		arg.WorkspaceID,
		arg.TokenHash,
		arg.Role,
		arg.ExpiresAt,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const insertResetLink = `-- name: InsertResetLink :exec
INSERT INTO reset_link (id, workspace_id, token_hash, user_id, expires_at, created_by, created_at)
VALUES ($1, $2, $3, $4, $5,
        $6, $7)
`

type InsertResetLinkParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	TokenHash   string
	UserID      string
	ExpiresAt   time.Time
	CreatedBy   string
	CreatedAt   time.Time
}

func (q *Queries) InsertResetLink(ctx context.Context, arg InsertResetLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertResetLink,
		arg.ID,
		arg.WorkspaceID,
		arg.TokenHash,
		arg.UserID,
		arg.ExpiresAt,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const insertShareGuest = `-- name: InsertShareGuest :exec
INSERT INTO share_guest (id, bundle_id, display_name, created_at)
VALUES ($1, $2, $3, $4)
`

type InsertShareGuestParams struct {
	ID          uuid.UUID
	BundleID    uuid.UUID
	DisplayName string
	CreatedAt   time.Time
}

func (q *Queries) InsertShareGuest(ctx context.Context, arg InsertShareGuestParams) error {
	_, err := q.db.ExecContext(ctx, insertShareGuest,
		arg.ID,
		arg.BundleID,
		arg.DisplayName,
		arg.CreatedAt,
	)
	return err
}

const isBundleAuthor = `-- name: IsBundleAuthor :one
SELECT EXISTS (SELECT 1 FROM bundle_author WHERE bundle_id = $1 AND user_id = $2) AS author
`

type IsBundleAuthorParams struct {
	BundleID uuid.UUID
	UserID   string
}

func (q *Queries) IsBundleAuthor(ctx context.Context, arg IsBundleAuthorParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isBundleAuthor, arg.BundleID, arg.UserID)
	var author bool
	err := row.Scan(&author)
	return author, err
}

const isBundleMember = `-- name: IsBundleMember :one
SELECT EXISTS (
    SELECT 1 FROM bundle_author WHERE bundle_author.bundle_id = $1 AND bundle_author.user_id = $2
    UNION ALL
    SELECT 1 FROM spec_doc_reviewer r JOIN spec_doc d ON d.id = r.spec_doc_id
    WHERE d.bundle_id = $1 AND r.user_id = $2
) AS member
`

type IsBundleMemberParams struct {
	BundleID uuid.UUID
	UserID   string
}

// An author of the bundle, or a named member (reviewer) of a spec doc in it.
func (q *Queries) IsBundleMember(ctx context.Context, arg IsBundleMemberParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isBundleMember, arg.BundleID, arg.UserID)
	var member bool
	err := row.Scan(&member)
	return member, err
}

const listBundleAuthors = `-- name: ListBundleAuthors :many
SELECT user_id FROM bundle_author WHERE bundle_id = $1 ORDER BY user_id
`

func (q *Queries) ListBundleAuthors(ctx context.Context, bundleID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listBundleAuthors, bundleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvites = `-- name: ListInvites :many
SELECT id, workspace_id, token_hash, role, expires_at, created_by, created_at, used_at, used_by, revoked_at FROM invite WHERE workspace_id = $1 ORDER BY created_at DESC LIMIT 200
`

func (q *Queries) ListInvites(ctx context.Context, workspaceID uuid.UUID) ([]Invite, error) {
	rows, err := q.db.QueryContext(ctx, listInvites, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invite
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TokenHash,
			&i.Role,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UsedAt,
			&i.UsedBy,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpecDocReviewers = `-- name: ListSpecDocReviewers :many
SELECT user_id FROM spec_doc_reviewer WHERE spec_doc_id = $1 ORDER BY user_id
`

func (q *Queries) ListSpecDocReviewers(ctx context.Context, specDocID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSpecDocReviewers, specDocID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const peekInvite = `-- name: PeekInvite :one
SELECT id, workspace_id, token_hash, role, expires_at, created_by, created_at, used_at, used_by, revoked_at FROM invite
WHERE token_hash = $1 AND used_at IS NULL AND revoked_at IS NULL AND expires_at > $2
`

type PeekInviteParams struct {
	TokenHash string
	Now       time.Time
}

func (q *Queries) PeekInvite(ctx context.Context, arg PeekInviteParams) (Invite, error) {
	row := q.db.QueryRowContext(ctx, peekInvite, arg.TokenHash, arg.Now)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TokenHash,
		&i.Role,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UsedAt,
		&i.UsedBy,
		&i.RevokedAt,
	)
	return i, err
}

const peekResetLink = `-- name: PeekResetLink :one
SELECT id, workspace_id, token_hash, user_id, expires_at, created_by, created_at, used_at FROM reset_link WHERE token_hash = $1 AND used_at IS NULL AND expires_at > $2
`

type PeekResetLinkParams struct {
	TokenHash string
	Now       time.Time
}

func (q *Queries) PeekResetLink(ctx context.Context, arg PeekResetLinkParams) (ResetLink, error) {
	row := q.db.QueryRowContext(ctx, peekResetLink, arg.TokenHash, arg.Now)
	var i ResetLink
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const revokeInvite = `-- name: RevokeInvite :execrows
UPDATE invite SET revoked_at = $1
WHERE workspace_id = $2 AND id = $3 AND used_at IS NULL AND revoked_at IS NULL
`

type RevokeInviteParams struct {
	RevokedAt   sql.NullTime
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeInvite, arg.RevokedAt, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setBundleShare = `-- name: SetBundleShare :exec
UPDATE bundle SET share_token_hash = $1, share_expires_at = $2,
    updated_at = $3
WHERE id = $4
`

type SetBundleShareParams struct {
	ShareTokenHash sql.NullString
	ShareExpiresAt sql.NullTime
	UpdatedAt      time.Time
	ID             uuid.UUID
}

func (q *Queries) SetBundleShare(ctx context.Context, arg SetBundleShareParams) error {
	_, err := q.db.ExecContext(ctx, setBundleShare,
		arg.ShareTokenHash,
		arg.ShareExpiresAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setBundleVisibility = `-- name: SetBundleVisibility :exec
UPDATE bundle SET visibility = $1, updated_at = $2 WHERE id = $3
`

type SetBundleVisibilityParams struct {
	Visibility string
	UpdatedAt  time.Time
	ID         uuid.UUID
}

func (q *Queries) SetBundleVisibility(ctx context.Context, arg SetBundleVisibilityParams) error {
	_, err := q.db.ExecContext(ctx, setBundleVisibility, arg.Visibility, arg.UpdatedAt, arg.ID)
	return err
}

const setWorkspaceSettings = `-- name: SetWorkspaceSettings :exec
UPDATE workspace SET settings = $1 WHERE id = $2
`

type SetWorkspaceSettingsParams struct {
	Settings dbtype.JSON
	ID       uuid.UUID
}

func (q *Queries) SetWorkspaceSettings(ctx context.Context, arg SetWorkspaceSettingsParams) error {
	_, err := q.db.ExecContext(ctx, setWorkspaceSettings, arg.Settings, arg.ID)
	return err
}

const spendInvite = `-- name: SpendInvite :one
UPDATE invite SET used_at = $1, used_by = $2
WHERE token_hash = $3 AND used_at IS NULL AND revoked_at IS NULL AND expires_at > $4
RETURNING id, workspace_id, token_hash, role, expires_at, created_by, created_at, used_at, used_by, revoked_at
`

type SpendInviteParams struct {
	UsedAt    sql.NullTime
	UsedBy    sql.NullString
	TokenHash string
	Now       time.Time
}

// One conditional update spends an invite, so two parallel acceptances use it once.
func (q *Queries) SpendInvite(ctx context.Context, arg SpendInviteParams) (Invite, error) {
	row := q.db.QueryRowContext(ctx, spendInvite,
		arg.UsedAt,
		arg.UsedBy,
		arg.TokenHash,
		arg.Now,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TokenHash,
		&i.Role,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UsedAt,
		&i.UsedBy,
		&i.RevokedAt,
	)
	return i, err
}

const spendResetLink = `-- name: SpendResetLink :one
UPDATE reset_link SET used_at = $1
WHERE token_hash = $2 AND used_at IS NULL AND expires_at > $3
RETURNING id, workspace_id, token_hash, user_id, expires_at, created_by, created_at, used_at
`

type SpendResetLinkParams struct {
	UsedAt    sql.NullTime
	TokenHash string
	Now       time.Time
}

func (q *Queries) SpendResetLink(ctx context.Context, arg SpendResetLinkParams) (ResetLink, error) {
	row := q.db.QueryRowContext(ctx, spendResetLink, arg.UsedAt, arg.TokenHash, arg.Now)
	var i ResetLink
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const unspendInvite = `-- name: UnspendInvite :exec
UPDATE invite SET used_at = NULL, used_by = NULL WHERE id = $1
`

func (q *Queries) UnspendInvite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, unspendInvite, id)
	return err
}
