// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bundle.sql

package pgdb

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const getBlob = `-- name: GetBlob :one
SELECT content FROM blob WHERE sha256 = $1
`

func (q *Queries) GetBlob(ctx context.Context, sha256 string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getBlob, sha256)
	var content []byte
	err := row.Scan(&content)
	return content, err
}

const getBundle = `-- name: GetBundle :one
SELECT id, workspace_id, slug, title, profile_key, main_doc, source_kind, source_ref, current_version_id, archived_at, created_at, updated_at FROM bundle WHERE workspace_id = $1 AND id = $2
`

type GetBundleParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetBundle(ctx context.Context, arg GetBundleParams) (Bundle, error) {
	row := q.db.QueryRowContext(ctx, getBundle, arg.WorkspaceID, arg.ID)
	var i Bundle
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Slug,
		&i.Title,
		&i.ProfileKey,
		&i.MainDoc,
		&i.SourceKind,
		&i.SourceRef,
		&i.CurrentVersionID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBundleBySlug = `-- name: GetBundleBySlug :one
SELECT id, workspace_id, slug, title, profile_key, main_doc, source_kind, source_ref, current_version_id, archived_at, created_at, updated_at FROM bundle WHERE workspace_id = $1 AND slug = $2
`

type GetBundleBySlugParams struct {
	WorkspaceID uuid.UUID
	Slug        string
}

func (q *Queries) GetBundleBySlug(ctx context.Context, arg GetBundleBySlugParams) (Bundle, error) {
	row := q.db.QueryRowContext(ctx, getBundleBySlug, arg.WorkspaceID, arg.Slug)
	var i Bundle
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Slug,
		&i.Title,
		&i.ProfileKey,
		&i.MainDoc,
		&i.SourceKind,
		&i.SourceRef,
		&i.CurrentVersionID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFirstWorkspace = `-- name: GetFirstWorkspace :one
SELECT id, name, settings, created_at FROM workspace ORDER BY created_at, id LIMIT 1
`

func (q *Queries) GetFirstWorkspace(ctx context.Context) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getFirstWorkspace)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const getVersion = `-- name: GetVersion :one
SELECT id, workspace_id, bundle_id, number, created_by, message, created_at FROM version WHERE bundle_id = $1 AND id = $2
`

type GetVersionParams struct {
	BundleID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetVersion(ctx context.Context, arg GetVersionParams) (Version, error) {
	row := q.db.QueryRowContext(ctx, getVersion, arg.BundleID, arg.ID)
	var i Version
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.BundleID,
		&i.Number,
		&i.CreatedBy,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const getVersionByNumber = `-- name: GetVersionByNumber :one
SELECT id, workspace_id, bundle_id, number, created_by, message, created_at FROM version WHERE bundle_id = $1 AND number = $2
`

type GetVersionByNumberParams struct {
	BundleID uuid.UUID
	Number   int64
}

func (q *Queries) GetVersionByNumber(ctx context.Context, arg GetVersionByNumberParams) (Version, error) {
	row := q.db.QueryRowContext(ctx, getVersionByNumber, arg.BundleID, arg.Number)
	var i Version
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.BundleID,
		&i.Number,
		&i.CreatedBy,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const insertBlob = `-- name: InsertBlob :exec
INSERT INTO blob (sha256, content, size) VALUES ($1, $2, $3)
ON CONFLICT (sha256) DO NOTHING
`

type InsertBlobParams struct {
	Sha256  string
	Content []byte
	Size    int64
}

func (q *Queries) InsertBlob(ctx context.Context, arg InsertBlobParams) error {
	_, err := q.db.ExecContext(ctx, insertBlob, arg.Sha256, arg.Content, arg.Size)
	return err
}

const insertBundle = `-- name: InsertBundle :exec
INSERT INTO bundle (id, workspace_id, slug, title, profile_key, main_doc, source_kind, source_ref, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10)
`

type InsertBundleParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Slug        string
	Title       string
	ProfileKey  string
	MainDoc     string
	SourceKind  string
	SourceRef   json.RawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) InsertBundle(ctx context.Context, arg InsertBundleParams) error {
	_, err := q.db.ExecContext(ctx, insertBundle,
		arg.ID,
		arg.WorkspaceID,
		arg.Slug,
		arg.Title,
		arg.ProfileKey,
		arg.MainDoc,
		arg.SourceKind,
		arg.SourceRef,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertVersion = `-- name: InsertVersion :exec
INSERT INTO version (id, workspace_id, bundle_id, number, created_by, message, created_at)
VALUES ($1, $2, $3, $4, $5,
        $6, $7)
`

type InsertVersionParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	BundleID    uuid.UUID
	Number      int64
	CreatedBy   string
	Message     string
	CreatedAt   time.Time
}

func (q *Queries) InsertVersion(ctx context.Context, arg InsertVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertVersion,
		arg.ID,
		arg.WorkspaceID,
		arg.BundleID,
		arg.Number,
		arg.CreatedBy,
		arg.Message,
		arg.CreatedAt,
	)
	return err
}

const insertVersionFile = `-- name: InsertVersionFile :exec
INSERT INTO version_file (version_id, path, sha256) VALUES ($1, $2, $3)
`

type InsertVersionFileParams struct {
	VersionID uuid.UUID
	Path      string
	Sha256    string
}

func (q *Queries) InsertVersionFile(ctx context.Context, arg InsertVersionFileParams) error {
	_, err := q.db.ExecContext(ctx, insertVersionFile, arg.VersionID, arg.Path, arg.Sha256)
	return err
}

const insertWorkspace = `-- name: InsertWorkspace :exec
INSERT INTO workspace (id, name, settings, created_at) VALUES ($1, $2, $3, $4)
`

type InsertWorkspaceParams struct {
	ID        uuid.UUID
	Name      string
	Settings  json.RawMessage
	CreatedAt time.Time
}

func (q *Queries) InsertWorkspace(ctx context.Context, arg InsertWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, insertWorkspace,
		arg.ID,
		arg.Name,
		arg.Settings,
		arg.CreatedAt,
	)
	return err
}

const listBundles = `-- name: ListBundles :many
SELECT id, workspace_id, slug, title, profile_key, main_doc, source_kind, source_ref, current_version_id, archived_at, created_at, updated_at FROM bundle
WHERE workspace_id = $1 AND archived_at IS NULL AND slug > $2
ORDER BY slug
LIMIT $3::bigint
`

type ListBundlesParams struct {
	WorkspaceID uuid.UUID
	AfterSlug   string
	PageSize    int64
}

func (q *Queries) ListBundles(ctx context.Context, arg ListBundlesParams) ([]Bundle, error) {
	rows, err := q.db.QueryContext(ctx, listBundles, arg.WorkspaceID, arg.AfterSlug, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bundle
	for rows.Next() {
		var i Bundle
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Slug,
			&i.Title,
			&i.ProfileKey,
			&i.MainDoc,
			&i.SourceKind,
			&i.SourceRef,
			&i.CurrentVersionID,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBundlesBySource = `-- name: ListBundlesBySource :many
SELECT id, workspace_id, slug, title, profile_key, main_doc, source_kind, source_ref, current_version_id, archived_at, created_at, updated_at FROM bundle
WHERE workspace_id = $1 AND source_kind = $2
ORDER BY slug
`

type ListBundlesBySourceParams struct {
	WorkspaceID uuid.UUID
	SourceKind  string
}

func (q *Queries) ListBundlesBySource(ctx context.Context, arg ListBundlesBySourceParams) ([]Bundle, error) {
	rows, err := q.db.QueryContext(ctx, listBundlesBySource, arg.WorkspaceID, arg.SourceKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bundle
	for rows.Next() {
		var i Bundle
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Slug,
			&i.Title,
			&i.ProfileKey,
			&i.MainDoc,
			&i.SourceKind,
			&i.SourceRef,
			&i.CurrentVersionID,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionFiles = `-- name: ListVersionFiles :many
SELECT vf.path, vf.sha256, b.size
FROM version_file vf JOIN blob b ON b.sha256 = vf.sha256
WHERE vf.version_id = $1
ORDER BY vf.path
`

type ListVersionFilesRow struct {
	Path   string
	Sha256 string
	Size   int64
}

func (q *Queries) ListVersionFiles(ctx context.Context, versionID uuid.UUID) ([]ListVersionFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listVersionFiles, versionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVersionFilesRow
	for rows.Next() {
		var i ListVersionFilesRow
		if err := rows.Scan(&i.Path, &i.Sha256, &i.Size); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersions = `-- name: ListVersions :many
SELECT id, workspace_id, bundle_id, number, created_by, message, created_at FROM version
WHERE bundle_id = $1 AND number < $2
ORDER BY number DESC
LIMIT $3::bigint
`

type ListVersionsParams struct {
	BundleID     uuid.UUID
	BeforeNumber int64
	PageSize     int64
}

func (q *Queries) ListVersions(ctx context.Context, arg ListVersionsParams) ([]Version, error) {
	rows, err := q.db.QueryContext(ctx, listVersions, arg.BundleID, arg.BeforeNumber, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Version
	for rows.Next() {
		var i Version
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.BundleID,
			&i.Number,
			&i.CreatedBy,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextVersionNumber = `-- name: NextVersionNumber :one
SELECT CAST(COALESCE(MAX(number), 0) + 1 AS BIGINT) AS next FROM version WHERE bundle_id = $1
`

func (q *Queries) NextVersionNumber(ctx context.Context, bundleID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextVersionNumber, bundleID)
	var next int64
	err := row.Scan(&next)
	return next, err
}

const setBundleArchived = `-- name: SetBundleArchived :exec
UPDATE bundle SET archived_at = $1, updated_at = $2 WHERE id = $3
`

type SetBundleArchivedParams struct {
	ArchivedAt sql.NullTime
	UpdatedAt  time.Time
	ID         uuid.UUID
}

func (q *Queries) SetBundleArchived(ctx context.Context, arg SetBundleArchivedParams) error {
	_, err := q.db.ExecContext(ctx, setBundleArchived, arg.ArchivedAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateBundleHead = `-- name: UpdateBundleHead :execrows
UPDATE bundle
SET title = $1, profile_key = $2, main_doc = $3, current_version_id = $4,
    archived_at = NULL, updated_at = $5
WHERE id = $6 AND current_version_id IS NOT DISTINCT FROM $7
`

type UpdateBundleHeadParams struct {
	Title             string
	ProfileKey        string
	MainDoc           string
	CurrentVersionID  uuid.NullUUID
	UpdatedAt         time.Time
	ID                uuid.UUID
	ExpectedVersionID uuid.NullUUID
}

// The head moves only from the version the change was based on.
func (q *Queries) UpdateBundleHead(ctx context.Context, arg UpdateBundleHeadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateBundleHead,
		arg.Title,
		arg.ProfileKey,
		arg.MainDoc,
		arg.CurrentVersionID,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
