// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
)

const clearSpecDocHead = `-- name: ClearSpecDocHead :exec
UPDATE spec_doc SET current_version_id = NULL WHERE id = $1
`

// The bundle points at a version, and the version points at the bundle. The head goes first,
// so neither foreign key holds the other up.
func (q *Queries) ClearSpecDocHead(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearSpecDocHead, id)
	return err
}

const countSpecDocsInBundle = `-- name: CountSpecDocsInBundle :one
SELECT COUNT(*) FROM spec_doc WHERE bundle_id = $1
`

// Every spec doc of the bundle, archived or not.
func (q *Queries) CountSpecDocsInBundle(ctx context.Context, bundleID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSpecDocsInBundle, bundleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSpecDocsUsingProfile = `-- name: CountSpecDocsUsingProfile :one
SELECT COUNT(*) FROM spec_doc WHERE workspace_id = $1 AND profile_key = $2 AND archived_at IS NULL
`

type CountSpecDocsUsingProfileParams struct {
	WorkspaceID uuid.UUID
	ProfileKey  string
}

func (q *Queries) CountSpecDocsUsingProfile(ctx context.Context, arg CountSpecDocsUsingProfileParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSpecDocsUsingProfile, arg.WorkspaceID, arg.ProfileKey)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAnswersOfSpecDoc = `-- name: DeleteAnswersOfSpecDoc :exec
DELETE FROM answer WHERE run_id IN (SELECT id FROM review_run WHERE spec_doc_id = $1)
`

func (q *Queries) DeleteAnswersOfSpecDoc(ctx context.Context, specDocID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAnswersOfSpecDoc, specDocID)
	return err
}

const deleteBundleAuthors = `-- name: DeleteBundleAuthors :exec
DELETE FROM bundle_author WHERE bundle_id = $1
`

func (q *Queries) DeleteBundleAuthors(ctx context.Context, bundleID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBundleAuthors, bundleID)
	return err
}

const deleteBundleRow = `-- name: DeleteBundleRow :exec
DELETE FROM bundle WHERE workspace_id = $1 AND id = $2
`

type DeleteBundleRowParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) DeleteBundleRow(ctx context.Context, arg DeleteBundleRowParams) error {
	_, err := q.db.ExecContext(ctx, deleteBundleRow, arg.WorkspaceID, arg.ID)
	return err
}

const deleteClaimsOfSpecDoc = `-- name: DeleteClaimsOfSpecDoc :exec
DELETE FROM claim WHERE run_id IN (SELECT id FROM review_run WHERE spec_doc_id = $1)
`

func (q *Queries) DeleteClaimsOfSpecDoc(ctx context.Context, specDocID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteClaimsOfSpecDoc, specDocID)
	return err
}

const deleteEventsOfStream = `-- name: DeleteEventsOfStream :exec
DELETE FROM es_events WHERE stream_id = $1
`

func (q *Queries) DeleteEventsOfStream(ctx context.Context, streamID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEventsOfStream, streamID)
	return err
}

const deleteFindingsOfSpecDoc = `-- name: DeleteFindingsOfSpecDoc :exec
DELETE FROM finding WHERE run_id IN (SELECT id FROM review_run WHERE spec_doc_id = $1)
`

func (q *Queries) DeleteFindingsOfSpecDoc(ctx context.Context, specDocID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFindingsOfSpecDoc, specDocID)
	return err
}

const deleteHandoffsOfSpecDoc = `-- name: DeleteHandoffsOfSpecDoc :exec
DELETE FROM handoff WHERE spec_doc_id = $1
`

func (q *Queries) DeleteHandoffsOfSpecDoc(ctx context.Context, specDocID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteHandoffsOfSpecDoc, specDocID)
	return err
}

const deleteLinkStatesOfSpecDoc = `-- name: DeleteLinkStatesOfSpecDoc :exec
DELETE FROM link_state WHERE spec_doc_id = $1
`

func (q *Queries) DeleteLinkStatesOfSpecDoc(ctx context.Context, specDocID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLinkStatesOfSpecDoc, specDocID)
	return err
}

const deleteLinksOfSpecDoc = `-- name: DeleteLinksOfSpecDoc :exec
DELETE FROM link WHERE from_spec_doc_id = $1 OR target_spec_doc_id = $1
`

func (q *Queries) DeleteLinksOfSpecDoc(ctx context.Context, specDocID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLinksOfSpecDoc, specDocID)
	return err
}

const deleteOrphanBlobs = `-- name: DeleteOrphanBlobs :exec
DELETE FROM blob WHERE sha256 NOT IN (SELECT sha256 FROM version_file)
`

func (q *Queries) DeleteOrphanBlobs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOrphanBlobs)
	return err
}

const deleteProfileMaintainersOf = `-- name: DeleteProfileMaintainersOf :exec
DELETE FROM profile_maintainer WHERE profile_id = $1
`

func (q *Queries) DeleteProfileMaintainersOf(ctx context.Context, profileID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProfileMaintainersOf, profileID)
	return err
}

const deleteProfileRow = `-- name: DeleteProfileRow :exec
DELETE FROM profile WHERE workspace_id = $1 AND id = $2
`

type DeleteProfileRowParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) DeleteProfileRow(ctx context.Context, arg DeleteProfileRowParams) error {
	_, err := q.db.ExecContext(ctx, deleteProfileRow, arg.WorkspaceID, arg.ID)
	return err
}

const deleteProfileVersionsOf = `-- name: DeleteProfileVersionsOf :exec
DELETE FROM profile_version WHERE profile_id = $1
`

func (q *Queries) DeleteProfileVersionsOf(ctx context.Context, profileID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProfileVersionsOf, profileID)
	return err
}

const deleteQuestionResultsOfSpecDoc = `-- name: DeleteQuestionResultsOfSpecDoc :exec
DELETE FROM question_result WHERE run_id IN (SELECT id FROM review_run WHERE spec_doc_id = $1)
`

func (q *Queries) DeleteQuestionResultsOfSpecDoc(ctx context.Context, specDocID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteQuestionResultsOfSpecDoc, specDocID)
	return err
}

const deleteQuestionsOfSpecDoc = `-- name: DeleteQuestionsOfSpecDoc :exec
DELETE FROM question WHERE spec_doc_id = $1
`

func (q *Queries) DeleteQuestionsOfSpecDoc(ctx context.Context, specDocID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteQuestionsOfSpecDoc, specDocID)
	return err
}

const deleteReviewRunsOfSpecDoc = `-- name: DeleteReviewRunsOfSpecDoc :exec
DELETE FROM review_run WHERE spec_doc_id = $1
`

func (q *Queries) DeleteReviewRunsOfSpecDoc(ctx context.Context, specDocID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteReviewRunsOfSpecDoc, specDocID)
	return err
}

const deleteRunLinksOfSpecDoc = `-- name: DeleteRunLinksOfSpecDoc :exec
DELETE FROM run_link WHERE spec_doc_id = $1
`

func (q *Queries) DeleteRunLinksOfSpecDoc(ctx context.Context, specDocID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRunLinksOfSpecDoc, specDocID)
	return err
}

const deleteShareGuestsOfBundle = `-- name: DeleteShareGuestsOfBundle :exec
DELETE FROM share_guest WHERE bundle_id = $1
`

func (q *Queries) DeleteShareGuestsOfBundle(ctx context.Context, bundleID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteShareGuestsOfBundle, bundleID)
	return err
}

const deleteSpecDocReviewers = `-- name: DeleteSpecDocReviewers :exec
DELETE FROM spec_doc_reviewer WHERE spec_doc_id = $1
`

func (q *Queries) DeleteSpecDocReviewers(ctx context.Context, specDocID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSpecDocReviewers, specDocID)
	return err
}

const deleteSpecDocRow = `-- name: DeleteSpecDocRow :exec
DELETE FROM spec_doc WHERE workspace_id = $1 AND id = $2
`

type DeleteSpecDocRowParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) DeleteSpecDocRow(ctx context.Context, arg DeleteSpecDocRowParams) error {
	_, err := q.db.ExecContext(ctx, deleteSpecDocRow, arg.WorkspaceID, arg.ID)
	return err
}

const deleteSpecDocStatusView = `-- name: DeleteSpecDocStatusView :exec
DELETE FROM spec_doc_status_view WHERE spec_doc_id = $1
`

func (q *Queries) DeleteSpecDocStatusView(ctx context.Context, specDocID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSpecDocStatusView, specDocID)
	return err
}

const deleteStream = `-- name: DeleteStream :exec
DELETE FROM es_streams WHERE stream_id = $1
`

func (q *Queries) DeleteStream(ctx context.Context, streamID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteStream, streamID)
	return err
}

const deleteThreadMessagesOfSpecDoc = `-- name: DeleteThreadMessagesOfSpecDoc :exec
DELETE FROM thread_message_view WHERE thread_id IN (SELECT id FROM thread_view WHERE spec_doc_id = $1)
`

func (q *Queries) DeleteThreadMessagesOfSpecDoc(ctx context.Context, specDocID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, deleteThreadMessagesOfSpecDoc, specDocID)
	return err
}

const deleteThreadsOfSpecDoc = `-- name: DeleteThreadsOfSpecDoc :exec
DELETE FROM thread_view WHERE spec_doc_id = $1
`

func (q *Queries) DeleteThreadsOfSpecDoc(ctx context.Context, specDocID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, deleteThreadsOfSpecDoc, specDocID)
	return err
}

const deleteVerdictsOfSpecDoc = `-- name: DeleteVerdictsOfSpecDoc :exec
DELETE FROM verdict WHERE run_id IN (SELECT id FROM review_run WHERE spec_doc_id = $1)
`

func (q *Queries) DeleteVerdictsOfSpecDoc(ctx context.Context, specDocID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVerdictsOfSpecDoc, specDocID)
	return err
}

const deleteVerificationOutcomesOfSpecDoc = `-- name: DeleteVerificationOutcomesOfSpecDoc :exec

DELETE FROM verification_outcome WHERE run_id IN (SELECT id FROM verification_run WHERE spec_doc_id = $1)
`

// Deleting a bundle removes everything that hangs off it. The order is children first,
// because the foreign keys do not cascade.
func (q *Queries) DeleteVerificationOutcomesOfSpecDoc(ctx context.Context, specDocID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVerificationOutcomesOfSpecDoc, specDocID)
	return err
}

const deleteVerificationRunsOfSpecDoc = `-- name: DeleteVerificationRunsOfSpecDoc :exec
DELETE FROM verification_run WHERE spec_doc_id = $1
`

func (q *Queries) DeleteVerificationRunsOfSpecDoc(ctx context.Context, specDocID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVerificationRunsOfSpecDoc, specDocID)
	return err
}

const deleteVersionFilesOfSpecDoc = `-- name: DeleteVersionFilesOfSpecDoc :exec
DELETE FROM version_file WHERE version_id IN (SELECT id FROM version WHERE spec_doc_id = $1)
`

func (q *Queries) DeleteVersionFilesOfSpecDoc(ctx context.Context, specDocID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVersionFilesOfSpecDoc, specDocID)
	return err
}

const deleteVersionsOfSpecDoc = `-- name: DeleteVersionsOfSpecDoc :exec
DELETE FROM version WHERE spec_doc_id = $1
`

func (q *Queries) DeleteVersionsOfSpecDoc(ctx context.Context, specDocID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVersionsOfSpecDoc, specDocID)
	return err
}

const deleteWaiversOfSpecDoc = `-- name: DeleteWaiversOfSpecDoc :exec
DELETE FROM waiver_view WHERE spec_doc_id = $1
`

func (q *Queries) DeleteWaiversOfSpecDoc(ctx context.Context, specDocID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteWaiversOfSpecDoc, specDocID)
	return err
}

const listSpecDocsUsingProfile = `-- name: ListSpecDocsUsingProfile :many
SELECT id, slug, title FROM spec_doc
WHERE workspace_id = $1 AND profile_key = $2 AND archived_at IS NULL
ORDER BY slug LIMIT 5
`

type ListSpecDocsUsingProfileParams struct {
	WorkspaceID uuid.UUID
	ProfileKey  string
}

type ListSpecDocsUsingProfileRow struct {
	ID    uuid.UUID
	Slug  string
	Title string
}

func (q *Queries) ListSpecDocsUsingProfile(ctx context.Context, arg ListSpecDocsUsingProfileParams) ([]ListSpecDocsUsingProfileRow, error) {
	rows, err := q.db.QueryContext(ctx, listSpecDocsUsingProfile, arg.WorkspaceID, arg.ProfileKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpecDocsUsingProfileRow
	for rows.Next() {
		var i ListSpecDocsUsingProfileRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const threadIDsOfSpecDoc = `-- name: ThreadIDsOfSpecDoc :many
SELECT id FROM thread_view WHERE spec_doc_id = $1
`

func (q *Queries) ThreadIDsOfSpecDoc(ctx context.Context, specDocID uuid.NullUUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, threadIDsOfSpecDoc, specDocID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const waiverIDsOfSpecDoc = `-- name: WaiverIDsOfSpecDoc :many
SELECT id FROM waiver_view WHERE spec_doc_id = $1
`

func (q *Queries) WaiverIDsOfSpecDoc(ctx context.Context, specDocID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, waiverIDsOfSpecDoc, specDocID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
