// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: es.sql

package pgdb

import (
	"context"
	"time"

	"github.com/alternayte/speccy/db/dbtype"
	"github.com/google/uuid"
)

const getStream = `-- name: GetStream :one
SELECT stream_id, stream_type, version, state, updated_at
FROM es_streams
WHERE stream_id = $1
`

func (q *Queries) GetStream(ctx context.Context, streamID uuid.UUID) (EsStream, error) {
	row := q.db.QueryRowContext(ctx, getStream, streamID)
	var i EsStream
	err := row.Scan(
		&i.StreamID,
		&i.StreamType,
		&i.Version,
		&i.State,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO es_events (stream_id, version, event_type, payload, metadata, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertEventParams struct {
	StreamID   uuid.UUID
	Version    int64
	EventType  string
	Payload    dbtype.JSON
	Metadata   dbtype.JSON
	OccurredAt time.Time
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.StreamID,
		arg.Version,
		arg.EventType,
		arg.Payload,
		arg.Metadata,
		arg.OccurredAt,
	)
	return err
}

const insertStream = `-- name: InsertStream :execrows
INSERT INTO es_streams (stream_id, stream_type, version, state, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (stream_id) DO NOTHING
`

type InsertStreamParams struct {
	StreamID   uuid.UUID
	StreamType string
	Version    int64
	State      dbtype.JSON
	UpdatedAt  time.Time
}

func (q *Queries) InsertStream(ctx context.Context, arg InsertStreamParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertStream,
		arg.StreamID,
		arg.StreamType,
		arg.Version,
		arg.State,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listEvents = `-- name: ListEvents :many
SELECT stream_id, version, event_type, payload, metadata, occurred_at
FROM es_events
WHERE stream_id = $1
ORDER BY version
`

func (q *Queries) ListEvents(ctx context.Context, streamID uuid.UUID) ([]EsEvent, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, streamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EsEvent
	for rows.Next() {
		var i EsEvent
		if err := rows.Scan(
			&i.StreamID,
			&i.Version,
			&i.EventType,
			&i.Payload,
			&i.Metadata,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStream = `-- name: UpdateStream :execrows
UPDATE es_streams
SET version = $1, state = $2, updated_at = $3
WHERE stream_id = $4 AND stream_type = $5 AND version = $6
`

type UpdateStreamParams struct {
	Version         int64
	State           dbtype.JSON
	UpdatedAt       time.Time
	StreamID        uuid.UUID
	StreamType      string
	ExpectedVersion int64
}

func (q *Queries) UpdateStream(ctx context.Context, arg UpdateStreamParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateStream,
		arg.Version,
		arg.State,
		arg.UpdatedAt,
		arg.StreamID,
		arg.StreamType,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
