// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgdb

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type EsEvent struct {
	StreamID   uuid.UUID
	Version    int64
	EventType  string
	Payload    json.RawMessage
	Metadata   json.RawMessage
	OccurredAt time.Time
}

type EsStream struct {
	StreamID   uuid.UUID
	StreamType string
	Version    int64
	State      json.RawMessage
	UpdatedAt  time.Time
}
