// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgdb

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Blob struct {
	Sha256  string
	Content []byte
	Size    int64
}

type Bundle struct {
	ID               uuid.UUID
	WorkspaceID      uuid.UUID
	Slug             string
	Title            string
	ProfileKey       string
	SourceKind       string
	SourceRef        json.RawMessage
	CurrentVersionID uuid.NullUUID
	ArchivedAt       sql.NullTime
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type EsEvent struct {
	StreamID   uuid.UUID
	Version    int64
	EventType  string
	Payload    json.RawMessage
	Metadata   json.RawMessage
	OccurredAt time.Time
}

type EsStream struct {
	StreamID   uuid.UUID
	StreamType string
	Version    int64
	State      json.RawMessage
	UpdatedAt  time.Time
}

type Version struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	BundleID    uuid.UUID
	Number      int64
	CreatedBy   string
	Message     string
	CreatedAt   time.Time
}

type VersionFile struct {
	VersionID uuid.UUID
	Path      string
	Sha256    string
}

type Workspace struct {
	ID        uuid.UUID
	Name      string
	Settings  json.RawMessage
	CreatedAt time.Time
}
