// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pipeline.sql

package pgdb

import (
	"context"
	"database/sql"
	"time"

	"github.com/alternayte/speccy/db/dbtype"
	"github.com/google/uuid"
)

const claimJob = `-- name: ClaimJob :one
UPDATE job
SET status = 'running', attempts = attempts + 1, locked_until = $1
WHERE id = (
    SELECT id FROM job
    WHERE status = 'queued' OR (status = 'running' AND job.locked_until < $2)
    ORDER BY created_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, workspace_id, kind, payload, status, attempts, locked_until, last_error, created_at
`

type ClaimJobParams struct {
	LockUntil sql.NullTime
	Now       sql.NullTime
}

// The oldest queued job, or a running job whose lock expired (its worker died).
func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, claimJob, arg.LockUntil, arg.Now)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LockedUntil,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMCPConnection = `-- name: DeleteMCPConnection :exec
DELETE FROM mcp_connection WHERE workspace_id = $1 AND id = $2
`

type DeleteMCPConnectionParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) DeleteMCPConnection(ctx context.Context, arg DeleteMCPConnectionParams) error {
	_, err := q.db.ExecContext(ctx, deleteMCPConnection, arg.WorkspaceID, arg.ID)
	return err
}

const finishJob = `-- name: FinishJob :exec
UPDATE job SET status = $1, last_error = $2, locked_until = NULL
WHERE id = $3
`

type FinishJobParams struct {
	Status    string
	LastError string
	ID        uuid.UUID
}

func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) error {
	_, err := q.db.ExecContext(ctx, finishJob, arg.Status, arg.LastError, arg.ID)
	return err
}

const finishRun = `-- name: FinishRun :exec
UPDATE review_run
SET status = $1, stage = $2, error = $3, roles = $4,
    prompt_versions = $5, tokens_in = $6, tokens_out = $7,
    cost_estimate = $8, cache_hits = $9, finished_at = $10
WHERE id = $11
`

type FinishRunParams struct {
	Status         string
	Stage          string
	Error          string
	Roles          dbtype.JSON
	PromptVersions dbtype.JSON
	TokensIn       int64
	TokensOut      int64
	CostEstimate   float64
	CacheHits      int64
	FinishedAt     sql.NullTime
	ID             uuid.UUID
}

func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) error {
	_, err := q.db.ExecContext(ctx, finishRun,
		arg.Status,
		arg.Stage,
		arg.Error,
		arg.Roles,
		arg.PromptVersions,
		arg.TokensIn,
		arg.TokensOut,
		arg.CostEstimate,
		arg.CacheHits,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}

const getCache = `-- name: GetCache :one
SELECT result FROM cache_entry WHERE key_hash = $1
`

func (q *Queries) GetCache(ctx context.Context, keyHash string) (dbtype.JSON, error) {
	row := q.db.QueryRowContext(ctx, getCache, keyHash)
	var result dbtype.JSON
	err := row.Scan(&result)
	return result, err
}

const getMCPConnection = `-- name: GetMCPConnection :one
SELECT id, workspace_id, name, transport, command_or_url, secret_encrypted, secret_last4, tool_allowlist, is_search, search_tool, created_at FROM mcp_connection WHERE workspace_id = $1 AND id = $2
`

type GetMCPConnectionParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetMCPConnection(ctx context.Context, arg GetMCPConnectionParams) (McpConnection, error) {
	row := q.db.QueryRowContext(ctx, getMCPConnection, arg.WorkspaceID, arg.ID)
	var i McpConnection
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Transport,
		&i.CommandOrUrl,
		&i.SecretEncrypted,
		&i.SecretLast4,
		&i.ToolAllowlist,
		&i.IsSearch,
		&i.SearchTool,
		&i.CreatedAt,
	)
	return i, err
}

const insertClaim = `-- name: InsertClaim :exec
INSERT INTO claim (id, run_id, text, label, reason, sources, anchor)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertClaimParams struct {
	ID      uuid.UUID
	RunID   uuid.UUID
	Text    string
	Label   string
	Reason  string
	Sources dbtype.JSON
	Anchor  dbtype.JSON
}

func (q *Queries) InsertClaim(ctx context.Context, arg InsertClaimParams) error {
	_, err := q.db.ExecContext(ctx, insertClaim,
		arg.ID,
		arg.RunID,
		arg.Text,
		arg.Label,
		arg.Reason,
		arg.Sources,
		arg.Anchor,
	)
	return err
}

const insertJob = `-- name: InsertJob :exec
INSERT INTO job (id, workspace_id, kind, payload, status, created_at)
VALUES ($1, $2, $3, $4, 'queued', $5)
`

type InsertJobParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Kind        string
	Payload     dbtype.JSON
	CreatedAt   time.Time
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) error {
	_, err := q.db.ExecContext(ctx, insertJob,
		arg.ID,
		arg.WorkspaceID,
		arg.Kind,
		arg.Payload,
		arg.CreatedAt,
	)
	return err
}

const insertMCPConnection = `-- name: InsertMCPConnection :exec
INSERT INTO mcp_connection (id, workspace_id, name, transport, command_or_url, secret_encrypted, secret_last4,
                            tool_allowlist, is_search, search_tool, created_at)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9,
        $10, $11)
`

type InsertMCPConnectionParams struct {
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
	Name            string
	Transport       string
	CommandOrUrl    dbtype.JSON
	SecretEncrypted []byte
	SecretLast4     string
	ToolAllowlist   dbtype.JSON
	IsSearch        bool
	SearchTool      string
	CreatedAt       time.Time
}

func (q *Queries) InsertMCPConnection(ctx context.Context, arg InsertMCPConnectionParams) error {
	_, err := q.db.ExecContext(ctx, insertMCPConnection,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Transport,
		arg.CommandOrUrl,
		arg.SecretEncrypted,
		arg.SecretLast4,
		arg.ToolAllowlist,
		arg.IsSearch,
		arg.SearchTool,
		arg.CreatedAt,
	)
	return err
}

const listClaims = `-- name: ListClaims :many
SELECT id, run_id, text, label, reason, sources, anchor FROM claim WHERE run_id = $1 ORDER BY id
`

func (q *Queries) ListClaims(ctx context.Context, runID uuid.UUID) ([]Claim, error) {
	rows, err := q.db.QueryContext(ctx, listClaims, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Claim
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Text,
			&i.Label,
			&i.Reason,
			&i.Sources,
			&i.Anchor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCPConnections = `-- name: ListMCPConnections :many
SELECT id, workspace_id, name, transport, command_or_url, secret_encrypted, secret_last4, tool_allowlist, is_search, search_tool, created_at FROM mcp_connection WHERE workspace_id = $1 ORDER BY name
`

func (q *Queries) ListMCPConnections(ctx context.Context, workspaceID uuid.UUID) ([]McpConnection, error) {
	rows, err := q.db.QueryContext(ctx, listMCPConnections, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpConnection
	for rows.Next() {
		var i McpConnection
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Transport,
			&i.CommandOrUrl,
			&i.SecretEncrypted,
			&i.SecretLast4,
			&i.ToolAllowlist,
			&i.IsSearch,
			&i.SearchTool,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putCache = `-- name: PutCache :exec
INSERT INTO cache_entry (key_hash, result, created_at) VALUES ($1, $2, $3)
ON CONFLICT (key_hash) DO NOTHING
`

type PutCacheParams struct {
	KeyHash   string
	Result    dbtype.JSON
	CreatedAt time.Time
}

func (q *Queries) PutCache(ctx context.Context, arg PutCacheParams) error {
	_, err := q.db.ExecContext(ctx, putCache, arg.KeyHash, arg.Result, arg.CreatedAt)
	return err
}

const runningRunFor = `-- name: RunningRunFor :one
SELECT id, workspace_id, bundle_id, version_id, profile_key, profile_version, kind, status, stage, roles, prompt_versions, tokens_in, tokens_out, cost_estimate, cache_hits, error, started_at, finished_at FROM review_run
WHERE bundle_id = $1 AND kind = 'full' AND status IN ('queued', 'running')
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) RunningRunFor(ctx context.Context, bundleID uuid.UUID) (ReviewRun, error) {
	row := q.db.QueryRowContext(ctx, runningRunFor, bundleID)
	var i ReviewRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.BundleID,
		&i.VersionID,
		&i.ProfileKey,
		&i.ProfileVersion,
		&i.Kind,
		&i.Status,
		&i.Stage,
		&i.Roles,
		&i.PromptVersions,
		&i.TokensIn,
		&i.TokensOut,
		&i.CostEstimate,
		&i.CacheHits,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const updateMCPConnection = `-- name: UpdateMCPConnection :exec
UPDATE mcp_connection
SET name = $1, transport = $2, command_or_url = $3,
    secret_encrypted = $4, secret_last4 = $5,
    tool_allowlist = $6, is_search = $7, search_tool = $8
WHERE workspace_id = $9 AND id = $10
`

type UpdateMCPConnectionParams struct {
	Name            string
	Transport       string
	CommandOrUrl    dbtype.JSON
	SecretEncrypted []byte
	SecretLast4     string
	ToolAllowlist   dbtype.JSON
	IsSearch        bool
	SearchTool      string
	WorkspaceID     uuid.UUID
	ID              uuid.UUID
}

func (q *Queries) UpdateMCPConnection(ctx context.Context, arg UpdateMCPConnectionParams) error {
	_, err := q.db.ExecContext(ctx, updateMCPConnection,
		arg.Name,
		arg.Transport,
		arg.CommandOrUrl,
		arg.SecretEncrypted,
		arg.SecretLast4,
		arg.ToolAllowlist,
		arg.IsSearch,
		arg.SearchTool,
		arg.WorkspaceID,
		arg.ID,
	)
	return err
}

const updateRunProgress = `-- name: UpdateRunProgress :exec
UPDATE review_run SET status = $1, stage = $2 WHERE id = $3
`

type UpdateRunProgressParams struct {
	Status string
	Stage  string
	ID     uuid.UUID
}

func (q *Queries) UpdateRunProgress(ctx context.Context, arg UpdateRunProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateRunProgress, arg.Status, arg.Stage, arg.ID)
	return err
}
