// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pipeline.sql

package pgdb

import (
	"context"
	"database/sql"
	"time"

	"github.com/alternayte/speccy/db/dbtype"
	"github.com/google/uuid"
)

const claimJob = `-- name: ClaimJob :one
UPDATE job
SET status = 'running', attempts = attempts + 1, locked_until = $1
WHERE id = (
    SELECT id FROM job
    WHERE status = 'queued' OR (status = 'running' AND job.locked_until < $2)
    ORDER BY created_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, workspace_id, kind, payload, status, attempts, locked_until, last_error, created_at
`

type ClaimJobParams struct {
	LockUntil sql.NullTime
	Now       sql.NullTime
}

// The oldest queued job, or a running job whose lock expired (its worker died).
func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, claimJob, arg.LockUntil, arg.Now)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LockedUntil,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLinkStates = `-- name: DeleteLinkStates :exec
DELETE FROM link_state WHERE spec_doc_id = $1
`

func (q *Queries) DeleteLinkStates(ctx context.Context, specDocID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLinkStates, specDocID)
	return err
}

const deleteLinksFrom = `-- name: DeleteLinksFrom :exec
DELETE FROM link WHERE from_spec_doc_id = $1
`

func (q *Queries) DeleteLinksFrom(ctx context.Context, fromSpecDocID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLinksFrom, fromSpecDocID)
	return err
}

const deleteMCPConnection = `-- name: DeleteMCPConnection :exec
DELETE FROM mcp_connection WHERE workspace_id = $1 AND id = $2
`

type DeleteMCPConnectionParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) DeleteMCPConnection(ctx context.Context, arg DeleteMCPConnectionParams) error {
	_, err := q.db.ExecContext(ctx, deleteMCPConnection, arg.WorkspaceID, arg.ID)
	return err
}

const failActiveRun = `-- name: FailActiveRun :exec
UPDATE review_run SET status = 'failed', error = $1, finished_at = $2
WHERE id = $3 AND status IN ('queued', 'running')
`

type FailActiveRunParams struct {
	Error      string
	FinishedAt sql.NullTime
	ID         uuid.UUID
}

// Ends a run that its job left queued or running. A run that reached an end stays as it is.
func (q *Queries) FailActiveRun(ctx context.Context, arg FailActiveRunParams) error {
	_, err := q.db.ExecContext(ctx, failActiveRun, arg.Error, arg.FinishedAt, arg.ID)
	return err
}

const finishJob = `-- name: FinishJob :exec
UPDATE job SET status = $1, last_error = $2, locked_until = NULL
WHERE id = $3
`

type FinishJobParams struct {
	Status    string
	LastError string
	ID        uuid.UUID
}

func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) error {
	_, err := q.db.ExecContext(ctx, finishJob, arg.Status, arg.LastError, arg.ID)
	return err
}

const finishRun = `-- name: FinishRun :exec
UPDATE review_run
SET status = $1, stage = $2, error = $3, roles = $4,
    prompt_versions = $5, tokens_in = $6, tokens_out = $7,
    cost_estimate = $8, cache_hits = $9, notes = $10,
    stages = $11, finished_at = $12
WHERE id = $13
`

type FinishRunParams struct {
	Status         string
	Stage          string
	Error          string
	Roles          dbtype.JSON
	PromptVersions dbtype.JSON
	TokensIn       int64
	TokensOut      int64
	CostEstimate   float64
	CacheHits      int64
	Notes          dbtype.JSON
	Stages         dbtype.JSON
	FinishedAt     sql.NullTime
	ID             uuid.UUID
}

func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) error {
	_, err := q.db.ExecContext(ctx, finishRun,
		arg.Status,
		arg.Stage,
		arg.Error,
		arg.Roles,
		arg.PromptVersions,
		arg.TokensIn,
		arg.TokensOut,
		arg.CostEstimate,
		arg.CacheHits,
		arg.Notes,
		arg.Stages,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}

const getCache = `-- name: GetCache :one
SELECT result FROM cache_entry WHERE key_hash = $1
`

func (q *Queries) GetCache(ctx context.Context, keyHash string) (dbtype.JSON, error) {
	row := q.db.QueryRowContext(ctx, getCache, keyHash)
	var result dbtype.JSON
	err := row.Scan(&result)
	return result, err
}

const getMCPConnection = `-- name: GetMCPConnection :one
SELECT id, workspace_id, name, transport, command_or_url, secret_encrypted, secret_last4, tool_allowlist, is_search, search_tool, created_at, hosts, fetch_tool FROM mcp_connection WHERE workspace_id = $1 AND id = $2
`

type GetMCPConnectionParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetMCPConnection(ctx context.Context, arg GetMCPConnectionParams) (McpConnection, error) {
	row := q.db.QueryRowContext(ctx, getMCPConnection, arg.WorkspaceID, arg.ID)
	var i McpConnection
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Transport,
		&i.CommandOrUrl,
		&i.SecretEncrypted,
		&i.SecretLast4,
		&i.ToolAllowlist,
		&i.IsSearch,
		&i.SearchTool,
		&i.CreatedAt,
		&i.Hosts,
		&i.FetchTool,
	)
	return i, err
}

const getRunByID = `-- name: GetRunByID :one
SELECT id, workspace_id, spec_doc_id, version_id, profile_key, profile_version, kind, status, stage, roles, prompt_versions, tokens_in, tokens_out, cost_estimate, cache_hits, error, started_at, finished_at, notes, stages, decisions_hash, config_hash FROM review_run WHERE id = $1
`

func (q *Queries) GetRunByID(ctx context.Context, id uuid.UUID) (ReviewRun, error) {
	row := q.db.QueryRowContext(ctx, getRunByID, id)
	var i ReviewRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SpecDocID,
		&i.VersionID,
		&i.ProfileKey,
		&i.ProfileVersion,
		&i.Kind,
		&i.Status,
		&i.Stage,
		&i.Roles,
		&i.PromptVersions,
		&i.TokensIn,
		&i.TokensOut,
		&i.CostEstimate,
		&i.CacheHits,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Notes,
		&i.Stages,
		&i.DecisionsHash,
		&i.ConfigHash,
	)
	return i, err
}

const insertAnswer = `-- name: InsertAnswer :exec
INSERT INTO answer (question_id, run_id, reader_role, model_fingerprint, answer, quotes, quotes_found)
VALUES ($1, $2, $3, $4,
        $5, $6, $7)
`

type InsertAnswerParams struct {
	QuestionID       uuid.UUID
	RunID            uuid.UUID
	ReaderRole       string
	ModelFingerprint string
	Answer           string
	Quotes           dbtype.JSON
	QuotesFound      bool
}

func (q *Queries) InsertAnswer(ctx context.Context, arg InsertAnswerParams) error {
	_, err := q.db.ExecContext(ctx, insertAnswer,
		arg.QuestionID,
		arg.RunID,
		arg.ReaderRole,
		arg.ModelFingerprint,
		arg.Answer,
		arg.Quotes,
		arg.QuotesFound,
	)
	return err
}

const insertClaim = `-- name: InsertClaim :exec
INSERT INTO claim (id, run_id, text, label, reason, class, sources, anchor)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertClaimParams struct {
	ID      uuid.UUID
	RunID   uuid.UUID
	Text    string
	Label   string
	Reason  string
	Class   string
	Sources dbtype.JSON
	Anchor  dbtype.JSON
}

func (q *Queries) InsertClaim(ctx context.Context, arg InsertClaimParams) error {
	_, err := q.db.ExecContext(ctx, insertClaim,
		arg.ID,
		arg.RunID,
		arg.Text,
		arg.Label,
		arg.Reason,
		arg.Class,
		arg.Sources,
		arg.Anchor,
	)
	return err
}

const insertJob = `-- name: InsertJob :exec
INSERT INTO job (id, workspace_id, kind, payload, status, created_at)
VALUES ($1, $2, $3, $4, 'queued', $5)
`

type InsertJobParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Kind        string
	Payload     dbtype.JSON
	CreatedAt   time.Time
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) error {
	_, err := q.db.ExecContext(ctx, insertJob,
		arg.ID,
		arg.WorkspaceID,
		arg.Kind,
		arg.Payload,
		arg.CreatedAt,
	)
	return err
}

const insertLink = `-- name: InsertLink :exec
INSERT INTO link (id, workspace_id, from_spec_doc_id, kind, target_kind, target_spec_doc_id, target_ref, origin, target_url,
                  pull_number, pull_sha, pull_url)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9,
        $10, $11, $12)
`

type InsertLinkParams struct {
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
	FromSpecDocID   uuid.UUID
	Kind            string
	TargetKind      string
	TargetSpecDocID uuid.NullUUID
	TargetRef       string
	Origin          string
	TargetUrl       string
	PullNumber      int64
	PullSha         string
	PullUrl         string
}

func (q *Queries) InsertLink(ctx context.Context, arg InsertLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertLink,
		arg.ID,
		arg.WorkspaceID,
		arg.FromSpecDocID,
		arg.Kind,
		arg.TargetKind,
		arg.TargetSpecDocID,
		arg.TargetRef,
		arg.Origin,
		arg.TargetUrl,
		arg.PullNumber,
		arg.PullSha,
		arg.PullUrl,
	)
	return err
}

const insertLinkState = `-- name: InsertLinkState :exec
INSERT INTO link_state (spec_doc_id, target_ref, state, reason, checked_ref, checked_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertLinkStateParams struct {
	SpecDocID  uuid.UUID
	TargetRef  string
	State      string
	Reason     string
	CheckedRef string
	CheckedAt  time.Time
}

func (q *Queries) InsertLinkState(ctx context.Context, arg InsertLinkStateParams) error {
	_, err := q.db.ExecContext(ctx, insertLinkState,
		arg.SpecDocID,
		arg.TargetRef,
		arg.State,
		arg.Reason,
		arg.CheckedRef,
		arg.CheckedAt,
	)
	return err
}

const insertMCPConnection = `-- name: InsertMCPConnection :exec
INSERT INTO mcp_connection (id, workspace_id, name, transport, command_or_url, secret_encrypted, secret_last4,
                            tool_allowlist, is_search, search_tool, created_at, hosts, fetch_tool)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9,
        $10, $11, $12, $13)
`

type InsertMCPConnectionParams struct {
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
	Name            string
	Transport       string
	CommandOrUrl    dbtype.JSON
	SecretEncrypted []byte
	SecretLast4     string
	ToolAllowlist   dbtype.JSON
	IsSearch        bool
	SearchTool      string
	CreatedAt       time.Time
	Hosts           dbtype.JSON
	FetchTool       string
}

func (q *Queries) InsertMCPConnection(ctx context.Context, arg InsertMCPConnectionParams) error {
	_, err := q.db.ExecContext(ctx, insertMCPConnection,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Transport,
		arg.CommandOrUrl,
		arg.SecretEncrypted,
		arg.SecretLast4,
		arg.ToolAllowlist,
		arg.IsSearch,
		arg.SearchTool,
		arg.CreatedAt,
		arg.Hosts,
		arg.FetchTool,
	)
	return err
}

const insertQuestion = `-- name: InsertQuestion :exec
INSERT INTO question (id, workspace_id, spec_doc_id, version_id, number, text, level, cites, anchor, input_hash)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9, $10)
`

type InsertQuestionParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	SpecDocID   uuid.UUID
	VersionID   uuid.UUID
	Number      int64
	Text        string
	Level       string
	Cites       dbtype.JSON
	Anchor      dbtype.JSON
	InputHash   string
}

func (q *Queries) InsertQuestion(ctx context.Context, arg InsertQuestionParams) error {
	_, err := q.db.ExecContext(ctx, insertQuestion,
		arg.ID,
		arg.WorkspaceID,
		arg.SpecDocID,
		arg.VersionID,
		arg.Number,
		arg.Text,
		arg.Level,
		arg.Cites,
		arg.Anchor,
		arg.InputHash,
	)
	return err
}

const insertQuestionResult = `-- name: InsertQuestionResult :exec
INSERT INTO question_result (run_id, question_id, result, groups)
VALUES ($1, $2, $3, $4)
`

type InsertQuestionResultParams struct {
	RunID      uuid.UUID
	QuestionID uuid.UUID
	Result     string
	Groups     dbtype.JSON
}

func (q *Queries) InsertQuestionResult(ctx context.Context, arg InsertQuestionResultParams) error {
	_, err := q.db.ExecContext(ctx, insertQuestionResult,
		arg.RunID,
		arg.QuestionID,
		arg.Result,
		arg.Groups,
	)
	return err
}

const insertRunLink = `-- name: InsertRunLink :exec
INSERT INTO run_link (run_id, spec_doc_id, version_id) VALUES ($1, $2, $3)
`

type InsertRunLinkParams struct {
	RunID     uuid.UUID
	SpecDocID uuid.UUID
	VersionID uuid.UUID
}

func (q *Queries) InsertRunLink(ctx context.Context, arg InsertRunLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertRunLink, arg.RunID, arg.SpecDocID, arg.VersionID)
	return err
}

const latestQuestionResult = `-- name: LatestQuestionResult :one
SELECT r.run_id, r.question_id, r.result, r.groups FROM question_result r JOIN review_run run ON run.id = r.run_id
WHERE r.question_id = $1 AND run.status = 'complete'
ORDER BY run.started_at DESC, run.id DESC
LIMIT 1
`

// The result of a question in the last finished run that asked it.
func (q *Queries) LatestQuestionResult(ctx context.Context, questionID uuid.UUID) (QuestionResult, error) {
	row := q.db.QueryRowContext(ctx, latestQuestionResult, questionID)
	var i QuestionResult
	err := row.Scan(
		&i.RunID,
		&i.QuestionID,
		&i.Result,
		&i.Groups,
	)
	return i, err
}

const listActiveJobs = `-- name: ListActiveJobs :many
SELECT id, workspace_id, kind, payload, status, attempts, locked_until, last_error, created_at FROM job WHERE status IN ('queued', 'running') ORDER BY created_at
`

// The jobs that wait for a worker or run in one. A local owner that starts finds only jobs
// that a process before it left, and an owner that wants to exit waits until there is none.
func (q *Queries) ListActiveJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listActiveJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Kind,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LockedUntil,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnswers = `-- name: ListAnswers :many
SELECT question_id, run_id, reader_role, model_fingerprint, answer, quotes, quotes_found FROM answer WHERE run_id = $1 ORDER BY question_id, reader_role
`

func (q *Queries) ListAnswers(ctx context.Context, runID uuid.UUID) ([]Answer, error) {
	rows, err := q.db.QueryContext(ctx, listAnswers, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Answer
	for rows.Next() {
		var i Answer
		if err := rows.Scan(
			&i.QuestionID,
			&i.RunID,
			&i.ReaderRole,
			&i.ModelFingerprint,
			&i.Answer,
			&i.Quotes,
			&i.QuotesFound,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClaims = `-- name: ListClaims :many
SELECT id, run_id, text, label, reason, sources, anchor, class FROM claim WHERE run_id = $1 ORDER BY id
`

func (q *Queries) ListClaims(ctx context.Context, runID uuid.UUID) ([]Claim, error) {
	rows, err := q.db.QueryContext(ctx, listClaims, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Claim
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Text,
			&i.Label,
			&i.Reason,
			&i.Sources,
			&i.Anchor,
			&i.Class,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocQuestions = `-- name: ListDocQuestions :many
SELECT id, workspace_id, spec_doc_id, version_id, number, text, level, cites, anchor, input_hash, retired_at FROM question WHERE spec_doc_id = $1 ORDER BY number
`

// Every question the doc ever had, the retired ones too. A new question takes the next number.
func (q *Queries) ListDocQuestions(ctx context.Context, specDocID uuid.UUID) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, listDocQuestions, specDocID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SpecDocID,
			&i.VersionID,
			&i.Number,
			&i.Text,
			&i.Level,
			&i.Cites,
			&i.Anchor,
			&i.InputHash,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkStates = `-- name: ListLinkStates :many
SELECT spec_doc_id, target_ref, state, reason, checked_ref, checked_at FROM link_state WHERE spec_doc_id = $1 ORDER BY target_ref
`

func (q *Queries) ListLinkStates(ctx context.Context, specDocID uuid.UUID) ([]LinkState, error) {
	rows, err := q.db.QueryContext(ctx, listLinkStates, specDocID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinkState
	for rows.Next() {
		var i LinkState
		if err := rows.Scan(
			&i.SpecDocID,
			&i.TargetRef,
			&i.State,
			&i.Reason,
			&i.CheckedRef,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinksFrom = `-- name: ListLinksFrom :many
SELECT id, workspace_id, from_spec_doc_id, kind, target_kind, target_spec_doc_id, target_ref, origin, target_url, pull_number, pull_sha, pull_url FROM link WHERE from_spec_doc_id = $1 ORDER BY kind, target_ref
`

func (q *Queries) ListLinksFrom(ctx context.Context, fromSpecDocID uuid.UUID) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, listLinksFrom, fromSpecDocID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.FromSpecDocID,
			&i.Kind,
			&i.TargetKind,
			&i.TargetSpecDocID,
			&i.TargetRef,
			&i.Origin,
			&i.TargetUrl,
			&i.PullNumber,
			&i.PullSha,
			&i.PullUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinksTo = `-- name: ListLinksTo :many
SELECT id, workspace_id, from_spec_doc_id, kind, target_kind, target_spec_doc_id, target_ref, origin, target_url, pull_number, pull_sha, pull_url FROM link WHERE target_spec_doc_id = $1 ORDER BY kind, from_spec_doc_id
`

func (q *Queries) ListLinksTo(ctx context.Context, targetSpecDocID uuid.NullUUID) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, listLinksTo, targetSpecDocID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.FromSpecDocID,
			&i.Kind,
			&i.TargetKind,
			&i.TargetSpecDocID,
			&i.TargetRef,
			&i.Origin,
			&i.TargetUrl,
			&i.PullNumber,
			&i.PullSha,
			&i.PullUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveQuestions = `-- name: ListLiveQuestions :many
SELECT id, workspace_id, spec_doc_id, version_id, number, text, level, cites, anchor, input_hash, retired_at FROM question WHERE spec_doc_id = $1 AND retired_at IS NULL ORDER BY number
`

// The build questions a doc keeps: every question that is not retired.
func (q *Queries) ListLiveQuestions(ctx context.Context, specDocID uuid.UUID) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, listLiveQuestions, specDocID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SpecDocID,
			&i.VersionID,
			&i.Number,
			&i.Text,
			&i.Level,
			&i.Cites,
			&i.Anchor,
			&i.InputHash,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCPConnections = `-- name: ListMCPConnections :many
SELECT id, workspace_id, name, transport, command_or_url, secret_encrypted, secret_last4, tool_allowlist, is_search, search_tool, created_at, hosts, fetch_tool FROM mcp_connection WHERE workspace_id = $1 ORDER BY name
`

func (q *Queries) ListMCPConnections(ctx context.Context, workspaceID uuid.UUID) ([]McpConnection, error) {
	rows, err := q.db.QueryContext(ctx, listMCPConnections, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpConnection
	for rows.Next() {
		var i McpConnection
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Transport,
			&i.CommandOrUrl,
			&i.SecretEncrypted,
			&i.SecretLast4,
			&i.ToolAllowlist,
			&i.IsSearch,
			&i.SearchTool,
			&i.CreatedAt,
			&i.Hosts,
			&i.FetchTool,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionAnswers = `-- name: ListQuestionAnswers :many
SELECT question_id, run_id, reader_role, model_fingerprint, answer, quotes, quotes_found FROM answer WHERE run_id = $1 AND question_id = $2 ORDER BY reader_role
`

type ListQuestionAnswersParams struct {
	RunID      uuid.UUID
	QuestionID uuid.UUID
}

func (q *Queries) ListQuestionAnswers(ctx context.Context, arg ListQuestionAnswersParams) ([]Answer, error) {
	rows, err := q.db.QueryContext(ctx, listQuestionAnswers, arg.RunID, arg.QuestionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Answer
	for rows.Next() {
		var i Answer
		if err := rows.Scan(
			&i.QuestionID,
			&i.RunID,
			&i.ReaderRole,
			&i.ModelFingerprint,
			&i.Answer,
			&i.Quotes,
			&i.QuotesFound,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionResults = `-- name: ListQuestionResults :many
SELECT run_id, question_id, result, groups FROM question_result WHERE run_id = $1
`

func (q *Queries) ListQuestionResults(ctx context.Context, runID uuid.UUID) ([]QuestionResult, error) {
	rows, err := q.db.QueryContext(ctx, listQuestionResults, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestionResult
	for rows.Next() {
		var i QuestionResult
		if err := rows.Scan(
			&i.RunID,
			&i.QuestionID,
			&i.Result,
			&i.Groups,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunLinks = `-- name: ListRunLinks :many
SELECT run_id, spec_doc_id, version_id FROM run_link WHERE run_id = $1 ORDER BY spec_doc_id
`

func (q *Queries) ListRunLinks(ctx context.Context, runID uuid.UUID) ([]RunLink, error) {
	rows, err := q.db.QueryContext(ctx, listRunLinks, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunLink
	for rows.Next() {
		var i RunLink
		if err := rows.Scan(&i.RunID, &i.SpecDocID, &i.VersionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunQuestions = `-- name: ListRunQuestions :many
SELECT q.id, q.workspace_id, q.spec_doc_id, q.version_id, q.number, q.text, q.level, q.cites, q.anchor, q.input_hash, q.retired_at FROM question q JOIN question_result r ON r.question_id = q.id
WHERE r.run_id = $1 ORDER BY q.number
`

// The questions a run answered, which may be retired since.
func (q *Queries) ListRunQuestions(ctx context.Context, runID uuid.UUID) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, listRunQuestions, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SpecDocID,
			&i.VersionID,
			&i.Number,
			&i.Text,
			&i.Level,
			&i.Cites,
			&i.Anchor,
			&i.InputHash,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putCache = `-- name: PutCache :exec
INSERT INTO cache_entry (key_hash, result, created_at) VALUES ($1, $2, $3)
ON CONFLICT (key_hash) DO NOTHING
`

type PutCacheParams struct {
	KeyHash   string
	Result    dbtype.JSON
	CreatedAt time.Time
}

func (q *Queries) PutCache(ctx context.Context, arg PutCacheParams) error {
	_, err := q.db.ExecContext(ctx, putCache, arg.KeyHash, arg.Result, arg.CreatedAt)
	return err
}

const retireQuestion = `-- name: RetireQuestion :exec
UPDATE question SET retired_at = $1 WHERE id = $2
`

type RetireQuestionParams struct {
	RetiredAt sql.NullTime
	ID        uuid.UUID
}

func (q *Queries) RetireQuestion(ctx context.Context, arg RetireQuestionParams) error {
	_, err := q.db.ExecContext(ctx, retireQuestion, arg.RetiredAt, arg.ID)
	return err
}

const retireQuestions = `-- name: RetireQuestions :exec
UPDATE question SET retired_at = $1 WHERE spec_doc_id = $2 AND retired_at IS NULL
`

type RetireQuestionsParams struct {
	RetiredAt sql.NullTime
	SpecDocID uuid.UUID
}

func (q *Queries) RetireQuestions(ctx context.Context, arg RetireQuestionsParams) error {
	_, err := q.db.ExecContext(ctx, retireQuestions, arg.RetiredAt, arg.SpecDocID)
	return err
}

const runningRunFor = `-- name: RunningRunFor :one
SELECT id, workspace_id, spec_doc_id, version_id, profile_key, profile_version, kind, status, stage, roles, prompt_versions, tokens_in, tokens_out, cost_estimate, cache_hits, error, started_at, finished_at, notes, stages, decisions_hash, config_hash FROM review_run
WHERE spec_doc_id = $1 AND kind = 'full' AND status IN ('queued', 'running')
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) RunningRunFor(ctx context.Context, specDocID uuid.UUID) (ReviewRun, error) {
	row := q.db.QueryRowContext(ctx, runningRunFor, specDocID)
	var i ReviewRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SpecDocID,
		&i.VersionID,
		&i.ProfileKey,
		&i.ProfileVersion,
		&i.Kind,
		&i.Status,
		&i.Stage,
		&i.Roles,
		&i.PromptVersions,
		&i.TokensIn,
		&i.TokensOut,
		&i.CostEstimate,
		&i.CacheHits,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Notes,
		&i.Stages,
		&i.DecisionsHash,
		&i.ConfigHash,
	)
	return i, err
}

const setSpecDocFresh = `-- name: SetSpecDocFresh :exec
UPDATE spec_doc SET fresh_at = $1 WHERE id = $2
`

type SetSpecDocFreshParams struct {
	FreshAt sql.NullTime
	ID      uuid.UUID
}

// The next full review of the doc judges each rubric check from nothing.
func (q *Queries) SetSpecDocFresh(ctx context.Context, arg SetSpecDocFreshParams) error {
	_, err := q.db.ExecContext(ctx, setSpecDocFresh, arg.FreshAt, arg.ID)
	return err
}

const startRunExecution = `-- name: StartRunExecution :exec
UPDATE review_run
SET status = 'running', stage = $1, profile_version = $2
WHERE id = $3
`

type StartRunExecutionParams struct {
	Stage          string
	ProfileVersion int64
	ID             uuid.UUID
}

func (q *Queries) StartRunExecution(ctx context.Context, arg StartRunExecutionParams) error {
	_, err := q.db.ExecContext(ctx, startRunExecution, arg.Stage, arg.ProfileVersion, arg.ID)
	return err
}

const updateMCPConnection = `-- name: UpdateMCPConnection :exec
UPDATE mcp_connection
SET name = $1, transport = $2, command_or_url = $3,
    secret_encrypted = $4, secret_last4 = $5,
    tool_allowlist = $6, is_search = $7, search_tool = $8,
    hosts = $9, fetch_tool = $10
WHERE workspace_id = $11 AND id = $12
`

type UpdateMCPConnectionParams struct {
	Name            string
	Transport       string
	CommandOrUrl    dbtype.JSON
	SecretEncrypted []byte
	SecretLast4     string
	ToolAllowlist   dbtype.JSON
	IsSearch        bool
	SearchTool      string
	Hosts           dbtype.JSON
	FetchTool       string
	WorkspaceID     uuid.UUID
	ID              uuid.UUID
}

func (q *Queries) UpdateMCPConnection(ctx context.Context, arg UpdateMCPConnectionParams) error {
	_, err := q.db.ExecContext(ctx, updateMCPConnection,
		arg.Name,
		arg.Transport,
		arg.CommandOrUrl,
		arg.SecretEncrypted,
		arg.SecretLast4,
		arg.ToolAllowlist,
		arg.IsSearch,
		arg.SearchTool,
		arg.Hosts,
		arg.FetchTool,
		arg.WorkspaceID,
		arg.ID,
	)
	return err
}

const updateQuestionCites = `-- name: UpdateQuestionCites :exec
UPDATE question SET cites = $1, level = $2, anchor = $3 WHERE id = $4
`

type UpdateQuestionCitesParams struct {
	Cites  dbtype.JSON
	Level  string
	Anchor dbtype.JSON
	ID     uuid.UUID
}

func (q *Queries) UpdateQuestionCites(ctx context.Context, arg UpdateQuestionCitesParams) error {
	_, err := q.db.ExecContext(ctx, updateQuestionCites,
		arg.Cites,
		arg.Level,
		arg.Anchor,
		arg.ID,
	)
	return err
}

const updateRunProgress = `-- name: UpdateRunProgress :exec
UPDATE review_run SET status = $1, stage = $2 WHERE id = $3
`

type UpdateRunProgressParams struct {
	Status string
	Stage  string
	ID     uuid.UUID
}

func (q *Queries) UpdateRunProgress(ctx context.Context, arg UpdateRunProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateRunProgress, arg.Status, arg.Stage, arg.ID)
	return err
}
