// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetBlob(ctx context.Context, sha256 string) ([]byte, error)
	GetBundle(ctx context.Context, arg GetBundleParams) (Bundle, error)
	GetBundleBySlug(ctx context.Context, arg GetBundleBySlugParams) (Bundle, error)
	GetFirstWorkspace(ctx context.Context) (Workspace, error)
	GetStream(ctx context.Context, streamID uuid.UUID) (EsStream, error)
	GetVersion(ctx context.Context, arg GetVersionParams) (Version, error)
	GetVersionByNumber(ctx context.Context, arg GetVersionByNumberParams) (Version, error)
	InsertBlob(ctx context.Context, arg InsertBlobParams) error
	InsertBundle(ctx context.Context, arg InsertBundleParams) error
	InsertEvent(ctx context.Context, arg InsertEventParams) error
	InsertStream(ctx context.Context, arg InsertStreamParams) (int64, error)
	InsertVersion(ctx context.Context, arg InsertVersionParams) error
	InsertVersionFile(ctx context.Context, arg InsertVersionFileParams) error
	InsertWorkspace(ctx context.Context, arg InsertWorkspaceParams) error
	ListBundles(ctx context.Context, workspaceID uuid.UUID) ([]Bundle, error)
	ListBundlesBySource(ctx context.Context, arg ListBundlesBySourceParams) ([]Bundle, error)
	ListEvents(ctx context.Context, streamID uuid.UUID) ([]EsEvent, error)
	ListVersionFiles(ctx context.Context, versionID uuid.UUID) ([]ListVersionFilesRow, error)
	ListVersions(ctx context.Context, bundleID uuid.UUID) ([]Version, error)
	NextVersionNumber(ctx context.Context, bundleID uuid.UUID) (int64, error)
	SetBundleArchived(ctx context.Context, arg SetBundleArchivedParams) error
	UpdateBundleHead(ctx context.Context, arg UpdateBundleHeadParams) error
	UpdateBundleMeta(ctx context.Context, arg UpdateBundleMetaParams) error
	UpdateStream(ctx context.Context, arg UpdateStreamParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
