/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ProfilesIndexRouteImport } from './routes/profiles/index'
import { Route as ProfilesKeyRouteImport } from './routes/profiles/$key'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as BundlesBundleIdIndexRouteImport } from './routes/bundles/$bundleId/index'
import { Route as BundlesBundleIdDiffRouteImport } from './routes/bundles/$bundleId/diff'
import { Route as BundlesBundleIdTourRouteImport } from './routes/bundles/$bundleId/tour'
import { Route as BundlesBundleIdTraceRouteImport } from './routes/bundles/$bundleId/trace'
import { Route as BundlesBundleIdRunsRunIdRouteImport } from './routes/bundles/$bundleId/runs/$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesIndexRoute = ProfilesIndexRouteImport.update({
  id: '/profiles/',
  path: '/profiles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesKeyRoute = ProfilesKeyRouteImport.update({
  id: '/profiles/$key',
  path: '/profiles/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesBundleIdIndexRoute = BundlesBundleIdIndexRouteImport.update({
  id: '/bundles/$bundleId/',
  path: '/bundles/$bundleId/',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesBundleIdDiffRoute = BundlesBundleIdDiffRouteImport.update({
  id: '/bundles/$bundleId/diff',
  path: '/bundles/$bundleId/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesBundleIdTourRoute = BundlesBundleIdTourRouteImport.update({
  id: '/bundles/$bundleId/tour',
  path: '/bundles/$bundleId/tour',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesBundleIdTraceRoute = BundlesBundleIdTraceRouteImport.update({
  id: '/bundles/$bundleId/trace',
  path: '/bundles/$bundleId/trace',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesBundleIdRunsRunIdRoute =
  BundlesBundleIdRunsRunIdRouteImport.update({
    id: '/bundles/$bundleId/runs/$runId',
    path: '/bundles/$bundleId/runs/$runId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/inbox': typeof InboxRoute
  '/insights': typeof InsightsRoute
  '/invite': typeof InviteRoute
  '/reset': typeof ResetRoute
  '/sign-in': typeof SignInRoute
  '/profiles/$key': typeof ProfilesKeyRoute
  '/share/$token': typeof ShareTokenRoute
  '/profiles/': typeof ProfilesIndexRoute
  '/bundles/$bundleId/diff': typeof BundlesBundleIdDiffRoute
  '/bundles/$bundleId/tour': typeof BundlesBundleIdTourRoute
  '/bundles/$bundleId/trace': typeof BundlesBundleIdTraceRoute
  '/bundles/$bundleId/': typeof BundlesBundleIdIndexRoute
  '/bundles/$bundleId/runs/$runId': typeof BundlesBundleIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/inbox': typeof InboxRoute
  '/insights': typeof InsightsRoute
  '/invite': typeof InviteRoute
  '/reset': typeof ResetRoute
  '/sign-in': typeof SignInRoute
  '/profiles/$key': typeof ProfilesKeyRoute
  '/share/$token': typeof ShareTokenRoute
  '/profiles': typeof ProfilesIndexRoute
  '/bundles/$bundleId/diff': typeof BundlesBundleIdDiffRoute
  '/bundles/$bundleId/tour': typeof BundlesBundleIdTourRoute
  '/bundles/$bundleId/trace': typeof BundlesBundleIdTraceRoute
  '/bundles/$bundleId': typeof BundlesBundleIdIndexRoute
  '/bundles/$bundleId/runs/$runId': typeof BundlesBundleIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/inbox': typeof InboxRoute
  '/insights': typeof InsightsRoute
  '/invite': typeof InviteRoute
  '/reset': typeof ResetRoute
  '/sign-in': typeof SignInRoute
  '/profiles/$key': typeof ProfilesKeyRoute
  '/share/$token': typeof ShareTokenRoute
  '/profiles/': typeof ProfilesIndexRoute
  '/bundles/$bundleId/diff': typeof BundlesBundleIdDiffRoute
  '/bundles/$bundleId/tour': typeof BundlesBundleIdTourRoute
  '/bundles/$bundleId/trace': typeof BundlesBundleIdTraceRoute
  '/bundles/$bundleId/': typeof BundlesBundleIdIndexRoute
  '/bundles/$bundleId/runs/$runId': typeof BundlesBundleIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/inbox'
    | '/insights'
    | '/invite'
    | '/reset'
    | '/sign-in'
    | '/profiles/$key'
    | '/share/$token'
    | '/profiles/'
    | '/bundles/$bundleId/diff'
    | '/bundles/$bundleId/tour'
    | '/bundles/$bundleId/trace'
    | '/bundles/$bundleId/'
    | '/bundles/$bundleId/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/inbox'
    | '/insights'
    | '/invite'
    | '/reset'
    | '/sign-in'
    | '/profiles/$key'
    | '/share/$token'
    | '/profiles'
    | '/bundles/$bundleId/diff'
    | '/bundles/$bundleId/tour'
    | '/bundles/$bundleId/trace'
    | '/bundles/$bundleId'
    | '/bundles/$bundleId/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/inbox'
    | '/insights'
    | '/invite'
    | '/reset'
    | '/sign-in'
    | '/profiles/$key'
    | '/share/$token'
    | '/profiles/'
    | '/bundles/$bundleId/diff'
    | '/bundles/$bundleId/tour'
    | '/bundles/$bundleId/trace'
    | '/bundles/$bundleId/'
    | '/bundles/$bundleId/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  InboxRoute: typeof InboxRoute
  InsightsRoute: typeof InsightsRoute
  InviteRoute: typeof InviteRoute
  ResetRoute: typeof ResetRoute
  SignInRoute: typeof SignInRoute
  ProfilesKeyRoute: typeof ProfilesKeyRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ProfilesIndexRoute: typeof ProfilesIndexRoute
  BundlesBundleIdDiffRoute: typeof BundlesBundleIdDiffRoute
  BundlesBundleIdTourRoute: typeof BundlesBundleIdTourRoute
  BundlesBundleIdTraceRoute: typeof BundlesBundleIdTraceRoute
  BundlesBundleIdIndexRoute: typeof BundlesBundleIdIndexRoute
  BundlesBundleIdRunsRunIdRoute: typeof BundlesBundleIdRunsRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/': {
      id: '/profiles/'
      path: '/profiles'
      fullPath: '/profiles/'
      preLoaderRoute: typeof ProfilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$key': {
      id: '/profiles/$key'
      path: '/profiles/$key'
      fullPath: '/profiles/$key'
      preLoaderRoute: typeof ProfilesKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles/$bundleId/': {
      id: '/bundles/$bundleId/'
      path: '/bundles/$bundleId'
      fullPath: '/bundles/$bundleId/'
      preLoaderRoute: typeof BundlesBundleIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles/$bundleId/diff': {
      id: '/bundles/$bundleId/diff'
      path: '/bundles/$bundleId/diff'
      fullPath: '/bundles/$bundleId/diff'
      preLoaderRoute: typeof BundlesBundleIdDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles/$bundleId/tour': {
      id: '/bundles/$bundleId/tour'
      path: '/bundles/$bundleId/tour'
      fullPath: '/bundles/$bundleId/tour'
      preLoaderRoute: typeof BundlesBundleIdTourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles/$bundleId/trace': {
      id: '/bundles/$bundleId/trace'
      path: '/bundles/$bundleId/trace'
      fullPath: '/bundles/$bundleId/trace'
      preLoaderRoute: typeof BundlesBundleIdTraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles/$bundleId/runs/$runId': {
      id: '/bundles/$bundleId/runs/$runId'
      path: '/bundles/$bundleId/runs/$runId'
      fullPath: '/bundles/$bundleId/runs/$runId'
      preLoaderRoute: typeof BundlesBundleIdRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  InboxRoute: InboxRoute,
  InsightsRoute: InsightsRoute,
  InviteRoute: InviteRoute,
  ResetRoute: ResetRoute,
  SignInRoute: SignInRoute,
  ProfilesKeyRoute: ProfilesKeyRoute,
  ShareTokenRoute: ShareTokenRoute,
  ProfilesIndexRoute: ProfilesIndexRoute,
  BundlesBundleIdDiffRoute: BundlesBundleIdDiffRoute,
  BundlesBundleIdTourRoute: BundlesBundleIdTourRoute,
  BundlesBundleIdTraceRoute: BundlesBundleIdTraceRoute,
  BundlesBundleIdIndexRoute: BundlesBundleIdIndexRoute,
  BundlesBundleIdRunsRunIdRoute: BundlesBundleIdRunsRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
