/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DocsDocIdRouteImport } from './routes/docs/$docId'
import { Route as ProfilesIndexRouteImport } from './routes/profiles/index'
import { Route as ProfilesKeyRouteImport } from './routes/profiles/$key'
import { Route as ReviewsReviewIdRouteImport } from './routes/reviews/$reviewId'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as BundlesBundleIdIndexRouteImport } from './routes/bundles/$bundleId/index'
import { Route as BundlesBundleIdDocsDocIdIndexRouteImport } from './routes/bundles/$bundleId/docs/$docId/index'
import { Route as BundlesBundleIdDocsDocIdDiffRouteImport } from './routes/bundles/$bundleId/docs/$docId/diff'
import { Route as BundlesBundleIdDocsDocIdTourRouteImport } from './routes/bundles/$bundleId/docs/$docId/tour'
import { Route as BundlesBundleIdDocsDocIdTraceRouteImport } from './routes/bundles/$bundleId/docs/$docId/trace'
import { Route as BundlesBundleIdDocsDocIdRunsRunIdRouteImport } from './routes/bundles/$bundleId/docs/$docId/runs/$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDocIdRoute = DocsDocIdRouteImport.update({
  id: '/docs/$docId',
  path: '/docs/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesIndexRoute = ProfilesIndexRouteImport.update({
  id: '/profiles/',
  path: '/profiles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesKeyRoute = ProfilesKeyRouteImport.update({
  id: '/profiles/$key',
  path: '/profiles/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsReviewIdRoute = ReviewsReviewIdRouteImport.update({
  id: '/reviews/$reviewId',
  path: '/reviews/$reviewId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesBundleIdIndexRoute = BundlesBundleIdIndexRouteImport.update({
  id: '/bundles/$bundleId/',
  path: '/bundles/$bundleId/',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesBundleIdDocsDocIdIndexRoute =
  BundlesBundleIdDocsDocIdIndexRouteImport.update({
    id: '/bundles/$bundleId/docs/$docId/',
    path: '/bundles/$bundleId/docs/$docId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const BundlesBundleIdDocsDocIdDiffRoute =
  BundlesBundleIdDocsDocIdDiffRouteImport.update({
    id: '/bundles/$bundleId/docs/$docId/diff',
    path: '/bundles/$bundleId/docs/$docId/diff',
    getParentRoute: () => rootRouteImport,
  } as any)
const BundlesBundleIdDocsDocIdTourRoute =
  BundlesBundleIdDocsDocIdTourRouteImport.update({
    id: '/bundles/$bundleId/docs/$docId/tour',
    path: '/bundles/$bundleId/docs/$docId/tour',
    getParentRoute: () => rootRouteImport,
  } as any)
const BundlesBundleIdDocsDocIdTraceRoute =
  BundlesBundleIdDocsDocIdTraceRouteImport.update({
    id: '/bundles/$bundleId/docs/$docId/trace',
    path: '/bundles/$bundleId/docs/$docId/trace',
    getParentRoute: () => rootRouteImport,
  } as any)
const BundlesBundleIdDocsDocIdRunsRunIdRoute =
  BundlesBundleIdDocsDocIdRunsRunIdRouteImport.update({
    id: '/bundles/$bundleId/docs/$docId/runs/$runId',
    path: '/bundles/$bundleId/docs/$docId/runs/$runId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/inbox': typeof InboxRoute
  '/insights': typeof InsightsRoute
  '/invite': typeof InviteRoute
  '/reset': typeof ResetRoute
  '/sign-in': typeof SignInRoute
  '/docs/$docId': typeof DocsDocIdRoute
  '/profiles/$key': typeof ProfilesKeyRoute
  '/reviews/$reviewId': typeof ReviewsReviewIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/profiles/': typeof ProfilesIndexRoute
  '/bundles/$bundleId/': typeof BundlesBundleIdIndexRoute
  '/bundles/$bundleId/docs/$docId/diff': typeof BundlesBundleIdDocsDocIdDiffRoute
  '/bundles/$bundleId/docs/$docId/tour': typeof BundlesBundleIdDocsDocIdTourRoute
  '/bundles/$bundleId/docs/$docId/trace': typeof BundlesBundleIdDocsDocIdTraceRoute
  '/bundles/$bundleId/docs/$docId/': typeof BundlesBundleIdDocsDocIdIndexRoute
  '/bundles/$bundleId/docs/$docId/runs/$runId': typeof BundlesBundleIdDocsDocIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/inbox': typeof InboxRoute
  '/insights': typeof InsightsRoute
  '/invite': typeof InviteRoute
  '/reset': typeof ResetRoute
  '/sign-in': typeof SignInRoute
  '/docs/$docId': typeof DocsDocIdRoute
  '/profiles/$key': typeof ProfilesKeyRoute
  '/reviews/$reviewId': typeof ReviewsReviewIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/profiles': typeof ProfilesIndexRoute
  '/bundles/$bundleId': typeof BundlesBundleIdIndexRoute
  '/bundles/$bundleId/docs/$docId/diff': typeof BundlesBundleIdDocsDocIdDiffRoute
  '/bundles/$bundleId/docs/$docId/tour': typeof BundlesBundleIdDocsDocIdTourRoute
  '/bundles/$bundleId/docs/$docId/trace': typeof BundlesBundleIdDocsDocIdTraceRoute
  '/bundles/$bundleId/docs/$docId': typeof BundlesBundleIdDocsDocIdIndexRoute
  '/bundles/$bundleId/docs/$docId/runs/$runId': typeof BundlesBundleIdDocsDocIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/inbox': typeof InboxRoute
  '/insights': typeof InsightsRoute
  '/invite': typeof InviteRoute
  '/reset': typeof ResetRoute
  '/sign-in': typeof SignInRoute
  '/docs/$docId': typeof DocsDocIdRoute
  '/profiles/$key': typeof ProfilesKeyRoute
  '/reviews/$reviewId': typeof ReviewsReviewIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/profiles/': typeof ProfilesIndexRoute
  '/bundles/$bundleId/': typeof BundlesBundleIdIndexRoute
  '/bundles/$bundleId/docs/$docId/diff': typeof BundlesBundleIdDocsDocIdDiffRoute
  '/bundles/$bundleId/docs/$docId/tour': typeof BundlesBundleIdDocsDocIdTourRoute
  '/bundles/$bundleId/docs/$docId/trace': typeof BundlesBundleIdDocsDocIdTraceRoute
  '/bundles/$bundleId/docs/$docId/': typeof BundlesBundleIdDocsDocIdIndexRoute
  '/bundles/$bundleId/docs/$docId/runs/$runId': typeof BundlesBundleIdDocsDocIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/inbox'
    | '/insights'
    | '/invite'
    | '/reset'
    | '/sign-in'
    | '/docs/$docId'
    | '/profiles/$key'
    | '/reviews/$reviewId'
    | '/share/$token'
    | '/profiles/'
    | '/bundles/$bundleId/'
    | '/bundles/$bundleId/docs/$docId/diff'
    | '/bundles/$bundleId/docs/$docId/tour'
    | '/bundles/$bundleId/docs/$docId/trace'
    | '/bundles/$bundleId/docs/$docId/'
    | '/bundles/$bundleId/docs/$docId/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/inbox'
    | '/insights'
    | '/invite'
    | '/reset'
    | '/sign-in'
    | '/docs/$docId'
    | '/profiles/$key'
    | '/reviews/$reviewId'
    | '/share/$token'
    | '/profiles'
    | '/bundles/$bundleId'
    | '/bundles/$bundleId/docs/$docId/diff'
    | '/bundles/$bundleId/docs/$docId/tour'
    | '/bundles/$bundleId/docs/$docId/trace'
    | '/bundles/$bundleId/docs/$docId'
    | '/bundles/$bundleId/docs/$docId/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/inbox'
    | '/insights'
    | '/invite'
    | '/reset'
    | '/sign-in'
    | '/docs/$docId'
    | '/profiles/$key'
    | '/reviews/$reviewId'
    | '/share/$token'
    | '/profiles/'
    | '/bundles/$bundleId/'
    | '/bundles/$bundleId/docs/$docId/diff'
    | '/bundles/$bundleId/docs/$docId/tour'
    | '/bundles/$bundleId/docs/$docId/trace'
    | '/bundles/$bundleId/docs/$docId/'
    | '/bundles/$bundleId/docs/$docId/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  InboxRoute: typeof InboxRoute
  InsightsRoute: typeof InsightsRoute
  InviteRoute: typeof InviteRoute
  ResetRoute: typeof ResetRoute
  SignInRoute: typeof SignInRoute
  DocsDocIdRoute: typeof DocsDocIdRoute
  ProfilesKeyRoute: typeof ProfilesKeyRoute
  ReviewsReviewIdRoute: typeof ReviewsReviewIdRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ProfilesIndexRoute: typeof ProfilesIndexRoute
  BundlesBundleIdIndexRoute: typeof BundlesBundleIdIndexRoute
  BundlesBundleIdDocsDocIdDiffRoute: typeof BundlesBundleIdDocsDocIdDiffRoute
  BundlesBundleIdDocsDocIdTourRoute: typeof BundlesBundleIdDocsDocIdTourRoute
  BundlesBundleIdDocsDocIdTraceRoute: typeof BundlesBundleIdDocsDocIdTraceRoute
  BundlesBundleIdDocsDocIdIndexRoute: typeof BundlesBundleIdDocsDocIdIndexRoute
  BundlesBundleIdDocsDocIdRunsRunIdRoute: typeof BundlesBundleIdDocsDocIdRunsRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$docId': {
      id: '/docs/$docId'
      path: '/docs/$docId'
      fullPath: '/docs/$docId'
      preLoaderRoute: typeof DocsDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/': {
      id: '/profiles/'
      path: '/profiles'
      fullPath: '/profiles/'
      preLoaderRoute: typeof ProfilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$key': {
      id: '/profiles/$key'
      path: '/profiles/$key'
      fullPath: '/profiles/$key'
      preLoaderRoute: typeof ProfilesKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$reviewId': {
      id: '/reviews/$reviewId'
      path: '/reviews/$reviewId'
      fullPath: '/reviews/$reviewId'
      preLoaderRoute: typeof ReviewsReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles/$bundleId/': {
      id: '/bundles/$bundleId/'
      path: '/bundles/$bundleId'
      fullPath: '/bundles/$bundleId/'
      preLoaderRoute: typeof BundlesBundleIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles/$bundleId/docs/$docId/': {
      id: '/bundles/$bundleId/docs/$docId/'
      path: '/bundles/$bundleId/docs/$docId'
      fullPath: '/bundles/$bundleId/docs/$docId/'
      preLoaderRoute: typeof BundlesBundleIdDocsDocIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles/$bundleId/docs/$docId/diff': {
      id: '/bundles/$bundleId/docs/$docId/diff'
      path: '/bundles/$bundleId/docs/$docId/diff'
      fullPath: '/bundles/$bundleId/docs/$docId/diff'
      preLoaderRoute: typeof BundlesBundleIdDocsDocIdDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles/$bundleId/docs/$docId/tour': {
      id: '/bundles/$bundleId/docs/$docId/tour'
      path: '/bundles/$bundleId/docs/$docId/tour'
      fullPath: '/bundles/$bundleId/docs/$docId/tour'
      preLoaderRoute: typeof BundlesBundleIdDocsDocIdTourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles/$bundleId/docs/$docId/trace': {
      id: '/bundles/$bundleId/docs/$docId/trace'
      path: '/bundles/$bundleId/docs/$docId/trace'
      fullPath: '/bundles/$bundleId/docs/$docId/trace'
      preLoaderRoute: typeof BundlesBundleIdDocsDocIdTraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles/$bundleId/docs/$docId/runs/$runId': {
      id: '/bundles/$bundleId/docs/$docId/runs/$runId'
      path: '/bundles/$bundleId/docs/$docId/runs/$runId'
      fullPath: '/bundles/$bundleId/docs/$docId/runs/$runId'
      preLoaderRoute: typeof BundlesBundleIdDocsDocIdRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  InboxRoute: InboxRoute,
  InsightsRoute: InsightsRoute,
  InviteRoute: InviteRoute,
  ResetRoute: ResetRoute,
  SignInRoute: SignInRoute,
  DocsDocIdRoute: DocsDocIdRoute,
  ProfilesKeyRoute: ProfilesKeyRoute,
  ReviewsReviewIdRoute: ReviewsReviewIdRoute,
  ShareTokenRoute: ShareTokenRoute,
  ProfilesIndexRoute: ProfilesIndexRoute,
  BundlesBundleIdIndexRoute: BundlesBundleIdIndexRoute,
  BundlesBundleIdDocsDocIdDiffRoute: BundlesBundleIdDocsDocIdDiffRoute,
  BundlesBundleIdDocsDocIdTourRoute: BundlesBundleIdDocsDocIdTourRoute,
  BundlesBundleIdDocsDocIdTraceRoute: BundlesBundleIdDocsDocIdTraceRoute,
  BundlesBundleIdDocsDocIdIndexRoute: BundlesBundleIdDocsDocIdIndexRoute,
  BundlesBundleIdDocsDocIdRunsRunIdRoute:
    BundlesBundleIdDocsDocIdRunsRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
